Apply naming recommendations to all snippets and samples
gradle/gradle pull request #14198
Opened 2020-08-18 18:29 UTC by donat

2020-08-18 18:29 UTC, donat commented
@bot-gradle test this

2020-08-19 11:59 UTC, donat commented
@bot-gradle test this

2020-08-24 07:26 UTC, donat commented
@bot-gradle test this

2020-08-24 07:51 UTC, jjohannes requested changes
👍

2020-08-24 07:51 UTC, jjohannes commented on subprojects/docs/src/docsTest/java/org/gradle/docs/samples/ExemplarExternalSamplesFunctionalTest.java
> +import org.gradle.integtests.fixtures.DonatLocalInitScriptModifier;
I guess this sneaked in :)

2020-08-24 09:20 UTC, jjohannes approved these changes

2020-08-25 12:13 UTC, merged