Add toolchain support to release notes
gradle/gradle pull request #14477
Opened 2020-09-09 11:28 UTC by bmuskalla

2020-09-09 11:28 UTC, bmuskalla commented
@bot-gradle test QF

2020-09-09 15:21 UTC, pioterj requested changes

2020-09-09 15:21 UTC, pioterj commented on subprojects/docs/src/docs/release/notes.md
> +This release introduces a new concept called Java Toolchains to Gradle. A Java Toolchain (from now on referred to simply as toolchain) is a set of tools (e.g. a java compiler), taken from a local JRE
"java compiler" -> "Java compiler"

2020-09-09 15:21 UTC, pioterj commented on subprojects/docs/src/docs/release/notes.md
> +But instead of manually specifying this for the various tasks, toolchains provide a holistic set of requirements that define what the build needs.
Remove "But"

2020-09-09 15:21 UTC, pioterj commented on subprojects/docs/src/docs/release/notes.md
> +Compile tasks use `javac` as their compiler, test and exec tasks may use the `java` command while `javadoc` will be used to generate documentation. All taken from the selected toolchain above.
Let's make the first sentence consistent so it does not mix "use", "may use" and "will be used" for equivalent items.

2020-09-09 15:21 UTC, pioterj commented on subprojects/docs/src/docs/release/notes.md
> +With this, Gradle handles setting up the build and environment accordingly. It will detect locally installed Java versions to run the build according to the specified requirements. By default, Gradle
"With this" -> "Using the snippet above"

2020-09-10 09:54 UTC, ljacomet commented
@pioterj I addressed your comments and also moved the demo to be right before the documentation links, after all the text. I could not find a good place for it earlier without breaking the flow of the explanation.

Let me know what you think of the content now.

2020-09-10 13:55 UTC, pioterj commented
@ljacomet Could you give me a link to the rendered version?

2020-09-10 15:16 UTC, ljacomet commented
Changes included in #14489

2020-09-10 15:16 UTC, closed without merging