Jacoco documentation: fix a small issue
gradle/gradle pull request #14519
Opened 2020-09-15 17:07 UTC by tasomaniac

### Context

While integrating the Jacoco plugin into our repo, I realized a small build performance issue with the suggestion provided in the docs.

When `test` task is always finalized with `jacocoTestReport`, it causes jacoco report to be generated when not needed. Example: Recent versions of IntelliJ IDEA delegates to Gradle to run a single test. This is done during development workflow and supposed to be very fast. In this case, we don't need to generate jacoco report every time a single test is run.

### Solution

Remove the suggestion to make tests being finalized by jacoco task. Making `jacocoTestReport` depend on the test task should be enough. 

Also change the example usage to use Task configuration avoidance APIs.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] *N/A* Provide** integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] *N/A* Provide** unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

2020-11-18 21:35 UTC, JLLeitschuh commented
I'd rather document the performance impact over removing the suggestion. Can you instead update the documentation with a better solution?

2020-11-18 21:59 UTC, tasomaniac commented
I cannot see how it can be improved since it is just simply unnecessary. With my suggestion, it is simpler. If you want jaco report, you simply run jaco tasks and they automatically depend on tests. All works fine. 

If you have any suggestions, I'm open to change it.

2020-11-18 22:22 UTC, JLLeitschuh commented
🤔 Perhaps suggest that they attach the jacoco tasks to `check`? Maybe?

2020-11-18 22:22 UTC, JLLeitschuh commented
@big-guy your thoughts here?

2020-11-18 23:10 UTC, tasomaniac commented
That's a good idea. I will change it.

2020-11-19 14:16 UTC, JLLeitschuh commented
Thanks @tasomaniac!

2020-11-19 14:16 UTC, JLLeitschuh commented
@bot-gradle help

2020-11-19 14:18 UTC, JLLeitschuh commented
@bot-gradle test SanityCheck plz

2020-11-19 14:20 UTC, JLLeitschuh commented
@bot-gradle test QuickFeedback

2021-01-31 14:27 UTC, tasomaniac commented
Let's keep this open. It is small but very useful documentation change

2021-04-01 15:04 UTC, tasomaniac commented
Any updates on this? Can someone trigger the CI again? There is not much reason why this would fail in the CI?

2021-04-15 08:18 UTC, ljacomet requested changes
Please make snippet changes in the context of where this is included.
See https://docs.gradle.org/current/userguide/jacoco_plugin.html#sec:jacoco_getting_started and the text before example 2

2021-04-15 08:18 UTC, ljacomet commented on subprojects/docs/src/snippets/testing/jacoco-quickstart/groovy/build.gradle
> +tasks.named("check").configure {
These changes make no sense in isolation. The text before the inclusion of that snippet should be adapted as well then.

Another option is to make it clearer here that what is proposed is _optional_

2021-06-04 11:25 UTC, donat commented
I'm closing this PR as there hasn't been any progress for quite a while now. @tasomaniac let me know if you are still interested in finishing this work.

2021-06-04 11:25 UTC, closed without merging