slightly clearer explanation about overlapping outputs
gradle/gradle pull request #14680
Opened 2020-09-28 17:56 UTC by mathjeff

Signed-off-by: Jeff Gaston <gastoj3@gmail.com>

### Context
I was getting this message in my build and it wasn't clear to me whether this meant that Gradle couldn't parse the build cache entry or whether there were multiple tasks that declared the same file as an output.

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

2020-09-28 18:28 UTC, mathjeff commented
I think it would also be really helpful if Gradle were to specify which other task(s) declared the same output, although I didn't happen to notice how to do that

2020-09-28 20:13 UTC, lptr requested changes
Thanks for the suggestion for the improvement. I think that message can use some clarifying indeed. I added some suggestion on how we could do it even better.

2020-09-28 20:13 UTC, lptr commented on subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/DefaultTaskCacheabilityResolver.java
> +                "Gradle does not know how file '" + relativePath + "' was created (output property '" + overlappingOutputs.getPropertyName() + "'). Task output caching requires exclusive access to ou
Transforms have no ability to declare their outputs (and something similar is among the plans for tasks, but I digress), so let's not mention them here. This is also talking about task outputs here.

```suggestion
                "Gradle does not know how file '" + relativePath + "' was created (output property '" + overlappingOutputs.getPropertyName() + "'). Task output caching requires exclusive access to output paths to guarantee correctness (i.e. multiple tasks are not allowed to produce output in the same location)."));
```

(Yes, in theory you could be really evil and intentionally point your task to create something in `$buildDir/.transforms/...` to overlap with the output of a transform, but that is not something we want to defend against here.)

2020-09-28 20:58 UTC, mathjeff commented
Hmm, it's interesting that the fact that I pushed the button to accept your suggestions resulted in the creation of a change that says it's not correctly signed off

Maybe I should squash the two changes and keep the signed-off from the parent and the message from the child

I hope that doesn't cause Github to delete the conversation that took place on the original commit though

2020-10-02 08:02 UTC, lptr approved these changes
Looks good, thanks @mathjeff! Will merge this soon.

2020-10-02 08:02 UTC, lptr commented
@bot-gradle test this please.

2020-10-02 12:48 UTC, merged