Ensure that no partial toolchain is left behind
gradle/gradle pull request #14764
Opened 2020-10-06 13:19 UTC by bmuskalla

Fixes #14761

2020-10-06 13:20 UTC, bmuskalla commented
Ignore the first 2 commits (will be gone after rebase)

2020-10-06 13:20 UTC, bmuskalla commented
@bot-gradle test QF

2020-10-12 15:32 UTC, ljacomet requested changes
See comment

2020-10-12 15:32 UTC, ljacomet commented on subprojects/platform-jvm/src/main/java/org/gradle/jvm/toolchain/install/internal/AdoptOpenJdkDownloader.java
> +            downloadFile.renameTo(targetFile);
We should not ignore the return value here.
I also believe that using `java.nio.file.Files#move` with the right options might be a better choice.

2020-10-12 19:59 UTC, bmuskalla commented
@bot-gradle test this

2020-10-15 07:56 UTC, ljacomet approved these changes

2020-10-15 08:28 UTC, merged