Refine smoke test configurations
gradle/gradle pull request #14858
Opened 2020-10-14 05:58 UTC by blindpirate

Smoke tests seem to be slower than 90m recently, so we increase the timeout to 120m
and set the stacktrace timeout monitor to 90m.

2020-10-14 05:58 UTC, blindpirate commented
@bot-gradle test this

2020-10-14 08:20 UTC, jjohannes requested changes
I found a copy/paste error.

Apart from that this is fine. 

We should split this up in the future, ideally using the same mechanism as for the other tests. In addition, one specific improvement we could/should do is split out the Configuration Cache tests that depend on the Gradle sources itself (e.g. into a separate task). They are responsible that this (long running test task) is never from-cache. Maybe you can create a follow up issue (I didn't find one for this).

2020-10-14 08:20 UTC, jjohannes commented on buildSrc/subprojects/lifecycle/src/main/kotlin/gradlebuild.lifecycle.gradle.kts
> +val smokeTest = "soakTest"
:x:

```suggestion
val smokeTest = "smokeTest"
```

2020-10-15 02:11 UTC, blindpirate commented
@bot-gradle test this

2020-10-15 06:28 UTC, jjohannes approved these changes

2020-10-16 00:29 UTC, merged