Introduce a separate SnapshotType
gradle/gradle pull request #15033
Opened 2020-10-30 00:05 UTC by lptr

This allows us to have more types for snapshots than for fingerprints.

2020-10-30 00:05 UTC, lptr commented
@bot-gradle test QFL please.

2020-10-31 10:02 UTC, lptr commented
@bot-gradle test QFL please.

2020-10-31 10:52 UTC, lptr commented
@bot-gradle test this please.

2020-11-02 12:38 UTC, wolfs requested changes
Like you said, the PR is missing some test cases. I found at least one problem for which we need a new test case.

2020-11-02 12:38 UTC, wolfs commented on subprojects/snapshots/src/main/java/org/gradle/internal/fingerprint/overlap/impl/DefaultOverlappingOutputDetector.java
> +                    return hasNewContent(unreadableSnapshot, null);
Won't `hasNewContent` throw when trying to compare the types? Is this intended for overlapping output detection? It seems like this shouldn't throw when the type did not change, so there is probably a test case missing.

2020-11-10 10:38 UTC, lptr commented
@bot-gradle test QFL please.

2020-11-20 07:17 UTC, lptr commented
@bot-gradle test QFL please.

2021-08-23 08:42 UTC, lptr commented
Instead of tracking unreadable snapshots we'll mark properties as untracked, and not snapshot them: https://github.com/gradle/gradle/pull/18085.

2021-08-23 08:42 UTC, closed without merging