Allow task exclusion in included builds
gradle/gradle pull request #15101
Opened 2020-11-09 10:58 UTC by donat

This PR allows users to exclude tasks from the included builds.

The implementation only changes how the filters are applied to the task graph. The existing implementation defines all filters (i.e. `-x` arguments on the command line) on the root build's graph. This PR inspects the filter's path and if it points to an included build, then the filter is assigned to the target build's task graph.

2020-11-09 11:01 UTC, donat commented
@bot-gradle test this

2020-11-09 12:19 UTC, donat commented
@bot-gradle test this

2020-11-11 09:17 UTC, donat commented
@bot-gradle test this

2020-11-12 06:53 UTC, big-guy requested changes

2020-11-12 06:53 UTC, big-guy commented on subprojects/core/src/main/java/org/gradle/execution/ExcludedTaskFilteringBuildConfigurationAction.java
>              }
I think this looks a little weird for two reasons:
- We're pushing things down into each build. 
- We're creating separate filter lists for each build. 

Could we instead add a service to the Build Tree scope that represents the task filter and then have each DefaultTaskExecutionGraph use that service as the source of filters? Then here, we wouldn't care about any particular Gradle instance, we'd just populate the "task filter service". That would remove the need for `useFilter` on the task graph.

2020-11-12 18:52 UTC, donat commented
Superseded by #15141

2020-11-12 18:52 UTC, closed without merging