Remove non-dynamic constraint on plugin versions.
gradle/gradle pull request #16046
Opened 2021-02-05 12:43 UTC by staale

Fixes #14704

### Context
This is currently blocking us from adopting the new plugins notation. We have a large set of projects that utilizes a common toolchain of Gradle plugins. By using a version of '1.0.+', we are able to update all projects and their build tools in a single step by just pushing a new patch version. Each dependent project then gets these fixes on their next build.

We are currently using the buildscript configuration with classpath dependencies that do have version ranges, which does allow us to set version ranges, and solves this for us. However, we would like to update to the more modern plugins notation.

I also believe this will benefit others, and does not adversely affect the current state of the code. Its just a check that is removed, without any logic changes. So this constraint doesn't really provide any value.

### Contributor Checklist
- [X] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [X] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [X] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [X] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [X] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

2021-02-05 13:29 UTC, jjohannes commented
@bot-gradle test QFL

2021-02-05 16:58 UTC, jjohannes commented
Thanks @staale for pushing this. It's indeed a simple fix so we should move forward asap. I tentatively added the 7.0 milestone for consideration.

I pushed it through our TeamCity CI (ignore Travis, seems to be broken at the moment).

There are two test cases failing, which need to be adjusted (they pass now, which is ok): https://ge.gradle.org/s/iiblm52lkkpk4/tests/failed 

Would you mind adjusting them?

2021-02-08 11:24 UTC, staale commented
> There are two test cases failing, which need to be adjusted (they pass now, which is ok): https://ge.gradle.org/s/iiblm52lkkpk4/tests/failed
> 
> Would you mind adjusting them?

Fixed both tests, and added 2 more for the positive case, when we try to use a version range, and verifying that this works.

Is this possible for a 6.9.? Or is 7.0 imminent enough that we can wait for this? Adding this in will help us update to the latest Gradle version, as well as allow us to transition to plugins declarations.

2021-02-09 13:45 UTC, eskatos requested changes
Looking good. I requested two little changes for a typo.

2021-02-09 13:45 UTC, eskatos commented on subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/repository/ResolvingWithPluginManagementSpec.groovy
> +    def 'when version range is specified, resolution sucseeds'() {
:x: Little typo
```suggestion
    def 'when version range is specified, resolution succeeds'() {
```

2021-02-09 13:45 UTC, eskatos commented on subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/repository/ResolvingWithPluginManagementSpec.groovy
> +    def 'when artifact version range is specified, resolution sucseeds'() {
:x: Little typo
```suggestion
    def 'when artifact version range is specified, resolution succeeds'() {
```

2021-02-09 13:46 UTC, eskatos commented
@bot-gradle test this

2021-02-10 14:13 UTC, eskatos commented
@Mergifyio update

2021-02-10 15:07 UTC, eskatos commented
@bot-gradle test this

2021-02-15 11:17 UTC, staale commented on subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/repository/ResolvingWithPluginManagementSpec.groovy
> +    def 'when version range is specified, resolution sucseeds'() {
Fixed

2021-02-15 11:17 UTC, staale commented on subprojects/plugin-use/src/integTest/groovy/org/gradle/plugin/repository/ResolvingWithPluginManagementSpec.groovy
> +    def 'when artifact version range is specified, resolution sucseeds'() {
Fixed

2021-02-16 07:47 UTC, jjohannes commented
@bot-gradle test this

2021-02-16 08:46 UTC, jjohannes approved these changes

2021-02-16 13:55 UTC, merged