Enable -Xjvm-default=all for the Kotlin DSL
gradle/gradle pull request #16040
Opened 2021-02-05 10:04 UTC by eskatos

See https://blog.jetbrains.com/kotlin/2020/07/kotlin-1-4-m3-generating-default-methods-in-interfaces/

Issue https://github.com/gradle/gradle/issues/14875

2021-02-05 10:06 UTC, eskatos commented
@bot-gradle test RFN

2021-02-05 13:17 UTC, bamboo approved these changes

2021-02-05 13:17 UTC, bamboo requested changes
We should include at least one integration test. Other than that, it looks good to me!

2021-02-05 15:17 UTC, eskatos commented
@bot-gradle test this

2021-02-08 18:49 UTC, bamboo requested changes

2021-02-08 18:49 UTC, bamboo commented on subprojects/kotlin-dsl-integ-tests/src/integTest/kotlin/org/gradle/kotlin/dsl/integration/KotlinDslJvmDefaultIntegrationTest.kt
> +    fun `kotlin-dsl java and groovy consumers can use kotlin interface default methods directly`() {
❌ Nice! We should also have a test for a Kotlin DSL script consumer implementing a Java interface with default methods.

2021-02-09 08:38 UTC, eskatos commented
@bot-gradle test this

2021-02-09 12:54 UTC, bamboo approved these changes

2021-02-09 13:14 UTC, eskatos commented
@bot-gradle test this

2021-02-09 17:55 UTC, bamboo approved these changes

2021-02-10 09:46 UTC, eskatos commented
@bot-gradle test this

2021-02-10 20:57 UTC, merged