[WIP] Support camelCase shourtcuts for configuration selection in dependecies/dependencyInsinght task
gradle/gradle pull request #16142
Opened 2021-02-13 00:12 UTC by grossws

Fixes #16141

I'll add relevant docs for this feature if required.

Do I need to add some integration tests for such trivial change? I've added couple of tests into `DependencyReportTaskTest` which check relevant behavior change.

Also `sanityCheck` against master fails 'cause dependency verification failures in independent modules. So I checked relevant todo item below.

### Context
See #16141 and https://gradle-community.slack.com/archives/CA7UM03V3/p1611706682059700

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

2021-02-19 00:48 UTC, grossws commented
Rebased on master and squashed commits into one

2021-06-03 12:03 UTC, donat commented
@grossws Sorry for the late reply. Your PR makes sense. I'll give it a more thorough review.

2021-06-03 12:16 UTC, donat requested changes
Thanks for the quality pull request. I have just a couple of minor requests, otherwise, it's good for merging.

2021-06-03 12:16 UTC, donat commented on subprojects/diagnostics/src/test/groovy/org/gradle/api/tasks/diagnostics/DependencyReportTaskTest.groovy
> +    def "configuration to render could be specified by camelCase shortcut"() {
❌ Please add a similar coverage to the `dependencyInsight` task. Maybe add it to the `DependencyInsightReportTaskIntegrationTest` class.

2021-06-03 12:16 UTC, donat commented on subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/viewing_debugging_dependencies.adoc
> +TIP: You can use _camelCase_ shortcut to select configuration like `tRC` instead of `testRuntimeClasspath` if that shortcut points to unique configuration.
Please mention this change in the `subprojects/docs/src/docs/release/notes.md`.

2021-06-03 12:19 UTC, donat commented
Running the changes through CI: https://builds.gradle.org/viewQueued.html?itemId=43971909

2021-06-03 12:23 UTC, donat commented on subprojects/diagnostics/src/main/java/org/gradle/api/tasks/diagnostics/internal/ConfigurationFinder.java
> +import org.gradle.util.NameMatcher;
❌ Please use `org.gradle.util.internal.NameMatcher`.

2021-06-03 12:49 UTC, grossws commented
@donat, thanks for review. I'll update PR when have a bit of time.

2021-06-03 15:19 UTC, donat commented
Sounds good. Looking forward to the update.

2021-06-09 18:47 UTC, grossws commented
@donat, I updated PR but I'm not quite sure what format should be used in `notes.md` for feature description.

2021-06-10 06:18 UTC, donat commented
@grossws It's fine, I've adjusted the text there.

2021-06-10 06:18 UTC, donat commented
@bot-gradle test and merge

2021-06-10 07:49 UTC, merged

2021-06-10 13:46 UTC, grossws commented
Thanks, @donat

2021-06-10 21:16 UTC, lacasseio commented
This PR breaks configurations that are created via Rules. There should be a final `getByName` if the finder here fails (https://github.com/gradle/gradle/commit/c190a1ba9997db532884c0f0a443dc4b29c638d2#diff-9c98c9ba8979d3a753ca3ebdc39a2c5d84bef93c3889132cc0ff67bf8702eedaR30). For example, in Nokee we use [this code](https://github.com/nokeedev/gradle-native/blob/ef45487ffe820073c082da016c79bec3bad74e41/subprojects/platform-jni/src/main/java/dev/nokee/platform/jni/internal/plugins/JniLibraryPlugin.java#L319-L321) to execute additional code that may create configurations. The [previous `getByName` here](https://github.com/gradle/gradle/commit/c190a1ba9997db532884c0f0a443dc4b29c638d2#diff-3abfca496347f99852cc4d194aa44ced6f255ab250be6813eabd667471f61d68L153) would trigger any container rules.

2021-06-11 10:54 UTC, donat commented
@grossws https://github.com/gradle/gradle/pull/16142#issuecomment-859076187 is valid. I'm about to revert your PR: https://github.com/gradle/gradle/pull/17428.
Could you please submit another PR that takes the rules into account? 

An integtest is pretty simple for this case: `gradle dependencies --configuration foo` should pass for the following build script:

```groovy
project.afterEvaluate { p ->
    p.configurations.addRule('my custom config defined via a rule', { s -> 
        if (s == 'foo') {
            p.configurations.create('foo')
       }
	)
}
```

2021-06-11 20:25 UTC, grossws commented
@donat, ok, I'll fix that and add tests. Should I create PR against current master or this PR branch?

@lacasseio, thanks for your feedback and catching a bug)

2021-06-12 03:41 UTC, lacasseio commented
I feel bad for forcing a revert as the feature is pretty cool. I hope you can submit a change quickly. :-)

2021-06-21 14:14 UTC, grossws commented
@lacasseio, already done in #17445 ,)