Improve documentation on custom and lazy types
gradle/gradle pull request #16300
Opened 2021-02-24 20:18 UTC by jjohannes

Update snippets and some misleading/wrong sections in 'custom_gradle_types' and 'lazy_configuration'.

Goal of this is:
- Make snippets concise and idiomatic
- Stronger align Groovy and Kotlin DSL snippets to avoid confusion
- Update sections in 'custom_gradle_types' that now give the wrong impression: managed types should always be preferred and they are not incubating anymore.

The goal of this is not a larger scale rework this part of the documentation, which should certainly be done as well to explain this topic better.

2021-02-24 20:19 UTC, jjohannes commented
@bot-gradle test QF

2021-02-25 09:31 UTC, ljacomet requested changes

2021-02-25 09:31 UTC, ljacomet commented on subprojects/docs/src/docs/userguide/extending-gradle/custom_gradle_types.adoc
> +Sometimes you may see properties implemented in the Java bean property stile.
stile -> style

2021-02-25 09:31 UTC, ljacomet commented on subprojects/docs/src/docs/userguide/extending-gradle/custom_gradle_types.adoc
> +Properties in Gradle's core plugins that are still of this style will be migrated to managed properties in the future versions.
in the future versions -> in future versions

2021-02-25 09:31 UTC, ljacomet commented on subprojects/docs/src/docs/userguide/extending-gradle/custom_gradle_types.adoc
> +[[object_factory]]
I would advise against changing the link id as it will potentially break existing links.

2021-02-25 10:00 UTC, jjohannes commented
Thanks @ljacomet. I addressed your comments.

2021-02-25 10:01 UTC, jjohannes commented
@bot-gradle test BD

2021-02-25 10:02 UTC, jjohannes commented
@bot-gradle test QF

2021-02-25 15:32 UTC, jjohannes commented
@bot-gradle test this

2021-02-25 16:54 UTC, merged