Polish project accessors
gradle/gradle pull request #16551
Opened 2021-03-16 15:11 UTC by melix

Supercedes https://github.com/gradle/gradle/pull/16538 after rebase

2021-03-16 15:11 UTC, melix commented
@bot-gradle test RFM

2021-03-16 16:40 UTC, ljacomet requested changes
Looks good overall!
Nice to have broader support for project names.

Fix request in the docs:

2021-03-16 16:40 UTC, ljacomet commented on subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/typesafe/AbstractTypeSafeProjectAccessorsIntegrationTest.groovy
> +        FeaturePreviewsFixture.enableTypeSafeProjectAccessors(settingsFile)
Dang forgot to use that fixture in other tests I fixed ...

2021-03-16 16:40 UTC, ljacomet commented on subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/declaring_dependencies.adoc
> +```
You are missing the closing part of that block

2021-03-16 17:45 UTC, melix commented
@bot-gradle test and merge

2021-03-16 21:15 UTC, melix commented
@bot-gradle test and merge

2021-03-17 06:36 UTC, blindpirate commented
@bot-gradle test and merge

2021-03-17 06:46 UTC, blindpirate commented
@bot-gradle test and merge

2021-03-17 07:25 UTC, blindpirate commented
I'm taking care of this. Please don't trigger new builds.

2021-03-17 07:33 UTC, melix commented
> I'm taking care of this. Please don't trigger new builds.

Thanks @blindpirate !

2021-03-17 08:24 UTC, blindpirate commented
@bot-gradle test and merge

2021-03-17 08:49 UTC, blindpirate commented
@bot-gradle test and merge

2021-03-17 13:45 UTC, merged