Make `PublishToMavenLocal` task compatible with configuration cache
gradle/gradle pull request #16945
Opened 2021-04-22 16:15 UTC by ALikhachev

Relates to #13468

### Context
We use `PublishToMavenLocal` task to publish Kotlin Gradle plugin to `mavenLocal` to use it then in [the integrations tests](https://github.com/JetBrains/kotlin/tree/master/libraries/tools/kotlin-gradle-plugin-integration-tests). The issue blocks us from using configuration cache. However, the issue can be workarounded by replacing task in [such way](https://github.com/JetBrains/kotlin/commit/c33cdac3540e73aa1876f5c08e045488d49b1ae5).

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

2021-04-22 16:25 UTC, ALikhachev commented
I've tried to add `mavenLocal` to publishing repository list and then replace `publishToMavenLocal` with `publishAllPublicationsToMavenLocalRepository` and it works, but It adds timestamps to snapshot artifact names.

2021-04-27 07:47 UTC, eskatos commented
@bot-gradle test QFL

2021-04-27 10:11 UTC, eskatos commented
@bot-gradle test ACC

2021-04-27 11:50 UTC, eskatos requested changes
Thanks for the PR @ALikhachev!

The test suite reveals that your changes fix the related test with the configuration cache enabled.
https://ge.gradle.org/s/mh5xgwxc6kykm/tests/:maven:configCacheIntegTest/org.gradle.api.publish.maven.MavenPublishSnapshotIntegTest/can%20install%20snapshot%20versions?anchor=e30&focused-exception-line=0-0&top-execution=1

Could you please remove this test annotation?
https://github.com/gradle/gradle/blob/5c69873798b90e134255a6355e17d37396bf1851/subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishSnapshotIntegTest.groovy#L115-L116

2021-04-27 14:58 UTC, eskatos commented
@bot-gradle test ACC

2021-04-27 15:44 UTC, eskatos approved these changes

2021-04-28 09:09 UTC, eskatos commented
@bot-gradle test and merge

2021-04-28 10:38 UTC, merged