Improving `isVersionMavenIncompatible` check
gradle/gradle pull request #16965
Opened 2021-04-25 08:03 UTC by elect86

2021-04-25 15:49 UTC, stephengold commented
Looks good to me!

2021-04-27 06:05 UTC, stephengold commented
This PR needs a milestone. Who assigns milestones?

2021-06-07 15:13 UTC, donat requested changes

2021-06-07 15:13 UTC, donat commented on subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publication/DefaultMavenPublication.java
> +        if (version.startsWith("latest.")) {
❌ Missing integration test coverage.

2021-06-07 16:16 UTC, stephengold commented
The issue this PR was intended to address (#16555) was recently closed by PR #17267. Perhaps this PR is no longer needed.

2021-06-07 16:17 UTC, elect86 commented
It's not, indeed

2021-06-07 16:17 UTC, closed without merging