Remove deprecated JavaExec.(get|set)Main
gradle/gradle pull request #17079
Opened 2021-05-05 12:34 UTC by rieske

https://github.com/gradle/gradle/issues/15681

2022-08-04 19:29 UTC, tresat commented
@bot-gradle test QFL

2022-08-04 20:11 UTC, tresat commented
@bot-gradle test QFL

2022-08-04 20:25 UTC, tresat commented
@bot-gradle test QFL

2022-08-04 20:46 UTC, tresat commented
@bot-gradle test this

2022-08-05 20:48 UTC, tresat commented
@bot-gradle test this

2022-08-05 20:52 UTC, tresat commented
Link to potential fix for asciidoctor (plugin version will need to be updated in this branch) - https://github.com/asciidoctor/asciidoctor-gradle-plugin/pull/642

2022-08-08 11:47 UTC, tresat commented
@bot-gradle test this

2022-08-18 14:14 UTC, tresat commented
@bot-gradle test this

2022-08-18 16:22 UTC, tresat commented
@bot-gradle test this

2022-08-18 19:34 UTC, jvandort approved these changes

2022-08-18 22:09 UTC, big-guy requested changes

2022-08-18 22:09 UTC, big-guy commented on subprojects/core-api/src/main/java/org/gradle/process/JavaExecSpec.java
>       */
The docs here still say "Gradle 8.0"

2022-08-19 14:57 UTC, big-guy approved these changes

2022-08-19 15:44 UTC, tresat commented
@bot-gradle test and merge

2022-08-19 16:54 UTC, merged