Move tracking of work unit execution time to work engine
gradle/gradle pull request #17116
Opened 2021-05-07 05:12 UTC by ldaley

Resolves #9117 by using this more precise time as the recorded “origin execution time”.

2021-05-07 05:12 UTC, ldaley commented
@bot-gradle test rfm

2021-05-07 05:12 UTC, ldaley commented
@lptr @wolfs I'm at a bit of a loss for how to test this well. All advice appreciated.

2021-05-07 05:29 UTC, ldaley commented
This PR currently shows my first attempt, then a revert of that, then a second simpler attempt.

2021-05-07 12:31 UTC, lptr commented
Why include output snapshotting time?

2021-05-10 06:54 UTC, lptr commented
I see, thanks. What I meant there was that we should calculate "execution time" used for the savings calculations by adding up the actual execution time and output snapshotting time. We should still measure them separately. I would do the adding up as late as possible, i.e. on the server side.

If this is complicated or not possible to do so with the current build scan model, I think it's okay to add them up in Gradle or in the build scan plugin for now, given that the current build operations only work for tasks anyway. It would be good to plot a course to where we can capture these measurements separately later on.

2021-05-11 23:17 UTC, ldaley commented
> I see, thanks. What I meant there was that we should calculate "execution time" used for the savings calculations by adding up the actual execution time and output snapshotting time. We should still measure them separately. I would do the adding up as late as possible, i.e. on the server side.

Doing it on the server side adds significant complexity and reduce reliability, as currently we obtain this information from the artifact metadata, not the referenced scan. So, ultimately we need to record the number that we want at the build site. 

I'll rework this to combine discrete measuring of execution time and output snapshotting time as mentioned in my previous comment.

2021-05-14 00:55 UTC, ldaley commented
@bot-gradle test rfm

2021-05-14 03:58 UTC, ldaley commented
@lptr ready for another look

2021-05-14 03:59 UTC, ldaley commented
@bot-gradle test rfm

2021-06-01 10:49 UTC, lptr requested changes
This looks good in general. I have one issue with the changes, and it's the introduction of `ExecuteWorkResult`. We already have quite a few confusing names around capturing the result of executed work that I'd love to clear up eventually:

- `ExecutionResult`
- `WorkResult`
- `Result`

This new name is a combination of the above without clarifying what its purpose is, increasing the confusion.

I see two ways to resolve this for the scope of the current PR:

1) just merge `Result` and `ExecuteWorkResult`: the latter replaced the former in most places anyway, and having the duration in a separate interface doesn't add anything,
2) rename `ExecuteWorkResult` to something like `TimedResult`.

I think we should go with 1).

2021-06-04 05:10 UTC, ldaley commented
@bot-gradle test RFM

2021-06-04 05:10 UTC, ldaley commented
@lptr those types have been merged.

2021-06-04 05:32 UTC, ldaley commented
@bot-gradle test RFM

2021-06-06 23:43 UTC, ldaley commented
@bot-gradle test RFM

2021-06-07 02:15 UTC, ldaley commented
@bot-gradle test RFM

2021-06-07 03:36 UTC, ldaley commented
@bot-gradle test RFM

2021-06-07 09:07 UTC, lptr commented
> The situation with getDuration() being meaningless for some types seems awkward, but I didn't have any other ideas that wouldn't have resulted in major surgery.

One option to handle this better would be to return an `Optional<Duration>` instead, and use `Optional.empty()` for when the duration is meaningless. However, I don't think doing this is actually necessary.

I'd instead define `getDuration()` as the execution time of the work, no matter where or when it happened. That way it is pretty straightforward to implement it for all `Result` types. It also gives us a good place to document why the duration might be misleading.

Take a look at the changes here: https://gist.github.com/lptr/d75ac40b91a83db6736731a15a88c005

If we go in that direction, I'd probably also change `OriginMetadata.getExecutionTime()` to return `Duration` directly.

2021-06-08 00:03 UTC, ldaley commented
@bot-gradle test RFM

2021-06-08 00:03 UTC, ldaley commented
@lptr patch applied.

2021-06-08 06:52 UTC, britter approved these changes
From what I can see this will not impact the Maven build cache implementation.

2021-06-08 08:25 UTC, ldaley commented
@bot-gradle test RFM

2021-06-08 12:40 UTC, lptr approved these changes
LGTM once the tests are fixed.

2021-06-08 12:40 UTC, lptr commented on subprojects/core/src/main/java/org/gradle/caching/internal/controller/impl/DefaultBuildCacheCommandFactory.java
> +            final BuildCacheEntryPacker.PackResult packResult = packer.pack(entity, snapshots, output, originMetadataFactory.createWriter(entity,  executionTime));
Nit: extra space.

2021-06-09 00:29 UTC, ldaley commented
@bot-gradle test RFM

2021-06-09 03:02 UTC, ldaley commented
@bot-gradle help

2021-06-09 03:03 UTC, ldaley commented
@bot-gradle test and merge

2021-06-09 08:42 UTC, blindpirate commented
I saw it. looking.

2021-06-09 08:44 UTC, blindpirate commented
@bot-gradle test and merge

2021-06-09 10:39 UTC, merged

2021-06-10 03:52 UTC, ldaley commented
Thanks @blindpirate