Define scala source set with extension
gradle/gradle pull request #17163
Opened 2021-05-11 09:13 UTC by donat

This is a follow-up PR to #17149. Here, clean up the usages of conventions in the `scala` plugin. The conventions are unmodified as they will be deprecated in a separate step.

2021-05-11 09:14 UTC, donat commented
@bot-gradle test quickFeedbackLinux

2021-05-11 11:52 UTC, donat commented
@bot-gradle test quickFeedbackLinux

2021-05-12 09:30 UTC, donat commented
@bot-gradle test rFM

2021-05-12 11:36 UTC, donat commented
@bot-gradle test rFM

2021-05-12 23:45 UTC, big-guy requested changes
see what I said in the Groovy PR

2021-05-18 09:13 UTC, donat commented
@bot-gradle test rFM

2021-05-18 09:25 UTC, donat commented
@bot-gradle test rFM

2021-05-18 09:34 UTC, donat commented
@bot-gradle test rFM

2021-05-18 11:51 UTC, merged