Allow precompiled Kotlin settings plugins to have plugins block
gradle/gradle pull request #17240
Opened 2021-05-20 09:54 UTC by rieske

https://github.com/gradle/gradle/issues/15416

2021-05-20 13:22 UTC, big-guy requested changes

2021-05-20 13:22 UTC, big-guy commented on subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/precompile/v1/PrecompiledScriptTemplates.kt
> +     * Configures the plugin dependencies for this project.
```suggestion
     * Configures the plugin dependencies for this settings script.
```

2021-05-20 13:59 UTC, jjohannes approved these changes
Man, if we would have know that it is that simple. :) 

Thanks for tackling this before 7.1
Looks good :+1:

2021-05-20 15:14 UTC, rieske commented
@bot-gradle test and merge

2021-05-20 18:52 UTC, rieske commented
@bot-gradle test and merge

2021-05-20 23:08 UTC, big-guy commented
@bot-gradle test and merge

2021-05-21 03:45 UTC, rieske commented
@bot-gradle test and merge

2021-05-21 05:56 UTC, blindpirate commented
I have fixed the verification problem on `master`.

@bot-gradle test and merge

2021-05-21 06:31 UTC, merged