Allow overriding of the wrapper network timeout
gradle/gradle pull request #17830
Opened 2021-07-24 18:19 UTC by goughy000

Fixes #17575 

### Context
As discussed in the issue, experience in our own organisation shows that the default timeout of 10 seconds can result in build failures when the download source of the wrapper is responding slowly.  Rather than hardcode an arbitrary higher timeout, this PR allows users to set their own.

Based on the feedback in the issue triage, I have introduced a single `networkTimeout` property to gradle-wrapper.properties which is used for both Connection and Read timeouts.  This can also be set at wrapper init time like the other properties

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

2021-09-22 19:04 UTC, goughy000 commented
@ljacomet any update on this..?

2021-09-23 13:13 UTC, ljacomet commented
@goughy000 Sorry, this slipped through and did not get attention. Let me correct that.

2021-09-23 13:28 UTC, ljacomet commented
@bot-gradle test this

2021-09-23 13:49 UTC, ljacomet commented
@goughy000 Any chance you can rebase this PR to a recent commit?
Some CI infra setup changed and this means running the build will fail with environment related failures.

2021-09-23 19:33 UTC, goughy000 commented
@ljacomet no problem, I will try find some time this weekend

2021-09-24 04:10 UTC, big-guy requested changes
Thanks, this was actually really well done.

2021-09-24 04:10 UTC, big-guy commented on subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java
> +    }
We don't want to introduce more non-Provider API properties on tasks, so this needs to be a `Property<Integer>`. I think our `@Option` knows how to convert String -> Integer, but if it doesn't we can add that.

```suggestion
    @Internal
    @Incubating
    @Option(option = "network-timeout", description = "Timeout in ms to use when the wrapper is performing network operations")
    public Property<Integer> getNetworkTimeout() {
        return networkTimeout;
    }
```

`networkTimeout` would need to be initialized with:

```
private final Property<Integer> networkTimeout = getProject().getObjects().property(Integer.class);
```

In addition, in `WrapperPlugin`, we should set the conventional value for this near here: https://github.com/gradle/gradle/blob/2d0225d7406122d7e345f90607438e2ddd85cc07/subprojects/build-init/src/main/java/org/gradle/buildinit/plugins/WrapperPlugin.java#L34

```
wrapper.getNetworkTimeout().convention(10000);
```

2021-09-24 06:50 UTC, ljacomet commented
As Sterling commented, this PR is of good quality. Please take a look at his requests and assuming CI is happy with the result, this could be merged pretty soon.

2021-11-23 08:25 UTC, ljacomet commented
@goughy000 Any chance you could pick this up to push it through the finish line?

2022-01-22 14:41 UTC, closed without merging