Document defaults for gradle properties in Build Enviroment page in the user guide
gradle/gradle pull request #18102
Opened 2021-08-23 18:50 UTC by tresat

Addresses https://github.com/gradle/gradle/issues/15203 by adding defaults directly to properties page.

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

2021-08-23 18:53 UTC, tresat commented
@bot-gradle test this

2021-08-23 20:53 UTC, big-guy requested changes

2021-08-23 20:53 UTC, big-guy commented on subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
> +_Default is false._
```suggestion
_Default is `false`._
```

2021-08-23 20:53 UTC, big-guy commented on subprojects/docs/src/docs/userguide/running-builds/performance.adoc
> +Some collections have dedicated types, `TaskContainer` being one of them, that have useful extra methods like the link:{groovyDslPath}/org.gradle.api.tasks.TaskContainer.html#https://docs.gradle.org/
I think you might mean this? I didn't try it:
```suggestion
Some collections have dedicated types, `TaskContainer` being one of them, that have useful extra methods like the link:{groovyDslPath}/org.gradle.api.tasks.TaskContainer.html#org.gradle.api.tasks.TaskContainer:create(java.lang.String,%20java.lang.Class)[create] method that takes a task type.
```

2021-08-23 22:39 UTC, tresat commented
@bot-gradle test this

2021-08-24 19:19 UTC, big-guy commented on subprojects/docs/src/docs/userguide/running-builds/performance.adoc
> +Some collections have dedicated types, `TaskContainer` being one of them, that have useful extra methods like the link:{groovyDslPath}/org.gradle.api.tasks.TaskContainer.html#org.gradle.api.tasks.Tas
```suggestion
Some collections have dedicated types, `TaskContainer` being one of them, that have useful extra methods like the link:{groovyDslPath}/org.gradle.api.tasks.TaskContainer.html#org.gradle.api.tasks.TaskContainer:create(java.lang.String,%20java.lang.Class)[create] method that takes a task type.
```

2021-08-24 19:19 UTC, big-guy commented
@bot-gradle test and merge

2021-08-24 19:20 UTC, big-guy approved these changes

2021-08-24 20:07 UTC, merged