Automatically normalize aliases for find* methods in VersionCatalog API
gradle/gradle pull request #18207
Opened 2021-09-06 09:04 UTC by asodja

Fixes #18050

I figured to make it more user friendly, we can just automatically normalize aliases.

2021-09-06 09:18 UTC, asodja commented
@gradle-bot help

2021-09-06 09:19 UTC, asodja commented
@bot-gradle test QFL

2021-09-06 09:25 UTC, asodja commented
@bot-gradle help

2021-09-06 09:25 UTC, asodja commented
@bot-gradle test this

2021-09-06 10:14 UTC, ljacomet requested changes
The changes in here are 👍 for solving the non typed API issue. Though I would like to have the issue reference in the commit message itself.

However we should still clarify documentation around how declaring an alias like `my-plug` results in `libs.my.plug`.

In particular, the note in [that section](https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog-declaration) should become a section and be referenced from relevant places in the document.

Makes sense?

2021-09-06 11:13 UTC, asodja commented
Makes sense, will check it.

2021-09-07 07:32 UTC, asodja commented
New version for proof read:
[platforms.html.zip](https://github.com/gradle/gradle/files/7119769/platforms.html.zip)

2021-09-07 07:37 UTC, asodja commented
New version for proof read:
[platforms.html.zip](https://github.com/gradle/gradle/files/7119801/platforms.html.zip)

2021-09-07 09:45 UTC, ljacomet reviewed
A couple suggestions on the added documentation:

2021-09-07 09:45 UTC, ljacomet commented on subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/platforms.adoc
> +Where prefix `libs` comes from version catalog name.
💄 : Where the `libs` prefix comes from the version catalog name.

2021-09-07 09:45 UTC, ljacomet commented on subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/platforms.adoc
> +For example, given the following aliases in version catalog named `libs`:
💄 : ... in a version catalog ...

2021-09-07 09:45 UTC, ljacomet commented on subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/platforms.adoc
> +For aliases same rules apply as described in <<platforms.adoc#sub:mapping-aliases-to-accessors, aliases and their mapping to type safe accessors>> section.
💄 : For aliases, the rules described in the section <<platforms.adoc#sub:mapping-aliases-to-accessors, aliases and their mapping to type safe accessors>> apply as well.

2021-09-07 09:45 UTC, ljacomet commented on subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/platforms.adoc
> +You can also access version catalog programmatically with version catalog extension and version catalog API:
💄 : ... with the version catalog extension and API:

2021-09-07 09:45 UTC, ljacomet commented on subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/platforms.adoc
> +Check link:{javadocPath}/org/gradle/api/artifacts/VersionCatalog.html[version catalog API] for all supported methods.
💄 : Check the ...

2021-09-13 16:50 UTC, ljacomet approved these changes

2021-09-20 11:24 UTC, asodja commented
@bot-gradle test QFL

2021-09-20 12:31 UTC, ljacomet approved these changes

2021-09-20 13:52 UTC, asodja commented
@bot-gradle test and merge

2021-09-20 14:36 UTC, asodja commented
@bot-gradle test this

2021-09-20 15:33 UTC, asodja commented
@bot-gradle test and merge

2021-09-20 18:45 UTC, merged