Fix functional tests generated by build-init to be rerunnable
gradle/gradle pull request #18222
Opened 2021-09-07 20:10 UTC by tresat

Ensure that when gradle plugin projects are setup via the build-init plugin, the generated functional tests are rerunnable using "gradle check --rerun-tasks".

Previously, the way build scripts were applied in the Spock and JUnit templates would result in duplicate plugin application blocks which would fail to run.

Fixes https://github.com/gradle/gradle/issues/18206.

### Context
This will reduce a potential point of confusion for new plugin authors.

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

2021-09-07 20:11 UTC, tresat commented
@bot-gradle test this

2021-09-07 23:07 UTC, big-guy requested changes
The tests are OK here, but we should also update PluginFunctionalTest.kt.template to follow the same kind of pattern.

The reason that the Kotlin test was working, but the Groovy/Java ones were not is the Kotlin test overwrites the file every time vs appending to it.

2021-09-08 14:21 UTC, tresat commented on subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/plugin/groovy/spock/PluginFunctionalTest.groovy.template
> +        def settingsFile = new File(projectDir, "settings.gradle")
Definitely an improved test setup, I was just looking to make a quick fix.

Looks like we're using JUnit/Spock/kotlintest for each flavor of functional test template, but I'll use the appropriate temp directory process for each.

2021-09-08 14:25 UTC, tresat commented
@bot-gradle test QF

2021-09-09 05:53 UTC, big-guy requested changes
Very close to being done here.  Thanks!

2021-09-09 05:53 UTC, big-guy commented on subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/plugin/groovy/spock/PluginFunctionalTest.groovy.template
> +import spock.lang.TempDir
Ah, good spot on this.

2021-09-09 05:53 UTC, big-guy commented on subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/plugin/groovy/spock/PluginFunctionalTest.groovy.template
> +        getBuildFile() << """
Just so this looks a little Groovier:
```suggestion
        settingsFile << ""
        buildFile << """
```

2021-09-09 05:53 UTC, big-guy commented on subprojects/build-init/src/main/resources/org/gradle/buildinit/tasks/templates/plugin/kotlin/kotlintest/PluginFunctionalTest.kt.template
> +
Ah, I was wrong that we were using JUnit Platform for Kotlin too :/

Could we use JUnit4's `TemporaryFolder` here? Something like:
```suggestion
    @get:Rule val tempFolder = TemporaryFolder()

    private fun getProjectDir() = tempFolder.root
    private fun getBuildFile() = getProjectDir().resolve("build.gradle")
    private fun getSettingsFile() = getProjectDir().resolve("settings.gradle")
```

2021-09-09 14:25 UTC, tresat commented
@bot-gradle test QF

2021-09-10 12:12 UTC, big-guy approved these changes

2021-09-10 12:12 UTC, big-guy commented
@bot-gradle test and merge

2021-09-13 01:37 UTC, blindpirate commented
@bot-gradle test and merge

2021-09-13 03:46 UTC, blindpirate commented
@bot-gradle test and merge

2021-09-13 16:51 UTC, ljacomet approved these changes

2021-09-13 18:46 UTC, tresat commented
@bot-gradle test and merge

2021-09-13 19:36 UTC, merged