Use the file resolver in LazyPublishArtifact
gradle/gradle pull request #18715
Opened 2021-10-20 19:10 UTC by octylFractal

This gives us many of these conversions for free, reducing duplicated code. This also fixes #15711.

The bulk of the change is `LazyPublishArtifact.java`, everything else is dependency injection or test fixing.

2021-10-22 02:20 UTC, big-guy commented
@bot-gradle help

2021-10-22 02:21 UTC, big-guy commented
@bot-gradle test AllSmokeTestsReadyForMerge

2021-11-10 21:31 UTC, big-guy requested changes

2021-11-10 21:31 UTC, big-guy commented on subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/JvmPluginsHelper.java
> +            .undocumented()
same here

2021-11-11 04:42 UTC, octylFractal commented
@bot-gradle test AllSmokeTestsReadyForMerge

2021-11-11 16:35 UTC, octylFractal commented
@bot-gradle test AllSmokeTestsReadyForMerge

2021-11-11 22:33 UTC, big-guy approved these changes

2021-11-11 22:41 UTC, octylFractal commented
@bot-gradle test and merge

2021-11-15 20:54 UTC, octylFractal commented
@bot-gradle test and merge

2021-12-07 23:57 UTC, big-guy commented
@bot-gradle test and merge

2021-12-08 00:00 UTC, big-guy commented
@bot-gradle cancel

2021-12-15 23:34 UTC, octylFractal commented
@bot-gradle help

2021-12-15 23:35 UTC, octylFractal commented
@bot-gradle test

2021-12-15 23:36 UTC, octylFractal commented
@bot-gradle test this

2021-12-16 00:14 UTC, octylFractal commented
@bot-gradle test this

2021-12-16 01:42 UTC, octylFractal commented
@bot-gradle test and merge

2021-12-16 19:19 UTC, octylFractal commented
@bot-gradle test and merge

2021-12-16 20:46 UTC, merged