Provide option to hide welcome message on gradle startup
gradle/gradle pull request #18830
Opened 2021-10-30 21:28 UTC by yasmans

Add a property **org.gradle.hideWelcomeMessage** to provide build authors and executors control over weather to show Gradle welcome message or not. As mentioned in linked issue, this can be useful in automated execution environments where this information is irrelevant and creates noise.

Fixes #12550

2022-02-24 11:22 UTC, hegyibalint requested changes
Hi @yasmans,
Thanks for the PR, it's nice work!

2022-03-04 19:45 UTC, yasmans commented on subprojects/launcher/src/main/java/org/gradle/launcher/cli/WelcomeMessageAction.java
> +    private boolean isHiddenByUser() {
Thank you very much for suggestions, somehow there was no difference in my head between system and gradle properties. I agree with suggested improvements and will update PR.

2022-03-07 08:53 UTC, hegyibalint commented
@bot-gradle test RFM

2022-03-07 12:28 UTC, yasmans commented
What does these build errors mean? Do I need to sync with main branch? @hegyibalint

2022-03-08 08:50 UTC, blindpirate commented
> What does these build errors mean? Do I need to sync with main branch? @hegyibalint

Yes, I think so.

2022-03-08 12:52 UTC, hegyibalint commented
Hi @yasmans! Sorry, got sidetracked by another issue... As @blindpirate said, please sync up the branch, and ping me so I can go on with the prep-work!

2022-03-08 16:58 UTC, yasmans commented
@hegyibalint synced.

2022-03-09 12:14 UTC, hegyibalint approved these changes

2022-03-09 12:32 UTC, donat requested changes

2022-03-09 12:32 UTC, donat commented on subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
> +_Enabled by default and welcome message is shown on first execution of each new version of Gradle._
I think we should adjust the key and the values to the other Gradle properties. How about this: 

```suggestion
`org.gradle.welcome=(never,once)::
Controls whether Gradle should print a welcome message. If set to _never_ then the welcome message will be suppressed. If set to _once_ then the message is printed once for each new version of Gradle.
_Default is `once`._
```

2022-03-09 12:49 UTC, donat commented on subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
> +_Enabled by default and welcome message is shown on first execution of each new version of Gradle._
Nonetheless, the PR looks good. Thank you @yasmans for taking the time and implementing this feature!

2022-03-21 13:58 UTC, donat commented
@bot-gradle test RFM

2022-03-21 15:21 UTC, hegyibalint requested changes

2022-03-21 15:44 UTC, donat commented
@bot-gradle test RFM

2022-03-21 15:44 UTC, donat commented on subprojects/launcher/src/main/java/org/gradle/launcher/cli/DefaultCommandLineActionFactory.java
> +            BuildOptionBackedConverter<StartParameterInternal> startParameterConverter = new BuildOptionBackedConverter<>(new StartParameterBuildOptions());
Removed.

2022-04-13 12:05 UTC, donat approved these changes
I don't think `TestFilesCleanupServiceTest` should be disabled, otherwise, the PR is good to go.

```
@Disabled
class TestFilesCleanupServiceTest {
```

2022-04-13 12:44 UTC, hegyibalint approved these changes

2022-04-13 12:46 UTC, hegyibalint commented
@yasmans I've seen that you added @pioterj to the review. We can get him involved, but I don't think he has time currently to handle PRs.

2022-04-13 13:20 UTC, hegyibalint commented
@bot-gradle test and merge

2022-04-13 13:21 UTC, hegyibalint commented
@bot-gradle test and merge

2022-04-13 13:26 UTC, hegyibalint commented
@bot-gradle test and merge

2022-04-13 14:46 UTC, merged

2022-04-14 08:06 UTC, hegyibalint commented
@yasmans thanks for the PR! 
I know we might got sidetracked a little with the option parsing, but we still glad that you took the time to work on this!

2022-11-12 04:10 UTC, sourcedelica commented on subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
> +`org.gradle.welcome=(never,once)::
There is a missing backtick after the `)` on this line.  You can see that the property is not formatted correctly on the [doc page](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties).  Also it is out of alphabetical order.  It should go after `org.gradle.warning.mode`.  `org.gradle.logging.stacktrace` is also in the wrong location - it should go after `org.gradle.logging.level`

2022-11-12 04:46 UTC, sourcedelica commented on subprojects/docs/src/docs/userguide/running-builds/build_environment.adoc
> +`org.gradle.welcome=(never,once)::
Submitted #22702 and PR#22703