Support version catalogs in `classpath`
gradle/gradle pull request #18865
Opened 2021-11-04 17:08 UTC by octylFractal

This is a little more targeted than my previous ProviderConvertible Kotlin DSL PR, basically due to some open questions revolving around the 'correct' way to expose Provider/ProviderConvertible to the API. This one was designed with a different way of doing the Kotlin DSL than we currently do, and hopefully one that ends up more powerful.

Fixes #17792

2021-11-05 08:36 UTC, eskatos requested changes
Adding static extensions to `DependencyHandler` for the `classpath` configuration in `ScriptHandlerScope` which is targeted to `buildscript {}` is the way to go 👍 

The nullable return change on the `DependencyHander` API is a good change, reflecting reality. Tough, making the return nullable might break build logic that did not expect a null return at runtime, and break the compilation of build logic that has nullability compilation assertions enabled such as Kotlin with JSR305, the Kotlin DSL . This should be postponed to 8.0.

I made some suggestions in https://github.com/gradle/gradle/pull/18870 to add the required kotlin extensions to support version catalogs in `buildscript { dependencies { classpath(..) } }` without requiring the nullability change.

2021-11-09 17:04 UTC, octylFractal commented
This PR is waiting on #18910 to be merged, I want to fix the bug related to accepting API changes rather than commit more incorrect entries as this PR would require.

2021-11-26 17:12 UTC, ljacomet approved these changes

2021-12-09 17:10 UTC, octylFractal commented
@bot-gradle test and merge

2021-12-09 18:31 UTC, merged