Document dependency verification udpate process
gradle/gradle pull request #18863
Opened 2021-11-04 13:47 UTC by ljacomet

2021-11-04 14:08 UTC, ljacomet commented
@bot-gradle test this

2021-11-04 14:42 UTC, octylFractal requested changes
Looks good overall, just a few grammar suggestions.

2021-11-04 14:42 UTC, octylFractal commented on subprojects/docs/src/docs/release/notes.md
> +This allows to leverage generation as an update strategy for the verification metadata when dependencies change in your project.
```suggestion
This allows you to leverage generation as an update strategy for the verification metadata when dependencies change in your project.
```

2021-11-04 14:42 UTC, octylFractal commented on subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_verification.adoc
> +* Entries added by hand will immediately be accounted for, and appear at their right location after writing the file,
```suggestion
* Entries added by hand will immediately be accounted for, and appear at the right location after writing the file,
```

2021-11-04 14:42 UTC, octylFractal commented on subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_verification.adoc
> +* The header comments of the file will be preserved, that is comments before the root XML node.
```suggestion
* The header comments of the file will be preserved, i.e. comments before the root XML node.
```

2021-11-05 14:23 UTC, ljacomet commented
@bot-gradle test this

2021-11-08 10:01 UTC, ljacomet commented
@bot-gradle test this

2021-11-08 12:44 UTC, tresat commented on subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_verification.adoc
> +This behaviour should make the feature much easier to use in practice.
I agree.  This: "This behaviour should make the feature much easier to use in practice." should be removed from this part of the documentaion.

2021-11-09 16:33 UTC, octylFractal approved these changes

2021-11-16 10:55 UTC, ljacomet commented
@bot-gradle test and merge

2021-11-16 11:22 UTC, pioterj requested changes

2021-11-16 11:22 UTC, pioterj commented on subprojects/docs/src/docs/release/notes.md
> +With this release, the generation of the dependency verification file has been improved to produce stable output.
Could we clarify what specifically we mean by stable output?

2021-11-16 11:22 UTC, pioterj commented on subprojects/docs/src/docs/release/notes.md
> +This allows you to leverage generation as an update strategy for the verification metadata when dependencies change in your project.
This is not entirely clear. Can we add some context on the "generation update strategy"?

2021-11-16 18:58 UTC, merged