Add method for adding lazy values to AttributeContainer using providers
gradle/gradle pull request #18936
Opened 2021-11-11 00:41 UTC by tresat

This work was extracted from the PR 18834.

### Context

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

2021-11-11 00:41 UTC, tresat commented
@bot-gradle test this

2021-11-11 12:33 UTC, tresat commented
@bot-gradle test this

2021-11-11 12:54 UTC, tresat commented
@bot-gradle test this

2021-11-11 12:56 UTC, tresat commented
@big-guy, @DPUkyle - Here is just the AttributeContainer work lifted from https://github.com/gradle/gradle/pull/18834, using the generic type arg vs. the 2-arg call, and with an upgrade note added.  Hopefully this looks good to merge soon.

2021-11-11 14:00 UTC, tresat commented
@bot-gradle test this

2021-11-11 21:27 UTC, DPUkyle requested changes
Overall looks good, with two points for follow-up:

 1. I am not a Kotlin expert. Are we 100% sure the new method overload breaks the kotlin extension function?
 2. Consider using `Map#forEach` instead of iterating over entryset

2021-11-11 21:27 UTC, DPUkyle commented on build-logic-commons/code-quality/src/main/kotlin/gradlebuild.code-quality.gradle.kts
> +        attribute(LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE, objects.named<LibraryElements>(LibraryElements.RESOURCES))
Nevermind, I see you explained it in `upgrading_version_7.adoc`. Are we really sure Kotlin can't handle both argument types? Perhaps not, if the use-case is Object vs. Provider.

--

I wonder why we started parameterizing all the `objects.named` calls. I don't have a problem with it, I'm just curious.

Is it something to do with the erasure of `AttributeContainer#attribute(Attribute<T>, T)` conflicting with `public <T> AttributeContainer attribute(Attribute<T> key, Provider<? extends T> provider)` on `DefaultImmutableAtributes`?

2021-11-11 21:27 UTC, DPUkyle commented on subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultMutableAttributeContainer.java
> +        // Don't just use keySet() method instead, since we should be allowed to override attributes alread in the parent
👍

2021-11-11 21:27 UTC, DPUkyle commented on subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultMutableAttributeContainer.java
> +        }
See https://github.com/gradle/gradle/pull/18834#discussion_r746973844

2021-11-12 00:23 UTC, DPUkyle requested changes

2021-11-12 00:23 UTC, DPUkyle commented on subprojects/core/src/main/java/org/gradle/api/internal/attributes/DefaultMutableAttributeContainer.java
> +    private final Map<Attribute<?>, Provider<?>> lazyAttributes = Maps.newHashMap();
Please use `new HashMap<>();` for the RHS. I suspect this should also remove the need to use a cast in the `forEach` use below.

From the javadoc of `Maps#newHashMap()`:
```
Note for Java 7 and later: this method is now unnecessary and should be treated as deprecated. Instead, use the HashMap constructor directly, taking advantage of the new "diamond" syntax .
```

Even without the "soft" deprecation above, I think we should not add any more usages of guava.

2021-11-12 03:23 UTC, tresat commented
@bot-gradle test this

2021-11-12 12:35 UTC, tresat commented
@big-guy, @DPUkyle - I think I've addressed everything for the AttributeContainer work here and this is ready to merge.

2021-11-12 15:26 UTC, big-guy approved these changes

2021-11-12 15:27 UTC, big-guy commented
@bot-gradle test and merge

2021-11-12 15:46 UTC, big-guy commented
@bot-gradle cancel

2021-11-12 15:46 UTC, big-guy commented
@bot-gradle test and merge

2021-11-12 19:54 UTC, big-guy commented
@bot-gradle test and merge

2021-11-12 21:47 UTC, merged