Fix StartParameter links
gradle/gradle pull request #19042
Opened 2021-11-18 17:45 UTC by octylFractal

These are in the JavaDoc, not the DSL docs.

Fixes #18963

2021-11-18 22:09 UTC, big-guy requested changes

2021-11-23 18:45 UTC, octylFractal commented on subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
> +link:{javadocPath}/org/gradle/StartParameter.html#setBuildFile(java.io.File)[setBuildFile(File)]
Odd, apparently I had some old copy where it was `()`.

2021-11-26 17:29 UTC, ljacomet approved these changes

2021-11-26 17:30 UTC, octylFractal commented
@bot-gradle test and merge

2021-11-26 19:08 UTC, merged