Add configuration for test sources and test dependencies for Eclipse
gradle/gradle pull request #19197
Opened 2021-12-02 11:00 UTC by donat

Fixes #?

### Context

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

2021-12-03 12:32 UTC, donat commented
@bot-gradle test rFN

2021-12-03 12:33 UTC, donat commented
@bot-gradle test rFM

2021-12-06 09:15 UTC, donat commented
@bot-gradle test rFM

2021-12-06 11:43 UTC, donat commented
@bot-gradle test Quick Feedback Linux

2021-12-06 11:44 UTC, donat commented
@bot-gradle test QuickFeedbackLinux

2021-12-06 13:01 UTC, donat commented
@bot-gradle test rFM

2021-12-06 17:21 UTC, tresat requested changes

2021-12-06 17:21 UTC, tresat commented on subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/internal/SourceFoldersCreator.java
> +    private List<SourceFolder> projectRelativeFolders(Iterable<SourceSet> sourceSets, Function<File, String> provideRelativePath, File defaultOutputDir, Property<String> testSourceSetNamePatternPrope
If you can pass the classpath into this method, you can find all the test SourceSets created by the test suite plugin like this:

```
final Set<SourceSet> testSuiteSourceSets = new HashMap<>()
JavaPluginExtension java = project.getExtensions().getByType(JavaPluginExtension.class);
TestingExtension testing = project.getExtensions().getByType(TestingExtension.class);
ExtensiblePolymorphicDomainObjectContainer<TestSuite> testSuites = testing.getSuites();
testSuites.forEach(suite -> {
    if (suite instanceof JvmTestSuite) {
        JvmTestSuite jvmTestSuite = (JvmTestSuite) suite;
        testSuiteSourceSets.add(jvmTestSuite.getSources());
    }
});
```

And then when iterating through all the SourceSets, also mark any directories for SourceSets in this collection as test for eclipse.

2021-12-06 17:21 UTC, tresat commented on subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/internal/SourceFoldersCreator.java
> +    private List<SourceFolder> projectRelativeFolders(Iterable<SourceSet> sourceSets, Function<File, String> provideRelativePath, File defaultOutputDir, Property<String> testSourceSetNamePatternPrope
Test `Configuration`s can be retrieved from these sourceSets, too.  Here are the 3 that test suites create for each `SourceSet`:

```
Configuration compileOnly = configurations.getByName(sourceSet.getCompileOnlyConfigurationName());
Configuration implementation = configurations.getByName(sourceSet.getImplementationConfigurationName());
Configuration runtimeOnly = configurations.getByName(sourceSet.getRuntimeOnlyConfigurationName());
```

2021-12-06 17:21 UTC, tresat commented on subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/EclipseClasspath.java
> +        this.testSourceSetNamePattern = project.getObjects().property(String.class).convention(".*[tT][eE][sS][tT].*");
I think the danger in testSuites is that the DSL might encourage people naming their suites just `integration` or `functional` and leaving off the `Test` suffix, so they would not get discovered here.

2021-12-06 17:21 UTC, tresat commented on subprojects/ide/src/main/java/org/gradle/plugins/ide/eclipse/model/EclipseClasspath.java
> +        this.testSourceSetNamePattern = project.getObjects().property(String.class).convention(".*[tT][eE][sS][tT].*");
I think probably a combination of both your change to pickup custom SourceSets which are configured outside of test suites, and reading the suites directly per my suggestion below (or something similar) will be needed to get everything which ought to be marked 'test'.

2021-12-22 10:13 UTC, donat commented
Superseded by #19310

2021-12-22 10:13 UTC, closed without merging