Use UUID in build confgiration
gradle/gradle pull request #19339
Opened 2021-12-17 08:13 UTC by blindpirate

2021-12-17 08:29 UTC, wolfs requested changes

2021-12-17 08:29 UTC, wolfs commented on .teamcity/src/main/kotlin/model/CIBuildModel.kt
> +    READY_FOR_MERGE("Pull Request Feedback", "Run vairous functional tests against distribution", "PullRequestFeedback") {
```suggestion
    READY_FOR_MERGE("Pull Request Feedback", "Run various functional tests", "PullRequestFeedback") {
```

typo + removed redundant information.

2021-12-17 08:29 UTC, wolfs commented on .teamcity/src/main/kotlin/model/CIBuildModel.kt
> +    READY_FOR_MERGE("Pull Request Feedback", "Run vairous functional tests against distribution", "PullRequestFeedback") {
```suggestion
    PULL_REQUEST_FEEDBACK("Pull Request Feedback", "Run vairous functional tests against distribution", "ReadyForMerge") {
```

The UUID would be `ReadyForMerge`, to keep the history, right? We also should rename the enum name.

2021-12-31 03:39 UTC, blindpirate commented
This is done.

2021-12-31 03:39 UTC, closed without merging