test to exercise variant matching in the java ecosystem
gradle/gradle pull request #19784
Opened 2022-01-31 23:46 UTC by big-guy

2022-01-31 23:46 UTC, big-guy commented
@bot-gradle test this

2022-02-01 18:21 UTC, DPUkyle approved these changes
LGTM with just a couple of minor comments, thanks for the comprehensive new test.

2022-02-01 18:21 UTC, DPUkyle commented on subprojects/core-api/src/main/java/org/gradle/api/attributes/AttributesSchema.java
> +     * Registers the order of precedence of attributes when resolving ambiguity.
Should we explicitly state that elements listed first are higher precedence?

2022-02-01 18:21 UTC, DPUkyle commented on subprojects/dependency-management/src/main/java/org/gradle/api/internal/attributes/DefaultAttributesSchema.java
> +    private final List<Attribute<?>> precedence = Lists.newArrayList();
nit: replace RHS with `new ArrayList<>();`

I know it's consistent with the line above, but diamond syntax is better here and doesn't rely on guava.

Even guava's javadoc says so:
> Note for Java 7 and later: this method is now unnecessary and should be treated as deprecated. Instead, use the ArrayList constructor directly, taking advantage of the new "diamond" syntax .

2022-02-02 16:18 UTC, DPUkyle commented on subprojects/dependency-management/src/main/java/org/gradle/api/internal/attributes/DefaultAttributesSchema.java
> -import com.google.common.collect.Lists;
*thank you*

2022-02-03 23:09 UTC, big-guy commented
@bot-gradle test this

2022-02-04 00:02 UTC, DPUkyle commented on subprojects/dependency-management/src/main/java/org/gradle/api/internal/attributes/AttributesSchemaInternal.java
> +
nit: un-touch this file if only whitespace change

2022-02-04 00:03 UTC, DPUkyle commented on subprojects/dependency-management/src/main/java/org/gradle/api/internal/attributes/DefaultAttributesSchema.java
> +        precedence.addAll(Arrays.asList(attributes));
Consider invoking `attributeDisambiguationPrecedence(attributes)` instead? This limits the number of places we mutate `precedence`.

2022-02-04 00:09 UTC, DPUkyle commented on subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/attributes/DefaultAttributesSchemaTest.groovy
> +    }
Excellent test!

2022-02-04 00:10 UTC, DPUkyle approved these changes
LGTM with a few minor comments

2022-02-07 23:14 UTC, big-guy commented
@bot-gradle test this

2022-02-08 16:41 UTC, octylFractal requested changes

2022-02-08 16:41 UTC, octylFractal commented on subprojects/dependency-management/src/main/java/org/gradle/api/internal/attributes/DefaultAttributesSchema.java
> +                    remaining.remove(preferredAttribute.getName());
You could just call `remove` instead of `get` 3 lines up for the same result.

2022-02-08 20:12 UTC, tresat requested changes

2022-02-08 20:12 UTC, tresat commented on subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/model/JavaEcosystemAttributeMatcherTest.groovy
> +        selectionSchema = schema.mergeWith(EmptySchema.INSTANCE)
Why does this need to mergeWith an empty schema?

2022-02-08 20:12 UTC, tresat commented on subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/model/JavaEcosystemAttributeMatcherTest.groovy
> +class JavaEcosystemAttributeMatcherTest extends Specification {
+1 for these tests making the expected selection in the Java world explicit.

2022-02-08 20:12 UTC, tresat commented on subprojects/dependency-management/src/test/groovy/org/gradle/internal/component/model/JavaEcosystemAttributeMatcherTest.groovy
> +    private static AttributeContainerInternal attributes(String usage, String libraryElements, int targetJvm) {
I think it would be beneficial to extract these attribute helper methods base attributes test fixture or trait.

2022-02-09 16:35 UTC, DPUkyle commented on subprojects/core-api/src/main/java/org/gradle/api/attributes/AttributesSchema.java
> +    void setAttributeDisambiguationPrecedence(Attribute<?>... attributes);
I suppose we could overload the setter to accept an iterable of attributes as well. `PatternFilterable#include` does this, for example - but only for the additive method, not for the setter. The setter only accepts an iterable. 🤔

2022-02-09 17:21 UTC, octylFractal requested changes

2022-02-09 22:09 UTC, big-guy commented on subprojects/core-api/src/main/java/org/gradle/api/attributes/AttributesSchema.java
> +    Attribute<?>[] getAttributeDisambiguationPrecedence();
I switched this back to a Collection.  It was related to the earlier comment from @tresat that the return type (Collection) of this was different from the setter (array).

2022-02-09 22:09 UTC, big-guy commented on subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/AttributeSelectionSchema.java
> +        private final Optional<Integer> index;
done

2022-02-10 12:37 UTC, tresat commented on subprojects/dependency-management/src/main/java/org/gradle/internal/component/model/AttributeSelectionSchema.java
> +    PrecedenceResult orderByPrecedence(ImmutableAttributes requested);
We could keep it alphabetized and print the ordinal in parens, like:

- Apple (1)
- Banana (4)
- Cat (3)
- Dog (2)

2022-02-11 13:38 UTC, big-guy commented
@bot-gradle test this

2022-02-14 22:54 UTC, big-guy commented
@bot-gradle test this

2022-02-15 00:14 UTC, DPUkyle approved these changes
LGTM; just some smalll nitpicky stuff

2022-02-15 00:14 UTC, DPUkyle commented on subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/attributes/DefaultAttributesSchemaTest.groovy
> +    static abstract class ConcreteNamed implements Named {
super nit: rename this? class `ConcreteNamed` is now... abstract :)

2022-02-15 16:08 UTC, big-guy commented
@bot-gradle test and merge

2022-02-15 19:59 UTC, big-guy commented
@bot-gradle test and merge

2022-02-16 03:05 UTC, blindpirate commented
@bot-gradle test and merge

2022-02-19 06:36 UTC, big-guy commented
@bot-gradle test and merge

2022-02-19 07:25 UTC, big-guy commented
@bot-gradle test and merge

2022-02-19 08:31 UTC, merged