Make Signature plugin more Kotlin friendly
gradle/gradle pull request #19910
Opened 2022-02-14 13:45 UTC by hegyibalint

2022-03-07 11:16 UTC, jbartok requested changes

2022-03-07 11:16 UTC, jbartok commented on subprojects/signing/src/main/java/org/gradle/plugins/signing/SigningExtension.java
> +     * Creates a new {@link SignOperation sign operation} using the given closure to configure it before executing it.
Closure? Copy-paste remnant

2022-03-07 11:16 UTC, jbartok commented on subprojects/signing/src/main/java/org/gradle/plugins/signing/SigningExtension.java
> +     * @param setup The configuration of the {@link SignOperation sign operation}.
Maybe say "configuration action of the..."?

2022-03-14 08:10 UTC, jbartok approved these changes

2022-03-14 08:26 UTC, hegyibalint commented
@bot-gradle test and merge

2022-03-14 11:50 UTC, merged