Fix documentation issues regarding range selection
gradle/gradle pull request #19979
Opened 2022-02-21 08:59 UTC by hegyibalint

2022-02-21 14:51 UTC, hegyibalint commented
@bot-gradle RFM test

2022-02-21 16:11 UTC, ljacomet requested changes
Nice added test and description!

A couple suggestions:

2022-02-22 08:49 UTC, hegyibalint commented on subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionConflictResolutionIntegrationTest.groovy
> +                    assert files == ['a-1.0.jar', 'b-1.0.jar', 'leaf-5.jar']
Ah, I see - we are going to fail before that!

2022-02-22 08:49 UTC, hegyibalint commented on subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_resolution.adoc
> +*** If there is no clear intersection between all the ranges, the highest _existing_ version will be selected from the highest range. If there is no artifact available for the highest range, the reso
Regarding the text:
 - I've tried to apply the same style as before, but it's true that _existing_ is a little bit of a noise here.
 - Should we remove _existing_ in both cases to simplify the statement?

Regarding the logic:
 - This branch is the "If there are only ranges" one, so it should be certain that there are no fixed versions defined.
 - I would think that in this case, Gradle would list the elements, as there is no other choice.

2022-02-22 11:19 UTC, ljacomet commented on subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_resolution.adoc
> +*** If there is no clear intersection between all the ranges, the highest _existing_ version will be selected from the highest range. If there is no artifact available for the highest range, the reso
About removing _existing_ in the previous sentence: might be worth checking what happens with [3,6] and [4,7] when 6 is not an existing version.

For the second point, what I mean is that you suddenly use the word "artifact" which does not appear elsewhere. I think you should use version instead.

2022-02-23 08:59 UTC, hegyibalint commented on subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_resolution.adoc
> +*** If there is no clear intersection between all the ranges, the highest _existing_ version will be selected from the highest range. If there is no artifact available for the highest range, the reso
> About removing existing in the previous sentence: might be worth checking what happens with [3,6] and [4,7] when 6 is not an existing version.
I will definitely check this out, as I haven't found tests for these corner cases.

> For the second point, what I mean is that you suddenly use the word "artifact" which does not appear elsewhere. I think you should use version instead.
Ah, I see... Who said that we are looking for an _artifact_, we are just hunting for information. :laughing:

2022-02-28 09:08 UTC, ljacomet approved these changes

2022-02-28 10:26 UTC, hegyibalint commented
@bot-gradle test and merge

2022-02-28 10:26 UTC, hegyibalint commented
@bot-gradle test and merge

2022-02-28 10:56 UTC, merged