Improve GPG operations
gradle/gradle pull request #20172
Opened 2022-03-14 13:36 UTC by hegyibalint

Fixes #?

### Context

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

2022-03-17 08:13 UTC, hegyibalint commented
@bot-gradle test RFM

2022-03-17 09:36 UTC, hegyibalint commented
Converted back to draft, as the documentation would need a checkup.

2022-03-17 17:11 UTC, hegyibalint commented
@bot-gradle test RFM

2022-03-18 14:38 UTC, ljacomet requested changes
The changes make sense. As indicated on the issue, my main question is about the potential breaking change that this causes.
At the same time, GnuPG had no 1.x releases since 2006 which is pretty ancient.

So I would OK this. However it needs to be documented in the potential breaking changes. See `upgrading_version_7.adoc`

2022-03-21 07:36 UTC, hegyibalint commented
Agreed, I will document this.
Just for the record, I haven't touched legacy GPG handling, so Gradle should still work with 1.x through the `useLegacyGpg` flag.

2022-03-21 10:14 UTC, ljacomet approved these changes
Good to go once you fix the minor doc edit below

2022-03-21 10:14 UTC, ljacomet commented on subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
> +In order to set the old default, the executable can be manually defined by `gradle.properties`:
by -> in

2022-03-21 15:42 UTC, hegyibalint commented
@bot-gradle test and merge

2022-03-21 17:07 UTC, merged