Improve docs related to version ordering and conflict resolution
gradle/gradle pull request #20475
Opened 2022-04-15 12:00 UTC by jbartok

Fixes #20329

2022-04-19 10:36 UTC, jbartok commented on subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_resolution.adoc
> +* if there are still multiple competing versions left, then one is picked with a preference for not having a qualifier or having release status.
I'm pondering if we should explain what "release status" is, but a) I myself have no clue (I'm assuming it's not something very prevalent in typical use-cases), and b) it's already getting confusing enough.

2022-04-22 14:01 UTC, ljacomet requested changes
Thanks for attempting to improve this. See below for comments.

2022-04-25 06:46 UTC, jbartok commented on subprojects/docs/src/docs/userguide/dep-man/02-declaring-dependency-versions/single_versions.adoc
> -** The string `SP` will be ordered higher than `release`, it remains however lower than an unqualified version, limiting its use to versioning schemes using either `FINAL`, `GA` or `RELEASE`: `1.0-RE
The description was overly complicated and confusing. While `dev` is indeed different than the rest, the other special qualifiers are all the same, besides having an ordering defined for them. So `sp` is special only in that it's last in the defined ordering. Mentioning it separately in the documentation, in my opinion, only makes it harder to understand.

Here, in the GH diff it looks weird, much better in IntelliJ:
<img width="1831" alt="image" src="https://user-images.githubusercontent.com/6204813/165034650-31574c1d-7764-470a-a968-6a22706f45d7.png">

2022-04-26 07:51 UTC, ljacomet approved these changes

2022-04-26 07:51 UTC, ljacomet commented
@jbartok This is good to go but needs to be rebased on `release` for 7.5

2022-04-26 09:44 UTC, jbartok commented
@bot-gradle test and merge

2022-04-26 09:57 UTC, merged