Add support for built-in per-task rerun option
gradle/gradle pull request #20895
Opened 2022-06-01 08:52 UTC by abstratt

Issue  #9166 description provides a great summary, but the primary
reason is to allow users to rerun specific tasks (that would otherwise
not be run), like test, without incurring the overhead of re-running all
other tasks (be it for the sake of time saving, or such as when
benchmarking a specific task, such as in #20641).

Additionally, when Gradle has a cache corruption issue (see “Corrupt
plugin jars end up in Gradle's local caches #20830”), rerunning the
affected tasks is the easiest and finest-grained workaround instead of
messing up with local cache state (or resorting to a full re-run of the
task graph).

Issues: #9166, #20641

Fixes #?

### Context

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

2022-06-01 09:06 UTC, abstratt commented
@bot-gradle test this

2022-06-01 09:07 UTC, abstratt commented on subprojects/core/src/main/java/org/gradle/api/internal/tasks/options/OptionReader.java
> +        // add additional built-in options only if they not clash with declared options
if the _do not_ clash...

2022-06-06 20:06 UTC, abstratt commented
@bot-gradle test this

2022-06-07 13:20 UTC, abstratt commented
@bot-gradle test this please

2022-06-07 14:57 UTC, abstratt commented
@bot-gradle test this

2022-06-08 00:47 UTC, abstratt commented
@bot-gradle test this

2022-06-08 12:33 UTC, ljacomet requested changes
One validation question and a few minor typos to fix
Otherwise looks good and glad we can deliver this soon!

2022-06-08 12:33 UTC, ljacomet commented on subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedTaskExecutionIntegrationTest.groovy
> +        withBuildCache().run"compileJava", "jar", "--rerun"
same space issue

2022-06-08 12:33 UTC, ljacomet commented on subprojects/core/src/main/java/org/gradle/api/internal/tasks/options/OptionReader.java
> +        // add additional built-in options only if they not clash with declared options
+1 on fixing that typo 😉

2022-06-08 13:38 UTC, abstratt commented on subprojects/core/src/integTest/groovy/org/gradle/api/tasks/CachedTaskExecutionIntegrationTest.groovy
> +        withBuildCache().run"compileJava", "jar"
IJ's fancy parameter name overlays hid that one from me. Done!

2022-06-08 13:42 UTC, abstratt commented on subprojects/core/src/main/java/org/gradle/api/internal/tasks/options/AbstractOptionElement.java
> +        if (description == null) {
I ended up moving null validation to the BuiltInOptionElement subclass, as I felt we need different failure modes for the two use cases/audiences (custom task options vs built-in options). Some rationale in the commit message.


@ljacomet Please let me know if you are ok with that approach.

2022-06-08 14:11 UTC, ljacomet approved these changes
LGTM!

2022-06-08 15:34 UTC, merged

2022-06-15 00:30 UTC, big-guy commented
@abstratt please don't forget to add something about this to the release notes