Add an includeInCheck() method to JvmTestSuite
gradle/gradle pull request #20900
Opened 2022-06-01 15:54 UTC by tresat

- Allows for keeping configuration of common suite behavior within the suite block itself = more declarative.
- Updated samples in docs to demonstrate, updated existing tests to use.
- Add help method to JvmTestSuite to centralize check if this is the default test suite.

- Looks like this:
![image](https://user-images.githubusercontent.com/44197/171447243-b6292fdf-c981-45fa-9492-a7438e01c3f6.png)

2022-06-01 17:16 UTC, jvandort approved these changes

2022-06-01 20:08 UTC, tresat commented
@bot-gradle test this

2022-06-08 20:33 UTC, big-guy requested changes
I'm not sure this this what we want to do. I think this comes down to a trade-off of push vs pull mechanics and useful conventions.

As it's implemented right now, `includeInCheck` is not "undoable" because it directly modifies the `check` task. We could implement this differently so that it can be undone, but this is inherently a "push" mechanic where we set this flag and Gradle configures something else in response.

We could make this more pull like by always configuring the check task in the plugin like:
```
check.dependsOn testing.suites.withType(JvmTestSuite).matching { includeInCheck.get() == true }
```
In this case, the check task is pulling information out of test suites to make a decision.

However, I don't think this is as simple as a flag to include in "check" or not. We currently have a 1:1:1 relationship between test suite -> test suite target -> test task. The vision is for this to change to 1:N:1 where each test suite has multiple test suite targets. I think that means the decision to include something in check isn't something you can always make at the test suite level.

That's part of why I prefer the explicit "pull" nature of having to configure the check task and explicitly opt-in to test suites being included in check. I think you can do everything you need to do:
```
// All test suites are checked when you run check
check.dependsOn testing.suites

// test and integTest test suites are part of check (test is by default)
check.dependsOn testing.suites.integTest

// Only certain targets of integTest are included with check
check.dependsOn testing.suites.integTest.targets.matching { /* some predicate */ }
```

The only thing that I think is hard to do right now is matching test suite targets across multiple test suites. e.g., I'd like to be able to do something like:
```
// Custom JDK8 only check :
checkJdk8.dependsOn testing.suites.withType(JvmTestSuite).elements.map { testSuite ->
    testSuite.targets.matching { /* target is for JDK8 */ }
}
```
I think we're missing a way to take a domain object collection and map over it in a lazy way.

Thinking about how we might use this in gradle/gradle, I think it would be more likely that we'd want to make check do a subset of useful things vs running all possible tests. I think that means most of the time you'd never really want to use `includeInCheck = true`.

2022-06-08 20:38 UTC, big-guy commented
I know this was in response to some feedback, so we could also fix this by explaining things like I have above with a more explicit example. I think if we had the multiple target support here already, it would be more obvious why it's useful to configure this lower than test suite.

2022-06-09 12:35 UTC, tresat commented
I agree we'd want a similar method on the target level, once we start supporting multiple targets per test.  We'd also want that to take precedence over what is configured at the suite level.  I figured that might be a few versions away, so providing something now at just the suite level which could later be expanded would be better, but I have no problems with adding this functionality on the target level as well now, even if that doesn't buy us anything while there is still only a single target.

The push vs. pull distinction makes sense as a better solution, since it allows toggling back and forth the inclusion of these tests programmatically.  I'd add it to the plugin with something like this, to allow targets to override the suite-level setting, with a property added to both suites and targets (defaulting to false on the suite and true and on the targets, except for true on default test suite):

```
testing.suites.withType(JvmTestSuite).matching { includeInCheck.get() == true }.configureEach { suite -> 
  check.dependsOn targets.matching { includeInCheck.get() == true } 
}
```

Lazy mapping over a domain object collection is interesting, but I think out of scope for this, and I think not needed (yet) since we eagerly create targets upon creating suites?

> I think it would be more likely that we'd want to make check do a subset of useful things vs running all possible tests.

Strong disagree here, I think the expectation is that `check` should "check all the things" by default, and defining a subset of things to check should be done explicitly in a new task.  The fact that non-default suites are opt-in still feels a little off to me. 

The problems I was trying to solve here were to keep the test suite related configuration 1) more declarative, 2) more co-located and contained within the `suites` block, and 3) harder to forget to do (and then be left wondering why my new suite didn't run with my `build` invocation).  I think these are still valid concerns, and this feature (as adjusted per this discussion) would still be a welcome improvement vs. just demoing the current method.  WDYT?

2022-06-10 14:32 UTC, big-guy commented
```
testing.suites.withType(JvmTestSuite).matching { includeInCheck.get() == true }.configureEach { suite -> 
  check.dependsOn targets.matching { includeInCheck.get() == true } 
}
```

> Strong disagree here, I think the expectation is that check should "check all the things" by default, and defining a subset of things to check should be done explicitly in a new task. The fact that non-default suites are opt-in still feels a little off to me.

I was thinking of two scenarios:
1. Some test suites can only run in certain environments. `gradle check` should run the "useful" set for the environment you're in. 
2. Test suites with soak tests or performance tests or with many cross-version targets. 

These could be controlled by `includeInCheck` sort of, but it seems awkward since you'd probably want to have a new task to run them somehow (`checkPerformance` or `checkCompatibility7.0` or something like that).

> The problems I was trying to solve here were to keep the test suite related configuration 1) more declarative, 2) more co-located and contained within the suites block, and 3) harder to forget to do (and then be left wondering why my new suite didn't run with my build invocation). I think these are still valid concerns, and this feature (as adjusted per this discussion) would still be a welcome improvement vs. just demoing the current method. WDYT?

I'm not sure.  We can chat more in our 1:1

2022-06-14 12:08 UTC, tresat commented
During our discussion, we came to the conclusion to not attempt adding any flag or help method for this now.  

The major reason for this was that regardless of whether or not a flag or method would be helpful, there is no easy way to keep that flag correct if the check task's dependencies are modified _outside_ the suite.  Better to have no flag and rely on slightly more imperative and scattered configuration than to have a potentially incorrect or misleading one which would introduce ordering concerns.

2022-06-14 12:08 UTC, closed without merging