Consolidate IvyArtifactName serialization
gradle/gradle pull request #20914
Opened 2022-06-02 20:19 UTC by jvandort

A clean-up PR to separate assorted code changes I found along the way of debugging #20696

* Create and use unified IvyArtifactNameSerializer to reduce duplicated encoder/decoder code
* Add missing @Nullable annotations all-around where they were prevously missing
* Update ComponentOverrideMetadata to hold only a single IvyArtifactName since it only ever held a single one
* Update outdated javadoc, fix grammar
* Reworked logic in DefaultArtifactMetadataSource
* Avoid potential NPE in DefaultIvyPatternMatcherExcludeRuleSpec
* Replace GUtil.isTrue with StringUtils.isNotEmpty
* Simplify testing code by consolidating/parameterizing some tests, removing unused code, make methods static

2022-06-02 20:20 UTC, jvandort commented
@bot-gradle test this

2022-06-16 15:44 UTC, ljacomet requested changes
Looks good overall except for the API breaking changes, see below.

2022-06-22 21:16 UTC, jvandort commented
@bot-gradle test ReadyForNightly

2022-06-22 21:16 UTC, jvandort commented on subprojects/architecture-test/src/changes/accepted-public-api-changes.json
> +            "type": "org.gradle.api.artifacts.DependencyArtifact",
Removed `@Nullable` changes for this PR on API types

2022-06-23 09:42 UTC, ljacomet approved these changes

2022-06-24 04:21 UTC, jvandort commented
@bot-gradle test and merge

2022-06-24 05:18 UTC, merged