Remove non java-gradle-plugin customPlugin snippet
gradle/gradle pull request #21091
Opened 2022-06-23 20:25 UTC by jvandort

All tags which were previously defined in this snippet were moved elsewhere.
Moved tests from this snippet to the java-gradle-plugin snippet which previously
did not define any tests

2022-06-23 20:25 UTC, jvandort commented
@bot-gradle test BD

2022-06-23 20:35 UTC, jvandort commented
@bot-gradle test BD

2022-06-24 22:50 UTC, big-guy requested changes

2022-06-24 22:50 UTC, big-guy commented on subprojects/docs/src/snippets/base/customExternalTask/groovy/task/build.gradle
> +    }
Unfortunately, I don't think we can do this quite yet. This is an incubating feature and we need to show the stable version for now.

2022-06-24 22:50 UTC, big-guy commented on subprojects/docs/src/snippets/base/customExternalTask/kotlin/task/build.gradle.kts
> +testing {
Same thing here

2022-06-28 00:04 UTC, jvandort commented
@bot-gradle test BD

2022-06-28 15:11 UTC, big-guy approved these changes

2022-06-28 15:24 UTC, jvandort commented
@bot-gradle test and merge

2022-06-28 20:40 UTC, jvandort commented
@bot-gradle test and merge

2022-06-28 22:07 UTC, merged