Remove ability to add configuration as a dependency - it is now an error
gradle/gradle pull request #21725
Opened 2022-08-29 20:51 UTC by tresat

Fixes #21724

2022-08-29 21:02 UTC, tresat commented
@bot-gradle test this

2022-08-30 10:59 UTC, tresat commented
@bot-gradle test this

2022-08-31 02:30 UTC, jvandort requested changes

2022-08-31 11:10 UTC, tresat commented on subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DefaultDependencyHandler.java
> +            throw new GradleException("Adding a Configuration as a dependency is a confusing behavior that is no longer allowed as of Gradle 8.0.");
I was keeping the existing wording, but on reflection I agree with you, "behavior" isn't great here.  I think I'll just remove that "confusing behavior" bit completely and just say it is no longer allowed.

2022-08-31 11:25 UTC, tresat commented
@bot-gradle test this

2022-08-31 13:52 UTC, jvandort approved these changes

2022-08-31 14:02 UTC, tresat commented
@bot-gradle test and merge

2022-08-31 17:55 UTC, merged