Use fixed timestamps in Minify transform
gradle/gradle pull request #21849
Opened 2022-09-03 01:03 UTC by liutikas

2022-09-07 08:55 UTC, jbartok requested changes

2022-09-07 08:56 UTC, jbartok commented
Pls. base this PR on the `release` branch so that we can include in Gradle 7.6.

2022-09-07 16:00 UTC, liutikas commented on build-logic/basics/src/main/kotlin/gradlebuild/basics/classanalysis/AnalyzeAndShade.kt
> +    entry.time = 0
Done

2022-09-07 16:20 UTC, liutikas commented
> Pls. base this PR on the `release` branch so that we can include in Gradle 7.6.

Done

2022-09-08 15:46 UTC, liutikas commented
Anything else missing here?

2022-09-09 06:57 UTC, jbartok approved these changes

2022-09-09 06:57 UTC, jbartok commented
@bot-gradle test this

2022-09-09 10:38 UTC, jbartok commented
@bot-gradle test and merge

2022-09-09 10:47 UTC, jbartok commented
@bot-gradle test and merge

2022-09-09 10:50 UTC, jbartok commented
@bot-gradle test and merge

2022-09-09 11:20 UTC, jbartok commented
@bot-gradle test and merge

2022-09-09 19:28 UTC, merged