Add deprecation warning for ProjectReportsPluginConvention
gradle/gradle pull request #22085
Opened 2022-09-19 12:56 UTC by donat

2022-09-19 13:57 UTC, donat commented
@bot-gradle test RFM

2022-09-19 18:15 UTC, donat commented
@bot-gradle test RFM

2023-04-13 10:05 UTC, ov7a commented
@bot-gradle test this

2023-04-13 11:25 UTC, ov7a commented
@bot-gradle test this

2023-04-13 12:33 UTC, jbartok requested changes
Looks good besides my one comment.

2023-04-13 12:33 UTC, jbartok commented on subprojects/docs/src/docs/userguide/migration/upgrading_version_8.adoc
> +[[project_report_convention_deprecation]]
Please look at what I merged in for the Java Plugin and the Application Plugin and make this part a bit more consistent with that.

2023-04-13 16:27 UTC, jbartok approved these changes

2023-04-14 04:49 UTC, jbartok commented
@bot-gradle test and merge

2023-04-14 05:44 UTC, merged