Add missed dsl html for ProcessResources task
gradle/gradle pull request #22163
Opened 2022-09-23 08:06 UTC by 6hundreds

Fixes https://github.com/gradle/gradle/issues/21522

2022-09-23 12:47 UTC, nathan-contino approved these changes
LGTM assuming this has the intended result. You can run `@bot-gradle test BD` to be sure before you merge.

2022-09-23 13:29 UTC, ljacomet requested changes
Could you make this PR against `release` and target 7.6 RC1?

Changes are ✅ otherwise

2022-09-27 08:35 UTC, ljacomet approved these changes

2022-09-27 08:36 UTC, ljacomet commented
@bot-gradle test and merge

2022-09-27 08:48 UTC, merged