Fix way of copying TestNGOptions
gradle/gradle pull request #22247
Opened 2022-09-29 14:26 UTC by snoopcheri

When copying the `TestNGTestFramework` in the test-retry Gradle plugin, this currently fails miserably with:

```
Caused by: java.lang.IllegalStateException: Cannot create DslObject for 'org.gradle.api.tasks.testing.testng.TestNGOptions@5b92dc57' (class: TestNGOptions) as it does not implement 'org.gradle.api.internal.IConventionAware' (it is not a DSL object)
	at org.gradle.api.internal.plugins.DslObject.toType(DslObject.java:108)
	at org.gradle.api.internal.plugins.DslObject.getConventionMapping(DslObject.java:83)
```

It seems that the copied `TestNGOption` object must be created via an object factory.

This PR fixes this issue.

2022-09-29 14:37 UTC, jvandort requested changes
We should make this same change for `JUnitTestFramework` and `JUnitPlatformTestFramework`.

2022-09-29 15:04 UTC, snoopcheri commented
> We should make this same change for `JUnitTestFramework` and `JUnitPlatformTestFramework`.

Do you mean for consistency, the `JUnitOptions` and `JUnitPlatformOptions` should also just provide a copy-method instead of a "copy-constructor"?

The `TestNGOptions` is the only one that has to be created via an object factory. The other two were already created with the default constructor before (see [here](https://github.com/gradle/gradle/blob/release/subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junit/JUnitTestFramework.java#L47) and [here](https://github.com/gradle/gradle/blob/release/subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/junitplatform/JUnitPlatformTestFramework.java#L50))

I figured that correctness-by-construction would be more important here, but I can surely make the copying consistent across all three versions.

2022-09-29 15:12 UTC, snoopcheri commented on subprojects/testing-jvm/src/main/java/org/gradle/api/tasks/testing/testng/TestNGOptions.java
> +    public void copyFrom(TestNGOptions other) {
The `addAll` calls are not really correct as we're not doing this in the constructor anymore. We should clear the collections first before populating them again.

2022-09-29 15:16 UTC, jvandort commented
@snoopcheri My understanding is that all DSL instances that users interact with should be instantiated with via the instantiator. Obviously, my understanding is flawed 'cause this has worked in the past without us needing to instantiate `JUnitOptions ` and `JUnitPlatformOptions`. So perhaps we do not need to instantiate these with the instantiator. I will look into this myself and we don't need to block this PR on it. 

However, I would still prefer we copy all of the options files in the same manner. Given that Test NG requires a copy method and not a copy constructor, I would prefer we change the other options to use a copy method. 

Another option, which would require less changes (and TBH is probably preferable here) is to use the instantiator with the copy constructor. The instantiator will allow you to pass arguments into the constructor. Consider the following code:

```
TestNGOptions copiedOptions = objects.newInstance(TestNGOptions.class, options);
```
This way we can still use the copy constructor the way we have been.

2022-09-29 15:54 UTC, snoopcheri commented
@jvandort 

I've tried to create `TestNGOptions` with the object factory, but that failed:
* if the constructor is not annotated with `@Inject`, it doesn't get picked up
* if there are multiple constructors annotated with `@Inject`, this fails with "Class TestNGOptions has multiple constructors that are annotated with @Inject."

Therefore I propose the following:
* remove all copy-constructors
* add copy-methods for all test options and make sure that containers are cleared before adding via `addAll(...)`

WDYT?

2022-09-29 15:56 UTC, jvandort commented
@snoopcheri I would support your proposed change

2022-09-29 17:24 UTC, snoopcheri commented
@jvandort I've implemented to copy methods

And I've added the following changes:
* copy-methods now have a simple unit test
* I stopped copying two fields from `TestNGOptions` as those are marked as transient. I don't believe we should copy those

2022-09-29 18:02 UTC, jvandort commented
Looks like you've got an unused import in `JUnitPlatformOptions`. Try running `./gradlew sanityCheck` locally to make sure there aren't any more code quality issues after that

2022-09-29 18:09 UTC, jvandort approved these changes
LGTM other than sanity check failing

2022-09-30 07:28 UTC, marcphilipp approved these changes

2022-09-30 09:22 UTC, snoopcheri commented
> LGTM other than sanity check failing

@jvandort All checks are passing now

2022-09-30 14:47 UTC, jvandort commented
@bot-gradle test and merge

2022-09-30 16:32 UTC, merged