WIP: Deprecate old groovy workaround behavior
gradle/gradle pull request #22289
Opened 2022-10-01 05:05 UTC by jvandort

Theres this old workaround that was supposed to be temporary. It wasn't. Deprecate the behavior and let's see what breaks. 

This is getting in the way of making the task container extensible

See: https://github.com/gradle/gradle/commit/79d084e16050b02cc566f71df3c3ad7a342b9c5a

2022-10-01 05:06 UTC, jvandort commented
@bot-gradle test this

2022-10-03 17:06 UTC, jvandort commented
@bot-gradle test this

2022-10-03 18:44 UTC, jvandort commented
@bot-gradle test this

2022-10-04 04:08 UTC, big-guy requested changes

2022-10-04 14:54 UTC, jvandort commented on subprojects/model-core/src/main/java/org/gradle/internal/metaobject/ConfigureDelegate.java
> +                    DeprecationLogger.deprecateBehaviour("Referencing script level configure method from named container configure closure when that closure would fail with MissingMethodException")
The `_configure` method which the try/catch wraps is only overridden by `NamedDomainObjectContainerConfigureDelegate` and `PolymorphicDomainObjectContainerConfigureDelegate`. All other instances of `ConfgureDelegate` use the default implementation which returns `DynamicInvokeResult.notFound()` and does not throw an exception.

2022-10-04 15:19 UTC, jvandort commented on subprojects/model-core/src/main/java/org/gradle/internal/metaobject/ConfigureDelegate.java
> +                    DeprecationLogger.deprecateBehaviour("Referencing script level configure method from named container configure closure when that closure would fail with MissingMethodException")
I left the upgrade guide as-is, though I'm happy to take recommendations there as well. I think the upgrade guide needs to be more descriptive of the circumstances where the behavior changed as opposed to the deprecation message which just recommends alternatives.

2022-10-04 17:20 UTC, big-guy commented on subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
> +==== Referencing Groovy script configure method from container configure closure is now deprecated
This title is a little technical and most people won't recognize what's changing here.

Maybe:
```suggestion
==== Implicitly referencing outer scope methods in some configuration blocks in Groovy DSL is now deprecated
```

2022-10-04 20:55 UTC, jvandort commented
@bot-gradle test and merge

2022-10-04 20:56 UTC, jvandort commented
@bot-gradle help

2022-10-04 20:56 UTC, jvandort commented
@bot-gradle cancel

2022-10-04 20:58 UTC, jvandort commented
@bot-gradle test and merge

2022-10-04 21:53 UTC, merged