Setup enriched report renderer for binary compatibility report
gradle/gradle pull request #22300
Opened 2022-10-03 20:59 UTC by tresat

Fixes #22299 

Allows the "bin.cmp.report.severity.filter" property to auto-select the filter on the Binary Compatibility report, if set

2022-10-03 20:59 UTC, tresat commented
This is built on a branch based on https://github.com/gradle/gradle/pull/22283, that PR should be merged first.

2022-10-07 15:48 UTC, octylFractal requested changes

2022-10-07 15:48 UTC, octylFractal commented on build-logic/binary-compatibility/src/main/groovy/gradlebuild/EnrichedReportRenderer.groovy
> +                            if (this.text == level) {
```suggestion
                            if (this.text === level) {
```
Strict equality should be preferred when possible.

2022-10-07 19:17 UTC, octylFractal approved these changes

2022-10-08 00:01 UTC, tresat commented
@bot-gradle test and merge

2022-10-08 00:48 UTC, merged