Remove deprecated methods from PluginCollection
gradle/gradle pull request #22393
Opened 2022-10-12 19:10 UTC by tresat

Fixes #22392

2022-10-12 19:10 UTC, tresat commented
@bot-gradle test this

2022-10-12 20:07 UTC, tresat commented
@bot-gradle test this

2022-10-12 23:11 UTC, big-guy requested changes
I think we don't actually want to remove these methods because they're documentation that the PluginCollection class doesn't support those methods.

2022-10-12 23:11 UTC, big-guy commented on subprojects/architecture-test/src/changes/accepted-public-api-changes.json
> +            "acceptation": "[ADD YOUR CUSTOM REASON HERE]",
Need reasons here too

2022-10-13 13:59 UTC, tresat commented
@bot-gradle test this

2022-10-13 14:00 UTC, tresat commented
> I think we don't actually want to remove these methods because they're documentation that the PluginCollection class doesn't support those methods.

I wonder if it would be clearer to throw the exceptions via default methods in the interface rather than rely on implementers.  Trying it now.  If it doesn't work, I'll just close this.

2022-10-13 15:14 UTC, tresat commented
Doesn't work, the methods from the base domain object class' are chosen rather than the defaults from the interface, so they just have be reimplemented in the plugin collection types anyway.

I'll close this as no further action needed.

2022-10-13 15:14 UTC, closed without merging