Remove deprecated fields from Usage
gradle/gradle pull request #22404
Opened 2022-10-13 15:42 UTC by tresat

Fixes #22403

2022-10-13 17:11 UTC, tresat commented
@bot-gradle test this

2022-10-25 20:56 UTC, tresat commented
@bot-gradle test this

2022-10-26 13:17 UTC, tresat commented
@bot-gradle test this

2022-10-27 07:01 UTC, big-guy requested changes
I don't think we can actually completely remove these because there is published metadata with these attributes still. 

We can remove the values from Usage, but they'll need to go somewhere else (JavaEcosystemSupport?) so we can keep the compatibility rules working.

2022-11-04 18:06 UTC, tresat commented
@bot-gradle test this

2022-11-04 20:22 UTC, tresat commented
@bot-gradle test QFL

2022-11-07 13:08 UTC, tresat commented
@bot-gradle test this

2022-11-07 17:33 UTC, big-guy requested changes

2022-11-07 17:33 UTC, big-guy commented on subprojects/core/src/main/java/org/gradle/api/internal/artifacts/JavaEcosystemAttributesDescriber.java
>                  break;
I think these need to stick around too since they're explaining the usage even with deprecated usages.

2022-11-07 17:33 UTC, big-guy commented on subprojects/maven/src/integTest/groovy/org/gradle/api/publish/maven/MavenPublishFeaturesJavaIntegTest.groovy
> +                        attribute(Usage.USAGE_ATTRIBUTE, project.objects.named(Usage, "java-runtime-jars"))
shouldn't this be the new one like you changed in IvyPublishJavaIntegTest?

2022-11-07 17:33 UTC, big-guy commented on subprojects/plugins/src/integTest/groovy/org/gradle/java/compile/AbstractJavaGroovyCompileAvoidanceIntegrationSpec.groovy
> -                        attributes.attribute(USAGE_ATTRIBUTE, objects.named(Usage, Usage.JAVA_API_CLASSES))
can't this be the new one too?  you might need other attributes as well

2022-11-07 17:33 UTC, big-guy commented on subprojects/core/src/test/groovy/org/gradle/api/internal/attributes/DefaultImmutableAttributesFactoryTest.groovy
> -    }
This should probably stay because we're still doing this

2022-11-07 17:59 UTC, tresat commented
@bot-gradle test this

2022-11-07 19:09 UTC, tresat commented
@bot-gradle test this

2022-11-07 22:20 UTC, tresat commented
@bot-gradle test QFL

2022-11-08 13:06 UTC, tresat commented
@bot-gradle test this

2022-11-08 15:49 UTC, tresat commented
@bot-gradle test this

2022-11-08 20:35 UTC, tresat commented
@bot-gradle test this

2022-11-08 20:46 UTC, big-guy approved these changes

2022-11-08 21:31 UTC, tresat commented
@bot-gradle test and merge

2022-11-08 22:30 UTC, merged