Remove trailing slash requirement for build cache URL
gradle/gradle pull request #22410
Opened 2022-10-13 21:28 UTC by erichaagdev

### Context
There does not seem to be a reason to require a trailing `/` when creating an instance of `HttpBuildCacheService`. This sometimes causes us to [create workarounds](https://github.com/gradle/gradle-enterprise-build-validation-scripts/issues/155). 

To me, removing the trailing `/` is the most logical permanent fix for this. 

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

2022-10-13 21:36 UTC, octylFractal requested changes

2022-10-13 21:36 UTC, octylFractal commented on subprojects/build-cache-http/src/main/java/org/gradle/caching/http/internal/HttpBuildCacheService.java
> +
I think it is worth adding documentation here:
```suggestion

    /**
     * Add a trailing slash to the given URI's path if necessary.
     *
     * @param uri the original URI
     * @return a URI guaranteed to have a trailing slash in the path
     */
```

2022-10-13 21:39 UTC, erichaagdev commented
@octylFractal, do you think it is necessary to remove the trailing `/` from the snippets?

For example: https://github.com/gradle/gradle/blob/31bff5917cb0573b30258e963cdad58e1d8b128b/subprojects/docs/src/snippets/buildCache/configure-built-in-caches/groovy/settings.gradle#L15

2022-10-13 21:41 UTC, octylFractal commented
I think it is better to leave it in place, since the docs may be referenced by people who use older versions of Gradle and it would be better if it worked for them too.

2022-10-13 21:52 UTC, octylFractal requested changes
Can you add a test or two to `HttpBuildCacheServiceIntegrationTest` to verify that everything works with both a slash and without a slash?

2022-10-13 22:21 UTC, erichaagdev commented
@octylFractal I'm not sure if you noticed, but I made it so that [all tests run without a trailing slash](https://github.com/gradle/gradle/pull/22410/files#diff-e75ac025e8e43b2489fbed275c5f3681eac3c9b2fd77422acd1563e08f31a4f2R40). Therefore, I added test a test to make sure `url` can be specified _with_ a trailing slash.

Do you think I should do the opposite and run all tests with a trailing slash (like before) and add a test testing it works with no slash?

2022-10-13 22:26 UTC, octylFractal commented
No, I think it's good. Thank you :)

2022-10-13 22:26 UTC, octylFractal approved these changes

2022-10-14 06:31 UTC, lptr approved these changes
LGTM.

2022-10-14 15:27 UTC, lptr commented
@bot-gradle test and merge please.

2022-10-14 16:23 UTC, merged