Show all deprecation instances (#16688)
gradle/gradle pull request #22489
Opened 2022-10-23 23:38 UTC by Vampire

Fixes #16688

### Context
Without this PR only the first finding of a concrete deprecation
warning is shown. This means you can only fix one after the other and
also only see own violations if all plugins were fixed.

With this PR all instances of a deprecation warning are shown
as long as they come from different locations.
The printed stack information is simply included in the
message deduplication that previously only contained the message itself.

### Contributor Checklist
- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [x] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [x] Provide unit tests (under `<subproject>/src/test`) to verify logic
- n/a Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

2022-11-10 08:49 UTC, jbartok commented
@bot-gradle test QFL

2022-11-10 09:03 UTC, jbartok commented
@bot-gradle test QFL

2022-11-10 09:37 UTC, jbartok commented
@Vampire, after reviewing your PR the conclusion is that your reasoning and changes make sense, BUT you implemented them in an overly generic way. I would say that this behavior should happen only when `--warning-more=all` is used and not for any other warning mode values. 

Also, pls. keep an eye out for other tests that are failing with your changes, see above failures on TC (just log in as guest).

2022-11-10 09:39 UTC, jbartok requested changes
@Vampire, after reviewing your PR the conclusion is that your reasoning and changes make sense, BUT you implemented them in an overly generic way. I would say that this behavior should happen only when --warning-more=all is used and not for any other warning mode values.

Also, pls. keep an eye out for other tests that are failing with your changes, see above failures on TC (just log in as guest).

2022-11-13 02:43 UTC, Vampire commented
Thanks for the heads-up.
I do not fully agree though.
It should also be done for `fail` as they are also all printed, and additionally the build fails.
I think the correct behavior is to do it for `warningMode.shouldDisplayMessages() == true` and just have a separate boolean for the summary case.

I'll do it like that and you can have another look then, after I also checked the failing tests.

2022-11-13 04:08 UTC, Vampire commented
I pushed a new version with the changes and the failed tests fixed

2022-11-14 13:22 UTC, jbartok commented
@bot-gradle test QFL

2022-11-16 09:28 UTC, jbartok approved these changes

2022-11-16 11:16 UTC, eskatos commented
@bot-gradle test this

2022-11-16 16:35 UTC, Vampire commented
@eskatos I fixed the failing test, please trigger another build. :-)

2022-11-16 16:57 UTC, eskatos commented
@bot-gradle test this

2022-11-17 07:30 UTC, jbartok commented
@bot-gradle test and merge

2022-11-17 07:47 UTC, jbartok commented
@bot-gradle test and merge

2022-11-17 09:10 UTC, eskatos commented
@jbartok this is release notes worthy IMO

2022-11-17 09:25 UTC, merged