Add blurb about CodeNarc tool autodetection to release notes
gradle/gradle pull request #22515
Opened 2022-10-26 12:58 UTC by tresat

Fixes #21509

2022-10-26 12:58 UTC, tresat commented
@bot-gradle test bd

2022-10-26 17:15 UTC, nathan-contino approved these changes
Docs LGTM! One suggestion.

2022-10-26 17:15 UTC, nathan-contino commented on subprojects/docs/src/docs/release/notes.md
> +The [CodeNarc](https://codenarc.org/) project now publishes separate versions for use with Groovy 4.  Although Gradle still currently ships with Groovy 3, to ensure future compatibility the [CodeNarc
```suggestion
The [CodeNarc](https://codenarc.org/) project now publishes separate versions for use with Groovy 4.
Gradle still currently ships with Groovy 3.
To ensure future compatibility, the [CodeNarcPlugin](userguide/codenarc_plugin.html) now automatically detects the appropriate version of CodeNarc for the current Groovy runtime.
You can still explicitly specify a CodeNarc version with the `toolVersion` property on the [CodeNarcExtension](current/dsl/org.gradle.api.plugins.quality.CodeNarcExtension.html#org.gradle.api.plugins.quality.CodeNarcExtension).
```
Suggestion: split up some long sentences, trim a few words.

2022-10-27 06:56 UTC, big-guy requested changes

2022-10-27 06:56 UTC, big-guy commented on subprojects/docs/src/docs/release/notes.md
> +The [CodeNarc](https://codenarc.org/) project now publishes separate versions for use with Groovy 4.  Although Gradle still currently ships with Groovy 3, to ensure future compatibility the [CodeNarc
This shouldn't be linking to /current/

2022-11-04 18:25 UTC, tresat commented
@bot-gradle test this

2022-11-07 17:26 UTC, big-guy approved these changes

2022-11-07 17:36 UTC, tresat commented
@bot-gradle test and merge

2022-11-07 18:26 UTC, tresat commented
@bot-gradle test and merge

2022-11-07 18:46 UTC, merged