Allow reseting test framework to same value after setting options
gradle/gradle pull request #22595
Opened 2022-11-02 18:25 UTC by tresat

Prior to blocking a call to set the test framework on a Test task, check if the value is already finalized to the value and if so; allow it.

Needed to fix an Android Studio issues using Gradle 8.0 milestone 3.

- This also adds a isFinalized method to AbstractProperty to support this use case.
- Also expand and adjust some tests to now pass, and explicitly test the built-in test task and custom Test tasks outside of Test Suites.

2022-11-02 18:25 UTC, tresat commented
@bot-gradle test this

2022-11-02 18:47 UTC, tresat commented
@bot-gradle test this

2022-11-02 19:35 UTC, big-guy requested changes

2022-11-02 19:35 UTC, big-guy commented on subprojects/model-core/src/main/java/org/gradle/api/internal/provider/AbstractProperty.java
> +    }
Can you add a test for this? Maybe PropertySpec or nearby

2022-11-02 19:35 UTC, big-guy commented on subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/TestTaskIntegrationTest.groovy
> +        ignoreWhenJUnitPlatform()
Can you also add the simplest case:

```
test {
  useJUnit { }
  useJUnit { }
}
```

2022-11-02 22:28 UTC, tresat commented
@bot-gradle test this

2022-11-03 16:59 UTC, big-guy approved these changes

2022-11-03 18:11 UTC, merged