Refactor ArtifactSelector to avoid capturing the full component metad…
gradle/gradle pull request #22821
Opened 2022-11-22 17:53 UTC by big-guy

…ata in the lambda

2022-11-22 17:54 UTC, big-guy commented
@bot-gradle test this

2022-11-22 19:30 UTC, big-guy commented
@bot-gradle help

2022-11-22 19:30 UTC, big-guy commented
@bot-gradle test PT

2022-11-22 22:11 UTC, big-guy commented
@bot-gradle test this

2022-11-22 23:41 UTC, big-guy commented on subprojects/base-services/src/main/java/org/gradle/internal/exceptions/DefaultMultiCauseException.java
> +    private static class HideStacktrace extends ThreadLocal<Boolean> {
We're limited to <Java 8, so a static inner class is the only way to replace this one.

2022-11-22 23:41 UTC, big-guy commented on subprojects/core/src/main/java/org/gradle/api/internal/DefaultMutationGuard.java
> +    private final ThreadLocal<Boolean> mutationGuardState = new GuardState();
`ThreadLocal.withInitial(...);` is no good here because CC can't serialize the Supplier.

2022-11-22 23:41 UTC, big-guy commented on subprojects/model-core/src/main/java/org/gradle/model/internal/registry/RuleContext.java
> +    private static final ThreadLocal<Deque<ModelRuleDescriptor>> STACK = ThreadLocal.withInitial(ArrayDeque::new);
I don't think this makes any difference to do.

2022-11-23 07:43 UTC, octylFractal approved these changes

2022-11-23 13:55 UTC, tresat approved these changes

2022-11-29 12:18 UTC, ljacomet requested changes
The PR content looks good, but we should not merge until we have a plan for 8.0 branching and future 7.6 releases.

2022-12-02 00:58 UTC, big-guy commented
@bot-gradle test and merge

2022-12-05 11:23 UTC, merged