Removing incubating on a number of methods and types
gradle/gradle pull request #22861
Opened 2022-11-25 16:35 UTC by ljacomet

The PR is using different commits to separate the different areas. Best reviewed by commit.

@gradle/bt-configuration-cache Would be great to have you confirm these de-incubation are good to go for Gradle 8

2022-11-25 16:35 UTC, ljacomet commented
@bot-gradle test this

2022-11-28 11:30 UTC, jbartok approved these changes
LGTM

2022-11-29 19:49 UTC, mlopatkin reviewed
I don't think we're ready to de-incubate ValueSource APIs in 8.0, there are some rough edges in the contract to finalize. We'll do it as part of the stable CC milestone, which is likely to be post 8.0.

2022-11-30 05:46 UTC, adammurdoch requested changes

2022-11-30 05:46 UTC, adammurdoch commented on subprojects/core-api/src/main/java/org/gradle/api/provider/ProviderFactory.java
> -    @Incubating
Let's not promote the `ValueSource` stuff yet. We'll do this in 8.1 instead once we've finalized the contract.

2022-11-30 05:46 UTC, adammurdoch commented on subprojects/core-api/src/main/java/org/gradle/api/provider/ValueSource.java
> -@Incubating
Same here

2022-11-30 05:46 UTC, adammurdoch commented on subprojects/core-api/src/main/java/org/gradle/api/provider/ValueSourceParameters.java
> -@Incubating
Same here

2022-11-30 05:46 UTC, adammurdoch commented on subprojects/core-api/src/main/java/org/gradle/api/provider/ValueSourceSpec.java
> -@Incubating
Same here

2022-11-30 09:11 UTC, ljacomet commented
@bot-gradle test and merge

2022-11-30 10:17 UTC, merged