Backport recent toolchain related fixes
gradle/gradle pull request #23095
Opened 2022-12-10 12:22 UTC by jbartok

Fixes #23025

2022-12-10 12:24 UTC, jbartok commented
@bot-gradle test QFL

2022-12-14 11:44 UTC, ljacomet requested changes
Looks good overall, and nice that it does not contain all the changes for abstract methods in DefaultSettings.

However, I would also not backport other changes, see below:

2022-12-14 11:44 UTC, ljacomet commented on subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ConfigurationInternal.java
> +public interface ConfigurationInternal extends ResolveContext, Configuration, DeprecatableConfiguration, DependencyMetaDataProvider, FinalizableValue {
Given this is a backport, I would exclude this change, just to be on the safe side.

2022-12-14 11:44 UTC, ljacomet commented on subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfigurationPublications.java
> +public class DefaultConfigurationPublications implements ConfigurationPublications, FinalizableValue {
I would exclude that change as well.

2022-12-14 11:44 UTC, ljacomet commented on subprojects/core/src/main/java/org/gradle/api/internal/SettingsInternal.java
> +public interface SettingsInternal extends Settings, PluginAwareInternal, FinalizableValue {
That one as well

2022-12-14 12:57 UTC, ljacomet approved these changes

2022-12-14 15:47 UTC, jbartok commented
@bot-gradle test and merge

2022-12-14 18:31 UTC, merged