allow labels for gradle wrapper task versions
gradle/gradle pull request #23179
Opened 2022-12-15 09:19 UTC by reinsch82

permitted labels:
- "latest"
- "release-candidate"
- "nightly"
- "release-nightly"

- Implements: #13504

Signed-off-by: Reinhold Degenfellner <rdegenfellner@gradle.com>

2022-12-15 14:34 UTC, reinsch82 commented
@bot-gradle test AFT

2022-12-15 15:07 UTC, eskatos reviewed
This is looking good :+1: 

Left a bunch of comments and suggestions. Mostly :lipstick:

2022-12-15 15:07 UTC, eskatos commented on subprojects/build-init/src/test/groovy/org/gradle/api/tasks/wrapper/WrapperTest.groovy
> +    private String targetWrapperJarPath = "gradle/wrapper"
:lipstick: can be made `final`

2022-12-15 16:58 UTC, eskatos commented
@bot-gradle test AFT

2022-12-15 18:00 UTC, eskatos commented
@bot-gradle test this

2022-12-16 11:05 UTC, eskatos commented on subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java
> +        "The following labels are allowed: latest, release-candidate, nightly, and release-nightly")
```suggestion
        "The following labels are allowed: latest, release-candidate, nightly, and release-nightly.")
```

2022-12-16 11:05 UTC, eskatos commented on subprojects/docs/src/docs/userguide/reference/command_line_interface.adoc
> +$ gradle wrapper --gradle-version=8.1
:+1:

2022-12-16 11:06 UTC, eskatos commented on subprojects/docs/src/docs/userguide/reference/gradle_wrapper.adoc
>  == Upgrading the Gradle Wrapper
We should also add some words in this section.

2022-12-16 15:03 UTC, eskatos requested changes
A few tiny changes requested

2022-12-16 15:03 UTC, eskatos commented on subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java
> +     * e.g. there is not a `release-candidate` available at all times.
:x: These two lines are now redundant with the `@throws` tag and should be removed.

2022-12-16 15:03 UTC, eskatos commented on subprojects/docs/src/docs/release/notes.md
> +More Details can be found in the [Gradle Wrapper](userguide/gradle_wrapper.html#sec:adding_wrapper) section.
:x:
```suggestion
More details can be found in the [Gradle Wrapper](userguide/gradle_wrapper.html#sec:adding_wrapper) section.
```

2022-12-16 15:21 UTC, eskatos approved these changes
Good work!

:tada:

2022-12-16 15:22 UTC, reinsch82 commented
@bot-gradle test this

2022-12-19 06:43 UTC, reinsch82 commented
@bot-gradle test and merge

2022-12-19 06:46 UTC, reinsch82 commented
@bot-gradle test and merge

2022-12-19 07:50 UTC, merged

2022-12-20 11:00 UTC, eskatos commented
A follow up issue should be created about supporting `milestone`.

2023-01-03 08:23 UTC, eskatos commented
@reinsch82 did you get to create the follow up issue about supporting `milestone`?

We should also review how our custom wrapper tasks in the `gradle/gradle` build could be rewritten using this new feature. See https://github.com/gradle/gradle/blob/master/build-logic/build-update-utils/src/main/kotlin/gradlebuild.wrapper.gradle.kts

2023-01-03 08:36 UTC, reinsch82 commented
@eskatos just did 
- #23369

should I create an issue for the custom wrapper adaption?

2023-01-03 08:53 UTC, eskatos commented
Thanks!

A direct PR changing our build logic would be fine for our custom wrapper tasks.