Documentation updates
gradle/gradle pull request #23241
Opened 2022-12-20 16:09 UTC by ljacomet

* Fix Groovy update note
* Add note about secrets and CC

2022-12-20 16:28 UTC, abstratt approved these changes
Thanks for doing this

2022-12-20 16:56 UTC, xaviarias approved these changes

2022-12-20 18:33 UTC, bamboo requested changes

2022-12-20 18:33 UTC, bamboo commented on subprojects/docs/src/docs/userguide/running-builds/configuration_cache.adoc
> +This is a temporary situation that will be resolved before making the configuration cache stable.
I wouldn't couple the resolution of this issue to _making the configuration cache stable_.

2022-12-21 17:17 UTC, ljacomet commented
@bot-gradle test and merge

2022-12-21 17:41 UTC, merged