introduce RegularFileProperty for output in WriteProperties Task
gradle/gradle pull request #23313
Opened 2022-12-27 16:14 UTC by reinsch82

- resolves: #13363

Signed-off-by: Reinhold Degenfellner <rdegenfellner@gradle.com>

2023-01-03 12:54 UTC, reinsch82 commented
@bot-gradle test this

2023-01-03 13:04 UTC, eskatos requested changes

2023-01-03 13:04 UTC, eskatos commented on subprojects/core/src/main/java/org/gradle/api/tasks/WriteProperties.java
> +        return null;
:x: This introduce a disconnected new property. You should instead have the old one delegates to the new one. e.g.
```suggestion
        return destinationFile.getAsFile().getOrNull();
```

and have the setter for `outputFile` actually call `destinationFile.set(...)`.

2023-01-03 14:13 UTC, reinsch82 commented
@bot-gradle test this

2023-01-03 15:13 UTC, eskatos approved these changes
LGTM! :+1:

2023-01-04 03:16 UTC, reinsch82 commented
@bot-gradle test this

2023-01-04 03:37 UTC, reinsch82 commented
@bot-gradle test this

2023-01-04 04:03 UTC, reinsch82 commented
@bot-gradle test this

2023-01-04 06:00 UTC, reinsch82 commented
@bot-gradle test this

2023-01-04 06:39 UTC, reinsch82 commented
@bot-gradle clean

2023-01-04 06:40 UTC, reinsch82 commented
@bot-gradle test this

2023-01-04 07:38 UTC, reinsch82 commented
@bot-gradle test this

2023-01-04 09:17 UTC, eskatos requested changes
Morning brain works better for reviews. I requested more changes to make this correct.

2023-01-04 09:17 UTC, eskatos commented on subprojects/core/src/integTest/groovy/org/gradle/api/tasks/WritePropertiesIntegrationTest.groovy
> +            "Please use the destinationFile property instead. See https://docs.gradle.org/current/dsl/org.gradle.api.tasks.WriteProperties_Decorated.html#org.gradle.api.tasks.WriteProperties_Decorate
:x: The documentation link is invalid. It should point to `https://docs.gradle.org/current/dsl/org.gradle.api.tasks.WriteProperties.html` without the `_Decorated`

2023-01-04 09:17 UTC, eskatos commented on subprojects/core/src/main/java/org/gradle/api/tasks/WriteProperties.java
> +            .nagUser();
:x: fix the link, see comment above, and extract deprecation logging in a common function

2023-01-04 09:17 UTC, eskatos commented on subprojects/core/src/main/java/org/gradle/api/tasks/WriteProperties.java
> +        this.getDestinationFile().set(getServices().get(FileOperations.class).file(outputFile));
:lipstick: unnecessary `this`
```suggestion
        getDestinationFile().set(getServices().get(FileOperations.class).file(outputFile));
```

2023-01-04 09:17 UTC, eskatos commented on subprojects/core/src/main/java/org/gradle/api/tasks/WriteProperties.java
> +    }
:x: This is unnecessary and will trigger the deprecation warning even if one doesn't use the deprecated property.
It should simply be `getDestinationFile().getAsFile().get();`

2023-01-04 09:17 UTC, eskatos commented on subprojects/core/src/main/java/org/gradle/api/tasks/WriteProperties.java
> +    @Optional
:x: The output is already tracked by `destinationFile` this should be made internal
```suggestion
    @Internal
```

2023-01-04 12:27 UTC, reinsch82 commented
@bot-gradle test this

2023-01-04 12:47 UTC, eskatos requested changes
Code looks good :+1: 

The DSL reference should be edited to add the new property.
This can be done in `subprojects/docs/src/docs/dsl/org.gradle.api.tasks.WriteProperties.xml`.

2023-01-04 13:26 UTC, reinsch82 commented
@bot-gradle this BD

2023-01-04 13:35 UTC, reinsch82 commented
@bot-gradle test BD

2023-01-04 14:06 UTC, eskatos approved these changes
:+1:

2023-01-04 14:11 UTC, reinsch82 commented
@bot-gradle test and merge

2023-01-04 18:59 UTC, reinsch82 commented
@bot-gradle test and merge

2023-01-04 20:13 UTC, merged