Add ExampleSelfLinkProcessor to asciidoctor enabling documentation samples linking
gradle/gradle pull request #23389
Opened 2023-01-04 14:33 UTC by ajordanow

Added asciidoctor processor that automatically creates self-links to named example blocks. This allows sharing URLs pointing directly at a particular example.

2023-01-04 15:18 UTC, ajordanow commented
This is an example how linking to the examples looks like:

![image](https://user-images.githubusercontent.com/1017775/209170335-0f5a3a35-b044-4c0f-9491-22e278588300.png)

2023-01-04 15:47 UTC, alllex requested changes
Apart from minor syntactical things, I think this is already looking great!

One thing that I would still do is tweak the styling of the generated links within the example titles. I would make them look and behave like headings: no font changes by default compared to what was before, and on hover only the cursor changes to pointer.

I believe the CSS changes should go here:
https://github.com/gradle/gradle/blob/c634cf72c37abceec2e8c136b5c718074f57534b/subprojects/docs/src/docs/css/manual.css#L1102-L1104

Right now it looks like this:
![image](https://user-images.githubusercontent.com/2759152/210593897-d772ca8e-9014-40e0-adff-1ca9533cb91e.png)

2023-01-04 15:47 UTC, alllex commented on subprojects/docs-asciidoctor-extensions-base/src/test/groovy/org/gradle/docs/asciidoctor/IdGeneratorTest.groovy
> +        source | id
🧐 We usually format these data tables, such that column-separator lines are aligned. Reformatting the file in the IDE should do the trick.

2023-01-04 15:47 UTC, alllex commented on subprojects/docs-asciidoctor-extensions-base/src/main/java/org/gradle/docs/asciidoctor/IdGenerator.java
> +
🧐 nitpick: I would remove those empty lines

2023-01-04 15:47 UTC, alllex commented on subprojects/docs-asciidoctor-extensions-base/src/test/groovy/org/gradle/docs/asciidoctor/ExampleSelfLinkProcessorTest.groovy
> +
nitpick: extra newline

2023-01-04 15:47 UTC, alllex commented on subprojects/docs-asciidoctor-extensions-base/src/main/java/org/gradle/docs/asciidoctor/ExampleSelfLinkProcessor.java
> +
nitpick: extra newlines

2023-01-05 10:28 UTC, ajordanow commented
I've amended the code accordingly. Now the title looks like this: 
<img width="411" alt="image" src="https://user-images.githubusercontent.com/1017775/210758831-53ee7918-db36-41ef-8a8b-d84c9fe5d73e.png">

2023-01-05 10:29 UTC, ajordanow commented on subprojects/docs/src/docs/css/manual.css
> -    color: #06A0CE;
I'm aware this probably shouldn't be here but my IDE insisted ;)

2023-01-05 10:58 UTC, alllex approved these changes
LGTM!

There are some example titles that are the same, sometimes even on the same page, like here:
https://github.com/gradle/gradle/blob/1a809ef6adada1b48623422a54127491885e0226/subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/platforms.adoc#L130

I don't think we should fix this in the current PR. We can either do a follow up, or defer this to the time when those parts of the documentation are updated the next time.

Overall, I think this is already an amazing improvement for working with Gradle docs 👍

2023-01-05 11:24 UTC, ajordanow commented
> There are some example titles that are the same, sometimes even on the same page, like here:

You're right. I've left this as-is so far, as this is something that potentially involves more invasive changes. I'd opt for having unique example names though - their meaning is like section names. They should be distinctive.

From the implementation perspective - having unique links for examples with the same title would be hard. It needs page-wise state preservation and currently this kind of support is deep inside the asciidoctor internals.

2023-01-05 11:24 UTC, ajordanow commented
@bot-gradle test and merge

2023-01-07 00:51 UTC, big-guy commented
@bot-gradle test and merge

2023-01-07 00:51 UTC, big-guy commented
@bot-gradle test and merge

2023-01-07 04:53 UTC, merged