Empty snippet JARs and update versions
gradle/gradle pull request #23403
Opened 2023-01-05 11:11 UTC by xaviarias

Updated versions just in case Gradle Enterprise checks the filename and not only the contents.

See #23378

2023-01-05 11:12 UTC, xaviarias commented
@bot-gradle

2023-01-05 11:14 UTC, eskatos commented
I wonder if we shouldn't instead use fake library names to prevent the same issue to happen in the future.
Something like `utility-library-1.0.jar` and `awesome-framework-2.0.jar`.

2023-01-05 11:39 UTC, eskatos requested changes

2023-01-05 11:39 UTC, eskatos commented on subprojects/docs/src/snippets/antMigration/fileDeps/groovy/build.gradle
> +    implementation ':log4j-core:2.19.0', ':commons-io:2.11.0'  // <3>
:x: still uses the old jar names
```suggestion
    implementation ':awesome-framework:2.0'  // <3>
    implementation ':utility-library:1.0'  // <3>
```
BTW I moved this to two lines so it is aligned with the Kotlin snippet.

2023-01-05 11:39 UTC, eskatos commented on subprojects/docs/src/snippets/antMigration/fileDeps/kotlin/build.gradle.kts
> +    implementation(":commons-io:2.11.0")  // <3>
:x: still uses the old jar names

```suggestion
    implementation(":awesome-framework:2.0")     // <3>
    implementation(":utility-library:1.0")  // <3>
```

2023-01-05 12:24 UTC, eskatos commented
@bot-gradle test BD

2023-01-05 12:27 UTC, eskatos commented
Manually triggered a build given the bot is on strike
https://builds.gradle.org/buildConfiguration/Gradle_Release_Check_BuildDistributions/60113441?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

2023-01-05 13:30 UTC, eskatos commented
@xaviarias the changeset is wrong since you changed the target branch, please rebase your commits on top of `release`

2023-01-05 15:44 UTC, xaviarias commented
> @xaviarias the changeset is wrong since you changed the target branch, please rebase your commits on top of `release`

@eskatos  I'd rather cherry pick is it ok?

2023-01-05 15:53 UTC, eskatos commented
Do as you see fit

2023-01-06 11:28 UTC, eskatos commented
* superseded by https://github.com/gradle/gradle/pull/23424

2023-01-06 11:28 UTC, closed without merging