Document incremental change reporting behavior when discaring path information
gradle/gradle pull request #23462
Opened 2023-01-10 12:42 UTC by lptr

When using `@PathSensitive(PathSensitivity.NONE)` or `@Classpath` on an incremental input, Gradle will not report `MODIFIED` events, but instead will produce a pair of an `ADDED` and a `REMOVED` event, since there is no identity to connect the old state and the new.

2023-01-10 13:53 UTC, wolfs requested changes

2023-01-10 13:53 UTC, wolfs commented on subprojects/core-api/src/main/java/org/gradle/api/tasks/CompileClasspath.java
> + *     {@link org.gradle.work.ChangeType#MODIFIED} events.
❌ This is not true. If possible, we try to identify elements on classpath inputs via the absolute path to produce modified events. So if, for example, a project JAR changes, we report it as `MODIFIED`. For external dependencies, that doesn't work, though.

See for example this test: https://github.com/gradle/gradle/blob/9bd595ea31b56b19fd2487c928dd37b201c3eb05/subprojects/execution/src/test/groovy/org/gradle/internal/execution/history/changes/ClasspathCompareStrategyTest.groovy#L72-L78

2023-01-25 17:04 UTC, wolfs approved these changes
LGTM!

2023-01-26 09:19 UTC, lptr commented
@bot-gradle test and merge please.

2023-01-26 10:25 UTC, merged