Updates asciidoctor used in Gradle build to version 4.0.0-alpha.1
gradle/gradle pull request #23508
Opened 2023-01-12 14:13 UTC by tresat

This will allow the Gradle build to benefit from configuration cache compatibility.

2023-01-12 14:28 UTC, eskatos requested changes
I'm going to try locally to see if we can declare more tasks compatible with CC on our build

2023-01-12 14:28 UTC, eskatos commented on gradle/verification-metadata.xml
> +            <sha256 value="59281a4861a380148bfb9924abcb1287bccdb6484955ac447577cf8bde17eefc" origin="Generated by Gradle"/>
:x: The `origin` should be updated, even better would be adding a `reason`. See the comments at the beginning of this file.

2023-01-12 14:33 UTC, eskatos commented
It doesn't help much yet, see
* https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/564#issuecomment-1380450159

I guess we should then wait for another version

2023-02-03 01:14 UTC, big-guy commented
@tresat We should take this out of 8.1

2024-03-20 09:43 UTC, ov7a commented
Closing this as obsolete. See
* #27839

2024-03-20 09:43 UTC, closed without merging