Use 17 for toolchain tests
gradle/gradle pull request #23561
Opened 2023-01-17 13:03 UTC by reinsch82

This version is available on every architecture and OS we test. Specifically MacOS aarch64 was causing a problem here.

- #23554

2023-01-17 14:17 UTC, reinsch82 commented
@bot-gradle test this

2023-01-18 07:32 UTC, jbartok requested changes
Should be good, but pls. take care of the other failing test too.

2023-01-18 08:23 UTC, jbartok approved these changes

2023-01-18 08:23 UTC, reinsch82 commented
@bot-gradle test and merge

2023-01-18 10:14 UTC, merged

2023-01-19 09:05 UTC, blindpirate commented
@bot-gradle help

2023-01-19 09:08 UTC, blindpirate commented
@bot-gradle help