Remove unnecessary inner interface and improve javadoc on local plugin resolution types
gradle/gradle pull request #23594
Opened 2023-01-19 21:16 UTC by tresat

2023-01-19 21:16 UTC, tresat commented
@bot-gradle test this

2023-01-19 21:54 UTC, tresat commented
@bot-gradle test this

2023-01-20 14:05 UTC, tresat commented
@bot-gradle test this

2023-01-20 14:37 UTC, tresat commented
@bot-gradle test this

2023-01-31 21:33 UTC, tresat commented
@bot-gradle test this

2023-02-07 23:16 UTC, big-guy requested changes
I think we should abandon this. It looks like a time sink to figure out how to make this better for local plugin resolution.

2023-02-07 23:16 UTC, big-guy commented on subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/plugins/PluginBuildsIntegrationTest.groovy
> +    def "multiple included plugin builds which each include a library build with the same name works with #dsl dsl"() {
I'm not sure if this is testing anything in particular.  The `lib`s are identical, so if we were getting the "wrong" one, you wouldn't notice.

2023-02-07 23:16 UTC, big-guy commented on subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/plugins/AbstractPluginBuildIntegrationTest.groovy
> +        PluginBuildFixture(String rootDir, String buildName, boolean useKotlinDSL) {
I don't think this is a good idea.  We have other fixtures that do something like this and the String concatenation makes it hard to follow what paths are being used. 

Maybe something like `TestFile rootDir` could be used here. But we'd need to make other changes:
1. PluginBuildFixture would be made static
2. The default for rootDir would be the temporary test directory from the outer test
3. all calls to `file(...)` below would need to be `rootDir.file(...)`. This avoids the string concatenation problem.
4. There might be other changes that I haven't noticed

2023-02-07 23:16 UTC, big-guy commented on subprojects/composite-builds/src/integTest/groovy/org/gradle/integtests/composite/plugins/PluginBuildsIntegrationTest.groovy
> +        """
isn't this what the test fixture should already be doing?

oh, I think I see... libBuild1 has a plugin, but it's nested deeper.  pluginBuild1 has a plugin.

You're adding libBuild1 as another included build, which should have the same plugin id. I think this is a case where the test fixtures are doing us no favors.

2023-02-08 15:49 UTC, tresat commented
> I think we should abandon this. It looks like a time sink to figure out how to make this better for local plugin resolution.

OK. Abandoning.

2023-02-08 15:49 UTC, closed without merging