Improvements for `File`-related configuration inputs tracking
gradle/gradle pull request #23636
Opened 2023-01-24 11:59 UTC by h0tk3y

Related to https://github.com/gradle/gradle/pull/23266 (fixing https://github.com/gradle/gradle/issues/22656)

2023-01-26 15:03 UTC, mlopatkin requested changes
Looks pretty good! I have a few concerns about tests, though.

2023-01-26 15:03 UTC, mlopatkin commented on subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/GroovyPluginImplementation.groovy
> +                    if (!project.tasks.names.contains("thing")) {
I'm not sure if introducing discrepancies into plugin implementations is a good idea. Maybe we can get away with an ad hoc implementation of the template in the test itself? Then you can drop all unrelated checks for INSTANCE, etc.

2023-01-26 15:03 UTC, mlopatkin commented on subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/inputs/undeclared/UndeclaredFileInputsIntegrationTest.groovy
> +    @NotYetImplemented
I think we prefer to use `@ToBeImplemented` instead to test for a specific kind of failure.

2023-02-21 18:13 UTC, h0tk3y commented
@bot-gradle test and merge

2023-02-21 18:43 UTC, h0tk3y commented
@bot-gradle test and merge

2023-02-21 22:11 UTC, h0tk3y commented
@bot-gradle test and merge

2023-02-21 22:42 UTC, merged