sigushkin/call-interception-tools
gradle/gradle pull request #23925
Opened 2023-02-16 12:51 UTC by h0tk3y

Work-in-progress update to the instrumentation / call interception infrastructure.

2023-03-03 14:22 UTC, h0tk3y commented
@bot-gradle test RFN

2023-03-03 18:31 UTC, bamboo requested changes
I haven't reviewed the generators in detail yet, will do it in a second pass but overall this is looking really good.

2023-03-03 18:31 UTC, bamboo commented on subprojects/core/src/main/java/org/gradle/internal/classpath/declarations/GroovyFileInterceptors.java
> +    @StaticMethod(ofClass = ResourceGroovyMethods.class)
👍

2023-03-03 18:31 UTC, bamboo commented on subprojects/core/src/main/java/org/gradle/internal/classpath/declarations/KotlinFileExtensionsInterceptorsDeclaration.java
> +        return mask != 0 ?
The plot thickens. 👍

2023-03-03 18:31 UTC, bamboo commented on subprojects/internal-instrumentation-processor/src/main/java/org/gradle/internal/instrumentation/model/CallableKindInfo.java
> +    public static CallableKindInfo fromAnnotation(Annotation annotation) {
👍

2023-03-03 21:33 UTC, h0tk3y commented
@bot-gradle test RFN

2023-03-04 00:11 UTC, h0tk3y commented
@bot-gradle test RFN

2023-03-04 03:17 UTC, h0tk3y commented
I have updated this PR to include only the changes in interceptors but not the tool itself.
The PR for the tool is https://github.com/gradle/gradle/pull/24152

2023-03-04 04:44 UTC, h0tk3y commented on subprojects/core/src/main/java/org/gradle/internal/classpath/FileUtils.java
> +                hasReadMode = true;
Fixed in [`9866fbc` (#23925)](https://github.com/gradle/gradle/pull/23925/commits/9866fbc27ebc36f51927ee338d2a8bf89a7baa6b)

2023-03-04 05:17 UTC, h0tk3y commented on subprojects/core/build.gradle.kts
> +tasks.withType(JavaCompile::class).named("compileJava") {
Fixed, thanks! It's in the other PR now.

2023-03-04 05:17 UTC, h0tk3y commented on subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java
> +        ).toArray(CallInterceptor[]::new)
Thanks! Fixed it in the other PR.

2023-03-04 05:18 UTC, h0tk3y commented on subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java
> +
✅

2023-03-04 05:18 UTC, h0tk3y commented on subprojects/internal-instrumentation-processor/src/main/java/org/gradle/internal/instrumentation/processor/modelreader/impl/AnnotationCallInterceptionRequestReaderImpl.java
> +    ).toArray(Class[]::new));
Ah, indeed! Fixed it in the other PR, thanks!

2023-03-04 05:18 UTC, h0tk3y commented on subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java
> +            Class<?> generatedClass = Class.forName(InterceptorDeclaration.GROOVY_INTERCEPTORS_GENERATED_CLASS_NAME);
Yes, it should be simple. I'll do that.

2023-03-04 05:23 UTC, h0tk3y commented on subprojects/core/src/main/java/org/gradle/internal/classpath/declarations/FileInterceptorsDeclaration.java
> +        @CallerClassName String consumer
Yes, it should be absolutely doable with some support in our bytecode visitors.

2023-03-04 07:02 UTC, h0tk3y commented on subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java
> +            Class<?> generatedClass = Class.forName(InterceptorDeclaration.GROOVY_INTERCEPTORS_GENERATED_CLASS_NAME);
Done in the other PR.

2023-03-04 14:23 UTC, h0tk3y commented
@bot-gradle test RFN

2023-03-04 21:33 UTC, h0tk3y commented
@bot-gradle test RFN

2023-03-05 18:14 UTC, mlopatkin approved these changes
Awesome!

2023-03-09 05:43 UTC, h0tk3y commented
See the other PR that includes these changes now: https://github.com/gradle/gradle/pull/24165

2023-03-09 05:43 UTC, closed without merging