Reduce OutputEventRenderer.onOutput() locking by refine lock granularity
gradle/gradle pull request #23920
Opened 2023-02-16 08:27 UTC by TheDadda

Fixes #23919 

I try to reduce locking by refine lock granularity, remove OutputEventRenderer.lock invoked by onOutput() and add synchronization logics to OutputEventTransformer class. Lock waiting counts reduced from 50,0000 to 3k, and it can save about 4s - 6s.

2023-02-23 10:14 UTC, eskatos commented
@bot-gradle test RFM, APT

2023-02-24 03:52 UTC, TheDadda commented
i just rebase the latest origin/master branch, and remove 'unused imports' reported by ci

2023-02-24 04:03 UTC, TheDadda commented
@bot-gradle test RFM, APT

2023-02-24 08:54 UTC, ljacomet commented
@bot-gradle test RFM, APT

2023-02-24 12:00 UTC, TheDadda commented
It seems that the master branch has been protected, shall i change the target branch and create another merge request?

![image](https://user-images.githubusercontent.com/125425242/221173625-b16ad5b3-49d1-4a58-b676-95d6e056cd1a.png)

2023-02-24 15:28 UTC, ljacomet commented
No need, we use a bot to do the merge.

2023-02-27 16:28 UTC, ljacomet requested changes
I think reducing the lock scope is a good idea. And since collections in `OutputEventTransformer` are not ordered, doing some handling out of order seems OK.

But there is a lock correctness issue introduced IMO, see below:

2023-02-27 16:28 UTC, ljacomet commented on subprojects/logging/src/main/java/org/gradle/internal/logging/sink/OutputEventTransformer.java
> +    private synchronized void invokeListener(OutputEvent event) {
Looking at the changes more in detail, this does not seem correct.

The synchronization is not on the same `lock` object as in `OutputEventRenderer`.

You should pass the `lock` instance from that type in this type and synchronize on it to restore the behavior.

2023-02-28 10:29 UTC, ljacomet approved these changes
LGTM!

Thanks for following up on the change request.

2023-02-28 10:29 UTC, ljacomet commented
@bot-gradle test RfR

2023-02-28 14:32 UTC, ljacomet commented
Test failures are flaky tests, looks like this is good to go

2023-02-28 14:32 UTC, ljacomet commented
@bot-gradle test and merge

2023-03-01 03:39 UTC, blindpirate commented
@bot-gradle test and merge

2023-03-01 08:08 UTC, merged