Add Plugin Publish plugin changes to the upgrade guide
gradle/gradle pull request #24486
Opened 2023-03-24 13:08 UTC by jbartok

* Mitigates https://github.com/gradle/gradle/issues/24458

2023-03-24 13:37 UTC, ljacomet requested changes

2023-03-24 16:34 UTC, ljacomet commented on subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
> +These versions of the plugin no longer add the `pluginBundle` extension.
I think the phrasing can be clarified, but it says that: with Gradle 8+, the `pluginBundle` extension is no longer registered.
So yes, it works in 7.x (and should log a deprecation warning) but it no longer does in 8.

2023-03-28 09:13 UTC, jbartok commented on subprojects/docs/src/docs/userguide/migration/upgrading_version_7.adoc
> +These versions of the plugin no longer add the `pluginBundle` extension.
You should hear how bad it sounds out loud, with my easter-European accent! Will rephrase ...

2023-03-28 09:34 UTC, eskatos approved these changes

2023-03-28 09:35 UTC, eskatos commented
@bot-gradle test and merge

2023-03-28 10:30 UTC, merged