Add more explanation for empty test set
gradle/gradle pull request #24528
Opened 2023-03-28 06:34 UTC by reinsch82

2023-03-28 14:55 UTC, donat requested changes

2023-03-28 14:55 UTC, donat commented on subprojects/tooling-api/readme.md
> +The preconditions will also end up in the same message if the filter all the tests.
```suggestion
The preconditions will also end up in the same message if it filters all tests.
```

2023-03-28 14:55 UTC, donat commented on subprojects/tooling-api/readme.md
> +This is due to the fact that Gradle 4.6 and older don't support Java 11 and newer, which is checked before filter is applied.
```suggestion
This is due to the fact that Gradle 4.6 and older don't support Java 11 and newer, which is checked before the test filter is applied.
```

2023-03-29 08:31 UTC, donat approved these changes

2023-03-29 08:33 UTC, reinsch82 commented
@bot-gradle test and merge

2023-03-29 10:24 UTC, merged