Add doc for --validate-only flag for publishPlugins task
gradle/gradle pull request #24671
Opened 2023-04-06 12:40 UTC by ov7a

refs #23908

2023-04-06 12:51 UTC, jbartok commented on subprojects/docs/src/docs/userguide/developing-plugins/publishing_gradle_plugins.adoc
> +You can validate your plugins before actually publishing them using `--validate-only` flag:
```suggestion
You can validate your plugins before actually publishing them using the `--validate-only` flag:
```

2023-04-06 12:51 UTC, jbartok approved these changes

2023-04-07 14:54 UTC, ljacomet requested changes
Thanks, I like the release notes.

But I believe the two remarks below would improve them further:

2023-04-07 14:54 UTC, ljacomet commented on subprojects/docs/src/docs/release/notes.md
> +### Plugin publishing
```suggestion
### Plugin publishing to the Gradle Plugin Portal
```

2023-04-07 14:54 UTC, ljacomet commented on subprojects/docs/src/docs/release/notes.md
> +
And I would add a general link to the documentation here.

2023-04-07 14:56 UTC, ljacomet commented on subprojects/docs/src/docs/release/notes.md
> +
And mention that these require version `1.2.0` of the plugin.

2023-04-07 15:25 UTC, ljacomet requested changes
Your release notes mixes the portal and the plugin.

See proposal:

2023-04-07 15:25 UTC, ljacomet commented on subprojects/docs/src/docs/release/notes.md
> +Version [1.2.0](https://plugins.gradle.org/plugin/com.gradle.plugin-publish/1.2.0) of the [Gradle Plugin Portal](https://plugins.gradle.org/) is now available.
```suggestion
Version [1.2.0](https://plugins.gradle.org/plugin/com.gradle.plugin-publish/1.2.0) of the `com.gradle.plugin-publish` plugin is now available.
It is required to benefit from the features and bugfixes listed below.

See [documentation](userguide/publishing_gradle_plugins.html) for more details.
```

2023-04-07 15:34 UTC, ljacomet commented
@bot-gradle test and merge

2023-04-07 16:16 UTC, merged