Rdegenfellner/24567/unify formatting for suggesting gradle documentation
gradle/gradle pull request #24750
Opened 2023-04-13 14:23 UTC by reinsch82

- Fixes #24567

2023-04-19 06:33 UTC, reinsch82 commented
@bot-gradle test this

2023-04-19 07:40 UTC, reinsch82 commented
@bot-gradle test this

2023-04-19 07:55 UTC, reinsch82 commented
@bot-gradle test this

2023-04-19 09:33 UTC, reinsch82 commented
@bot-gradle test this

2023-04-19 10:50 UTC, reinsch82 commented
@bot-gradle test this

2023-04-19 12:37 UTC, reinsch82 commented
@bot-gradle test RFN

2023-04-19 13:03 UTC, reinsch82 commented
@bot-gradle test this

2023-04-19 13:05 UTC, reinsch82 commented
@bot-gradle test this

2023-04-19 14:12 UTC, tresat reviewed
Didn't review the whole thing, but left a couple quick suggestions.

2023-04-19 14:12 UTC, tresat commented on subprojects/logging/src/main/java/org/gradle/api/internal/DocumentationRegistry.java
> +        return String.format("Learn more about Gradle by exploring Samples at %s", getSampleFor(id));
The here is slightly imperative, but in the same way that “Run with --stacktrace”, or “Consult the upgrade guide” etc. is.  I don’t think anyone would find it too condescending.

You could soften it a little by saying “To learn more about” if you wanted.  You should also definitely say “exploring the Samples” or “exploring our Samples”.

2023-04-19 14:55 UTC, donat requested changes
It looks really good!
I've spotted a few minor things, ptal.

2023-04-19 14:55 UTC, donat commented on subprojects/integ-test/src/integTest/groovy/org/gradle/integtests/ParallelStaleOutputIntegrationTest.groovy
> +    private getDocLinkMessage() {
```suggestion
    private def getDocLinkMessage() {
```

2023-04-19 14:55 UTC, donat commented on subprojects/launcher/src/main/java/org/gradle/launcher/cli/DebugLoggerWarningAction.java
> +        "\n"+
🧐 
```suggestion
        "\n" +
```

2023-04-20 05:36 UTC, reinsch82 commented
@bot-gradle test this

2023-04-20 05:52 UTC, reinsch82 commented
@bot-gradle test this

2023-04-20 05:52 UTC, reinsch82 commented
@bot-gradle clean

2023-04-20 12:01 UTC, reinsch82 commented
@bot-gradle test and merge

2023-04-20 13:54 UTC, merged