Introduce test task option to fail if there is no test
gradle/gradle pull request #24786
Opened 2023-04-17 15:05 UTC by FrauBoes

wip

* Rename to fail-on-no-test
* Make property abstract
* Drop deprecation
* Add documentation

Fixes https://github.com/gradle/gradle/issues/7452

### Context

2023-04-17 15:06 UTC, FrauBoes commented
@bot-gradle test this

2023-04-18 08:11 UTC, FrauBoes commented
@bot-gradle test this

2023-04-18 12:08 UTC, FrauBoes commented
@bot-gradle test this

2023-04-18 13:44 UTC, FrauBoes commented
@bot-gradle help

2023-04-18 13:44 UTC, FrauBoes commented
@bot-gradle clean

2023-04-18 13:44 UTC, FrauBoes commented
@bot-gradle test this

2023-04-18 14:06 UTC, eskatos approved these changes
Nice and tidy!

I agree that merging this first without deprecation is a good idea.
We should then discuss what to do next.

2023-04-18 18:15 UTC, ghale commented
So my initial reaction to this is to wonder whether this is fundamentally different than [TestFilter::isFailOnNoMatchingTests](https://github.com/gradle/gradle/blob/8db9012a4754bc236700be78b43b5172d9d2aa4e/subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/TestFilter.java#L156).  What I mean is, whether you have a filter or not, you're basically saying that the task should fail if no tests execute.  If there are no tests to execute, then no filters would match either (i.e. there are no cases where tests don't exist, but filters match).  If there are tests to execute, then it _is_ possible that the filters don't match.  So, is it a reasonable thing to want the build to fail if there are no tests to execute, but not to fail if tests exist, but none of them match the filters?  My gut feeling is that noone would really want this.  If not, then I think you either want both of these or neither of these, exclusively.

Another question that comes to mind is whether a command-line option is an appropriate way to express this.  This feels more like something that you would want to implement for all projects in a multiproject build or through a convention plugin (i.e. to catch when a new project is added and misconfigured).  You might also have projects in the build where it is "normal" to have no tests (for instance, a library of 100% generated sources).  A build-wide, single-invocation option would not fit those scenarios very well.  I wonder if a project or task-specific option might be more useful?

Did you consider making this a public api option on the `Test` task instead and just deprecating the option on the test filter?  That would allow the check to be disabled on tasks that it should not apply to (i.e. the generated sources use case), and would generalize the filter option such that it could be used with or without a filter.

2023-04-19 07:47 UTC, FrauBoes commented
> So my initial reaction to this is to wonder whether this is fundamentally different than [TestFilter::isFailOnNoMatchingTests](https://github.com/gradle/gradle/blob/8db9012a4754bc236700be78b43b5172d9d2aa4e/subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/TestFilter.java#L156). What I mean is, whether you have a filter or not, you're basically saying that the task should fail if no tests execute. If there are no tests to execute, then no filters would match either (i.e. there are no cases where tests don't exist, but filters match). If there are tests to execute, then it _is_ possible that the filters don't match. So, is it a reasonable thing to want the build to fail if there are no tests to execute, but not to fail if tests exist, but none of them match the filters? My gut feeling is that noone would really want this. If not, then I think you either want both of these or neither of these, exclusively.

I agree that `test --fail-on-no-test` is a more general way of expressing the intent of the `isFailOnNoMatchingTests` test filter, and that using the former makes the latter superfluous. Unless there are use cases I can’t think of right now?

> Another question that comes to mind is whether a command-line option is an appropriate way to express this. This feels more like something that you would want to implement for all projects in a multiproject build or through a convention plugin (i.e. to catch when a new project is added and misconfigured). You might also have projects in the build where it is "normal" to have no tests (for instance, a library of 100% generated sources). A build-wide, single-invocation option would not fit those scenarios very well. I wonder if a project or task-specific option might be more useful?

The `failOnNoTest` property on `Test` can be configured in the build script like this:
```
test {
  failOnNoTest = true
}
```
Is that what you mean?

> Did you consider making this a public api option on the `Test` task instead and just deprecating the option on the test filter? That would allow the check to be disabled on tasks that it should not apply to (i.e. the generated sources use case), and would generalize the filter option such that it could be used with or without a filter.

This change introduces a public api option on `Test`, see above. `failOnNoTest` is set to `false` by default. We could indeed decide to deprecate `isFailOnNoMatchingTests`. This could be a follow-up.

@ghale

2023-04-19 11:54 UTC, ghale requested changes
> Is that what you mean?

Yes, that's what I was referring to.  I didn't look closely enough.  I saw the package-private method on `AbstractTestTask` and didn't see any tests for this, so I assumed this was not public.  I think we should add some tests for configuring this through the API and add the new property to `docs/src/docs/dsl/org.gradle.api.tasks.testing.Test.xml` so that it shows up in the dsl reference.

I think we should deprecate the filter property, too.  However you want to handle it - either as part of this PR or in a follow up PR.

Good stuff.  Thanks for adding this.

2023-04-20 07:46 UTC, FrauBoes commented
After further discussion, we decided that “success on no test to execute” should be deprecated. The test task should fail when no test was executed, because running the test task with no test to execute is typically caused by some misconfiguration, which you might miss if the test task succeeds.

Note that "no test to execute" is different to "no test present". The former means there are test sources present, but they are not run (for example because of a missing test annotation or a different test framework). The latter means there are no test sources present, in which case the test task is skipped.

No test task option will be introduced right now as there doesn't seem to be a use case for reverting to “success on no test to execute”. This being said, if it turns out there are valid use cases, we can introduce the task option at a later point.

2023-04-20 07:46 UTC, closed without merging