Deprecate `project.buildDir`
gradle/gradle pull request #24820
Opened 2023-04-19 15:27 UTC by ljacomet

2023-04-19 15:43 UTC, jvandort commented
Will we be doing the same for `Project#getProjectDir`?

2023-04-19 15:46 UTC, ljacomet commented
Certainly not in this PR. But I am not sure generally. That property is read-only and so less of an issue.

2023-04-19 15:52 UTC, ljacomet commented
@bot-gradle test this

2023-04-21 16:02 UTC, ljacomet commented
@bot-gradle test this

2023-06-09 09:56 UTC, ljacomet commented
@bot-gradle test this

2023-06-22 15:24 UTC, jvandort commented
A related question, why is the build dir location configurable at all? Are there use cases for changing it?

2023-06-28 09:43 UTC, ljacomet commented
Yes, there are use cases. One is not having any build produced files inside your project source tree.

2023-06-28 09:43 UTC, ljacomet commented
@bot-gradle test this

2023-06-29 10:28 UTC, ljacomet commented
@bot-gradle test this

2023-06-29 15:37 UTC, ljacomet commented
@bot-gradle test RfR

2023-07-06 08:50 UTC, ljacomet commented
Looks like RfR is really unstable for now.

Let's see if this would pass nightly at least

2023-07-06 08:50 UTC, ljacomet commented
@bot-gradle test RfN

2023-07-06 10:03 UTC, ljacomet commented
@bot-gradle test RfN

2023-07-06 10:21 UTC, ov7a requested changes
While code changes are ok, I think this change should be reflected in the release notes and documentation with a detailed explanation of the reasons behind this change.

2023-07-06 10:28 UTC, eskatos approved these changes

2023-07-06 10:28 UTC, eskatos commented on subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/delegates/ProjectDelegate.kt
>          delegate.buildDir
❔ Can't the deprecation suppression be reduced to the call to the delegate as in `setBuildDir` below?

```suggestion
    @Deprecated("Use layout.buildDirectory instead", ReplaceWith("layout.buildDirectory.get()"))
    override fun getBuildDir(): File =
        @Suppress("DEPRECATION")
        delegate.buildDir
```

2023-07-06 10:28 UTC, eskatos commented on subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/delegates/ProjectDelegate.kt
>          delegate.setBuildDir(path)
❔ Can't the deprecation suppression be reduced to the call to the delegate as in `setBuildDir` above?


```suggestion
    @Deprecated("Use layout.buildDirectory instead", ReplaceWith("layout.buildDirectory.get()"))
    override fun setBuildDir(path: Any) =
        @Suppress("DEPRECATION")
        delegate.setBuildDir(path)
```

2023-07-06 16:20 UTC, ljacomet commented
@ov7a I'll work on documenting these changes in a follow up PR. Note that as indicated on the issue, we will not start nagging users now.

2023-07-06 16:24 UTC, ljacomet commented
@bot-gradle test and merge

2023-07-06 16:38 UTC, lkasso approved these changes

2023-07-06 17:41 UTC, ov7a approved these changes

2023-07-06 21:34 UTC, merged