docs: Make the configuration avoidance API table more readable
gradle/gradle pull request #24847
Opened 2023-04-20 21:23 UTC by sschuberth

### Context

The current table at https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#sec:old_vs_new_configuration_api_overview is hard to read.

### Contributor Checklist

- [x] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [x] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [x] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [x] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [x] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [x] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [x] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Gradle Core Team Checklist

- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation

2023-04-20 21:25 UTC, sschuberth commented
Screenshot of the new layout:

![image](https://user-images.githubusercontent.com/349154/233491150-6fae1b00-5700-4a12-92d6-f6a17cbb8bdc.png)

2023-05-25 16:53 UTC, lkasso requested changes
Let's make the new table 3 columns and not just 2 to make it clearer to the user.
I started this change in the code review but you need to go ahead and finish making the changes to all table entires. Once you do, I will be able to merge it into master.

2023-05-25 16:53 UTC, lkasso commented on subprojects/docs/src/docs/userguide/extending-gradle/task_configuration_avoidance.adoc
>  [cols="a,a", options="header"]
```suggestion
[cols="a,a,a", options="header"]
```

2023-05-25 16:53 UTC, lkasso commented on subprojects/docs/src/docs/userguide/extending-gradle/task_configuration_avoidance.adoc
> +| New API
```suggestion
| New API
| Notes
```

2023-05-25 16:53 UTC, lkasso commented on subprojects/docs/src/docs/userguide/extending-gradle/task_configuration_avoidance.adoc
> +2+| There is not a shorthand Groovy DSL for using the new API.
```suggestion
| There is not a shorthand Groovy DSL for using the new API.
```

2023-05-25 16:53 UTC, lkasso commented on subprojects/docs/src/docs/userguide/extending-gradle/task_configuration_avoidance.adoc
> +2+| Use one of the alternatives below.
```suggestion
| Use one of the alternatives below.
```

2023-05-25 16:53 UTC, lkasso commented on subprojects/docs/src/docs/userguide/extending-gradle/task_configuration_avoidance.adoc
> +2+| Use one of the alternatives below.
```suggestion
| Use one of the alternatives below.
```

2023-05-25 16:53 UTC, lkasso commented on subprojects/docs/src/docs/userguide/extending-gradle/task_configuration_avoidance.adoc
> +2+| This returns a `TaskProvider` instead of a `Task`.
```suggestion
| This returns a `TaskProvider` instead of a `Task`.
```

2023-05-25 16:53 UTC, lkasso commented on subprojects/docs/src/docs/userguide/extending-gradle/task_configuration_avoidance.adoc
> +2+| This returns a `TaskProvider` instead of a `Task`.
```suggestion
| This returns a `TaskProvider` instead of a `Task`.
```

2023-05-25 16:53 UTC, lkasso commented on subprojects/docs/src/docs/userguide/extending-gradle/task_configuration_avoidance.adoc
> +2+| This returns a `TaskProvider` instead of a `Task`.
```suggestion
| This returns a `TaskProvider` instead of a `Task`.
```

2023-05-25 16:53 UTC, lkasso commented on subprojects/docs/src/docs/userguide/extending-gradle/task_configuration_avoidance.adoc
> +2+| This returns a `TaskProvider` instead of a `Task`.
```suggestion
| This returns a `TaskProvider` instead of a `Task`.
```

2023-05-25 16:53 UTC, lkasso commented on subprojects/docs/src/docs/userguide/extending-gradle/task_configuration_avoidance.adoc
> +2+| Accessing tasks from another project requires a specific ordering of project evaluation.
```suggestion
| Accessing tasks from another project requires a specific ordering of project evaluation.
```

2023-05-25 17:05 UTC, sschuberth commented
> Let's make the new table 3 columns and not just 2 to make it clearer to the user.

I've actually considered doing that, but deliberately decided against that for the following reasons:

- The table uses alternating background colors for rows. In my proposed layout, notes are always displayed in rows with a dimmed background, making them distinct from the "real deal rows" of comparing old vs new API.
- With 3 columns the table gets wider, resulting in wrapping of cell contents, making the table actually less readable IMO.

So I'd clearly prefer to stick to the proposed layout.

2023-06-06 21:34 UTC, lkasso commented
> > So I'd clearly prefer to stick to the proposed layout.
> 
> @lkasso does that make sense to you?

Hey @sschuberth, this makes sense, but I have two problems:
1. The table layout doesn't make sense for all items in the table. For example, when an entry is "This returns a TaskProvider instead of a Task." it doesn't immediately let the user which API is which.
2. Tables have to be the same format across the entire documentation, so I would have to change all the other tables as part of this PR as well. 

I agree the current doc is also confusing.

2023-07-19 08:52 UTC, sschuberth commented
Sorry for the late reply.

> 1. The table layout doesn't make sense for all items in the table. For example, when an entry is "This returns a TaskProvider instead of a Task." it doesn't immediately let the user know which API is which.

IMO this could be easily addressed by slightly rewording those sentences.

> Tables have to be the same format across the entire documentation

Frankly, that sounds like a ridiculous requirement... what's the rationale for that? Also, how does your proposal to use 3 columns fit to this requirement?

> Proposal to make it more readable:

What I still like better in my proposal is that all rows with notes get a different background color due to the alternating row colors assigned to all tables. I.e. everything with a dimmed background is less important as it's just a note.

On the other hand, when putting the same information into all rows, the background row color has no meaning anymore.

2023-07-20 16:01 UTC, lkasso commented
@sschuberth, let's go ahead and merge for now.
I can look into it when I go over this section later this year during my general doc review/update cycle.

2023-07-20 16:02 UTC, lkasso approved these changes

2023-07-20 16:02 UTC, lkasso commented
@bot-gradle test and merge

2023-07-20 18:51 UTC, merged