Expose buildTreePath on Project and ProjectComponentIdentifier
gradle/gradle pull request #24963
Opened 2023-05-02 15:22 UTC by donat

2023-05-03 07:20 UTC, donat commented
@bot-gradle test rFM

2023-05-17 15:02 UTC, reinsch82 approved these changes
LGTM

2023-05-17 15:56 UTC, wolfs requested changes
The API changes look good, though tests are missing, especially for ProjectComponentIdentifier.buildTreePath.

2023-05-24 08:59 UTC, donat commented on subprojects/core/src/test/groovy/org/gradle/api/internal/project/DefaultProjectStateRegistryTest.groovy
> +        root.componentIdentifier.buildTreePath == ":"
I've adjusted the tests you mentioned.

2023-05-24 09:21 UTC, wolfs approved these changes

2023-05-24 10:39 UTC, donat commented
@bot-gradle test and merge please

2023-05-24 11:36 UTC, merged