Fix ClassCastException in Eclipse WTP
gradle/gradle pull request #25058
Opened 2023-05-15 12:29 UTC by reinsch82

- #24967

2023-05-15 14:13 UTC, donat requested changes
LGTM. I have only one concern regarding test coverage.

2023-05-15 14:13 UTC, donat commented on subprojects/ide/src/integTest/groovy/org/gradle/plugins/ide/eclipse/EclipseWtpIntegrationTest.groovy
> +        when:
❌ Even though it's written in Groovy, this still seems like a JUnit test that does not have the `when:` and `then:` constructs.

2023-05-15 14:57 UTC, reinsch82 commented
@bot-gradle test this

2023-05-15 17:00 UTC, donat approved these changes

2023-05-16 05:45 UTC, reinsch82 commented
@bot-gradle test and merge

2023-05-16 06:42 UTC, merged