Document configuration cache instrumentation
gradle/gradle pull request #25286
Opened 2023-06-05 22:14 UTC by mlopatkin

Gradle's bytecode instrumentation can break self-checking JARs, so it has to be documented for users to know about the possibility. The Worker API is recommended as a workaround.

2023-06-05 22:14 UTC, mlopatkin commented
@bot-gradle test BD

2023-06-06 20:35 UTC, lkasso requested changes
Minor syntax/grammar changes requested.

2023-06-07 13:21 UTC, bamboo approved these changes
Good to have this documented 👍

2023-06-08 19:29 UTC, mlopatkin commented
@bot-gradle test and merge

2023-06-08 19:39 UTC, merged