TAPI memory improvements for 8.2
gradle/gradle pull request #25442
Opened 2023-06-20 16:43 UTC by 6hundreds

Cherrypick of https://github.com/gradle/gradle/pull/25267

2023-06-20 19:51 UTC, bamboo approved these changes

2023-06-21 06:08 UTC, eskatos commented
You mentioned missing cross version tests, I would be more confident with this change if these tests were added.

2023-06-21 16:07 UTC, 6hundreds commented
@bot-gradle test RFR

2023-06-21 16:17 UTC, donat requested changes
Review for the cross-version test.

2023-06-21 16:17 UTC, donat commented on subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r82/CustomToolingModelCrossVersionSpec.groovy
> +    def "older TAPI versions is not releasing memory during BuildAction"() {
```suggestion
    def "older Tooling API versions cannot free memory when executing a build action"() {
```

2023-06-21 16:17 UTC, donat commented on subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r82/CustomToolingModelCrossVersionSpec.groovy
> +    def "older TAPI versions is not releasing memory during BuildAction"() {
Please move the test to the top of the class. That way the sequence of tests are read like:
- this is a bug in old versions
- starting from Gradel 8.2, it is fixed

2023-06-21 16:17 UTC, donat commented on subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r82/CustomToolingModelCrossVersionSpec.groovy
> +        connection.action()
❓ Wouldn't this be sufficient?

```
connection.action(new FetchProjectsCustomModelsAction()).run();
```

2023-06-21 16:17 UTC, donat commented on subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r82/FetchProjectsCustomModelsAction.groovy
> +class FetchProjectsCustomModelsAction implements BuildAction {
```suggestion
class FetchProjectsCustomModelsAction implements BuildAction<Void> {
```

2023-06-21 16:17 UTC, donat commented on subprojects/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r82/FetchProjectsCustomModelsAction.groovy
> +        return 42
```suggestion
```

2023-06-21 16:31 UTC, 6hundreds commented
> Review for the cross-version test.

Applied your comments

2023-06-22 09:33 UTC, 6hundreds commented
@bot-gradle test RFR

2023-06-22 11:38 UTC, 6hundreds commented
@bot-gradle test RFR

2023-06-22 12:21 UTC, 6hundreds commented
@bot-gradle test this

2023-06-22 13:10 UTC, 6hundreds commented
@bot-gradle test RFR

2023-06-22 16:25 UTC, 6hundreds commented
@bot-gradle test and merge

2023-06-22 16:26 UTC, 6hundreds commented
@bot-gradle cancel

2023-06-22 16:27 UTC, 6hundreds commented
@bot-gradle test and merge

2023-06-22 17:50 UTC, merged