Add `ProjectIsolation` integration test executer
gradle/gradle pull request #25602
Opened 2023-07-04 11:25 UTC by 6hundreds

Fixes #25178

2023-07-04 11:26 UTC, 6hundreds commented
@bot-gradle test this

2023-07-06 22:17 UTC, bamboo requested changes
Let's keep using `IsolatedProjects` for symbols.

2023-07-06 22:17 UTC, bamboo commented on build-logic/basics/src/main/kotlin/gradlebuild/basics/testing/TestType.kt
> +    INTEGRATION("integ", listOf("embedded", "forking", "noDaemon", "parallel", "configCache", "projectIsolation")),
❌ "isolatedProjects"
```suggestion
    INTEGRATION("integ", listOf("embedded", "forking", "noDaemon", "parallel", "configCache", "isolatedProjects")),
```

2023-07-06 22:17 UTC, bamboo commented on subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleContextualExecuter.java
> +        projectIsolation(true);
```suggestion
        isolatedProjects(true);
```

2023-07-06 22:17 UTC, bamboo commented on subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleContextualExecuter.java
> +            case projectIsolation:
```suggestion
            case isolatedProjects:
```

2023-07-06 22:17 UTC, bamboo commented on subprojects/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/executer/GradleContextualExecuter.java
> +                return new ProjectIsolationGradleExecuter(getDistribution(), getTestDirectoryProvider(), gradleVersion, buildContext);
```suggestion
                return new IsolatedProjectsGradleExecuter(getDistribution(), getTestDirectoryProvider(), gradleVersion, buildContext);
```

2023-07-07 16:19 UTC, bamboo approved these changes
💯

2023-07-07 16:20 UTC, 6hundreds commented
@bot-gradle test and merge

2023-07-08 05:38 UTC, merged