~ Test keeping CC listeners in cache writing
gradle/gradle pull request #25622
Opened 2023-07-05 18:58 UTC by h0tk3y

2023-07-05 18:58 UTC, h0tk3y commented
@bot-gradle test RFN

2023-07-07 16:48 UTC, bamboo requested changes

2023-07-07 16:48 UTC, bamboo commented on subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/DefaultConfigurationCache.kt
> +        Instrumented.discardListener()
⚙️ This already happens in `doneWithWork` and could be removed from here.

2023-07-07 19:08 UTC, h0tk3y commented
@bot-gradle test RFR

2023-07-07 20:15 UTC, h0tk3y commented
@bot-gradle test RFR

2023-07-10 11:45 UTC, h0tk3y commented
@bot-gradle test RFN

2023-07-10 12:28 UTC, h0tk3y commented
@bot-gradle test RFN

2023-07-10 12:43 UTC, h0tk3y commented
@bot-gradle cancel

2023-07-10 12:43 UTC, h0tk3y commented
@bot-gradle test RFN

2023-07-10 14:52 UTC, h0tk3y commented
@bot-gradle test RFR

2023-07-10 17:53 UTC, h0tk3y commented
@bot-gradle test RFR

2023-07-11 12:22 UTC, bamboo approved these changes
💯 🎉

2023-07-11 12:22 UTC, bamboo commented on subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheInputListenerLifecycleIntegrationTest.groovy
> +        and: "a project that has a provider having undeclared configuration inputs, which is linked to a task"
👍

2023-07-11 12:22 UTC, bamboo commented on subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheInputListenerLifecycleIntegrationTest.groovy
> +        isOptOut | _
👍

2023-07-11 12:22 UTC, bamboo commented on subprojects/configuration-cache/src/integTest/groovy/org/gradle/configurationcache/ConfigurationCacheInputListenerLifecycleIntegrationTest.groovy
> +    def 'switching the opt-out flag should invalidate the configuration cache entry'() {
👍

2023-07-11 12:22 UTC, bamboo commented on subprojects/core/src/main/java/org/gradle/initialization/StartParameterBuildOptions.java
> +        public static final String PROPERTY_NAME = "org.gradle.configuration-cache.inputs.unsafe.ignore-in-serialization";
👍

2023-07-11 14:33 UTC, merged