Load JvmBytecodeCallInterceptor and CallInterceptor via SPI
gradle/gradle pull request #26015
Opened 2023-08-03 12:19 UTC by asodja

And load Property upgrades interceptors from plugins classloader.

That way we don't have classloading issues in adapter logic, where we reference plugin types.

Fixes https://github.com/gradle/gradle/issues/25893

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2023-08-03 13:23 UTC, asodja commented
@bot-gradle test this APT

2023-08-04 07:28 UTC, asodja commented
@bot-gradle clean

2023-08-04 07:58 UTC, asodja commented
@bot-gradle test this APT

2023-08-04 08:23 UTC, asodja commented
@bot-gradle test this

2023-08-04 08:46 UTC, asodja commented
@bot-gradle test APT

2023-08-04 10:22 UTC, asodja commented
@bot-gradle clean

2023-08-21 07:41 UTC, mlopatkin requested changes
Looks good to me overall, but I think the second init possibility is worth addressing.
I like how clean the discovery process looks now.

2023-08-21 08:37 UTC, asodja commented on subprojects/core/src/main/java/org/gradle/internal/classpath/GroovyCallInterceptorsProvider.java
> +            this(classLoader, "org.gradle");
Yes, basically because of test. We can remove package filtering for production case

2023-08-21 08:41 UTC, asodja commented on subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java
> +                return;
I had it as an error first. But I found that new instance of `DefaultClassLoaderRegistry` is created for some reason for Tooling API and tooling API tests breaks

2023-08-21 12:10 UTC, asodja commented
@bot-gradle test this

2023-08-21 12:14 UTC, asodja commented on subprojects/core/src/main/java/org/gradle/internal/classpath/JvmBytecodeInterceptorSet.java
> +import static org.gradle.internal.jvm.inspection.JavaInstallationRegistry.distinctByKey;
Good catch, I decided to just remove it and collect values to a map

2023-08-21 12:14 UTC, asodja commented on subprojects/core/src/test/groovy/org/gradle/internal/classpath/GroovyDynamicDispatchingInterceptingTest.groovy
> +
Removed

2023-08-21 12:14 UTC, asodja commented on subprojects/core/src/test/groovy/org/gradle/internal/classpath/InheritedMethodsInterceptionTest.groovy
> +
Removed

2023-08-21 12:14 UTC, asodja commented on subprojects/core/src/main/java/org/gradle/internal/classpath/GroovyCallInterceptorsProvider.java
> +            this(classLoader, "org.gradle");
Removed filtering

2023-08-21 12:16 UTC, asodja commented on subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java
> +                return;
Changed it and now we do a check per classloader

2023-08-22 07:48 UTC, mlopatkin approved these changes
lgtm!

2023-08-22 07:48 UTC, mlopatkin commented on subprojects/core/src/main/java/org/gradle/internal/classpath/Instrumented.java
> +            if (LOADED_FROM_CLASSLOADERS.containsKey(classLoader)) {
:nail_care: can be simplified to `if (LOADED_FROM_CLASSLOADERS.put(classLoader, null) != null) { throw ... }`, but that's mostly a matter of taste, I don't insist.

2023-08-22 09:19 UTC, asodja commented
@bot-gradle test and merge

2023-08-22 14:29 UTC, merged