Use IDE plugins to set GRADLE_LIBS_REPO_OVERRIDE url
gradle/gradle pull request #26044
Opened 2023-08-08 08:41 UTC by SidB3

### Context

Currently IDEs downloads Gradle sources from a hardcoded repository https://repo.gradle.org/gradle/list/libs-releases. 

This url is blocked by our proxy. This results in a very poor developer experience when trying to import the project into the ide. Intellij keeps trying to download Gradle sources from this url for a lot of time and project import never finishes. The issue is also very confusing at first glance because developers think that something is wrong with maven repositories defined for the project. 

There is a workaround of adding an environment variable but quoting from #25840 

> This[workaround] is great for an individual but hard for teams. In an environment of hundreds or thousands of engineers we'd have to make a large announcement, hope they apply the workaround, etc. This is pretty expensive and results aren't very durable for new people joining a team, machine upgrades, etc

This PR allows a build author to specify a Gradle sources repository url using the `idea` or `eclipse` plugins.

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2023-08-14 08:44 UTC, donat requested changes
I understand the use-case, however, I think jamming this internal concept into a place like `eclipse.classpth {} ` is incorrect.

Would it be a solution if we added a gradle property or a system property to override the url? That way a project can store the override url in the gradle.properties file.

2023-08-29 15:46 UTC, donat commented
@SidB3 You need a `Project` reference, which is available at both call sites where `DefaultGradleApiSourcesResolver` is instantiated.

2023-11-23 13:58 UTC, cobexer commented
Thank you for your interest in Gradle.

@SidB3  This PR has been in draft state for a while, do you have any plans to wrap it up? Unless this PR is updated it will be closed in 7 days.

2023-12-19 07:19 UTC, ov7a commented
This pull request has been closed due to inactivity. If you intend to work on this pull request, please ask the team to reopen the PR.

2023-12-19 07:19 UTC, closed without merging