Migrate some JVM language projects to JVM platform
gradle/gradle pull request #26187
Opened 2023-08-25 20:11 UTC by tresat

2023-08-25 20:12 UTC, tresat commented
@bot-gradle test this

2023-08-25 22:31 UTC, big-guy approved these changes

2023-08-25 22:36 UTC, big-guy requested changes
I forgot, we also need to update CODEOWNERS.

2023-08-28 11:56 UTC, tresat commented
@bot-gradle test and merge

2023-08-28 13:15 UTC, merged