Update foojay plugin version to 0.7.0 in docs and tests
gradle/gradle pull request #26184
Opened 2023-08-25 09:53 UTC by alllex

2023-08-25 16:04 UTC, lkasso approved these changes

2023-08-29 08:48 UTC, ljacomet requested changes
See remarks below, there should be no changes to dependency verification for this update.

2023-08-29 08:48 UTC, ljacomet commented on gradle/verification-metadata.xml
> +         <ignored-key id="e2f38302c8075e3d" reason="Key couldn't be downloaded from any key server"/>
❌ This needs to be removed, it is an artifact from the key failing to download.

2023-08-29 08:48 UTC, ljacomet commented on gradle/verification-metadata.xml
> +      <component group="org.gradle.toolchains" name="foojay-resolver" version="0.7.0">
❌ This should not appear as we trust the key itself.

2023-08-29 13:29 UTC, ljacomet commented on gradle/verification-metadata.xml
> +      <component group="org.gradle.toolchains" name="foojay-resolver" version="0.7.0">
But the trust of the key needs to be added. #26194 is taking care of this

2023-08-30 08:21 UTC, alllex commented
@bot-gradle test and merge

2023-08-30 10:51 UTC, merged