Bump Configuration Cache report to 1.3
gradle/gradle pull request #26194
Opened 2023-08-28 10:01 UTC by alllex

Migrates the Configuration Cache web report to version `1.3` that contains various styling fixes.

DO NOT MERGE before the metadata verification issues are resolved: https://github.com/gradle/gradle-private/issues/3963

2023-08-28 10:25 UTC, alllex commented
I manually validated that the CC reports produced by Gradle distro from this branch have expected styling (mainly, a larger font for the inline code):

<img width="975" alt="image" src="https://github.com/gradle/gradle/assets/2759152/49de6a39-ac10-421d-956b-85ea37126d47">

2023-08-29 08:55 UTC, ljacomet requested changes
❌ Similar to #26184, there should be no changes to verification metadata for this PR

2023-08-29 13:23 UTC, ljacomet approved these changes

2023-08-29 13:47 UTC, alllex commented
@bot-gradle test and merge

2023-08-29 16:12 UTC, merged