Dependency verification
gradle/gradle pull request #26268
Opened 2023-09-04 10:44 UTC by ahmedehabb

Fixes #20834 

### Context

Many users could benefit from this change because it addresses a specific use case in which developers want to track changes to the gradle/verification-keyring.keys file in pull request differentials. By making it possible to generate only the gradle/verification-keyring.keys file and not the gradle/verification-keyring.gpg file using the --export-keys option and vice versa if people want to keep .gpg only and not .keys file

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

2023-09-11 13:08 UTC, ov7a requested changes
The approach is good overall. Thanks for covering this. 

Please, don't forget to address the errors from sanityCheck.

2023-09-11 13:08 UTC, ov7a commented on subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/verification/serializer/DependencyVerificationsXmlReaderTest.groovy
> +    def "can parse keyring format"() {
💅 consider adding a test case with absent keyring-format entry

2023-10-04 16:57 UTC, lkasso approved these changes
Some changes and feedback on release notes.

2023-10-04 16:57 UTC, lkasso commented on subprojects/docs/src/docs/release/notes.md
> +When Gradle is asked to export all trusted keys via `./gradlew --export-keys`, it generates both binary and ASCII armored versions of the keys.
```suggestion
When Gradle is asked to export all trusted keys via `./gradlew --export-keys`, it generates both binary and ASCII armored versions of the keys.

```

2023-10-04 16:57 UTC, lkasso commented on subprojects/docs/src/docs/release/notes.md
> +In order to do so, you can edit `verification-metadata.xml` by adding the `keyring-format` setting.
```suggestion
To do so, edit `verification-metadata.xml` by adding the `keyring-format` setting:
```

2023-10-04 16:57 UTC, lkasso commented on subprojects/docs/src/docs/release/notes.md
> +With this release you can change this behavior and choose only one format.
```suggestion
You can now change this behavior to choose only one format.
```

2023-10-04 16:57 UTC, lkasso commented on subprojects/docs/src/docs/release/notes.md
> +We've also updated the XML validation schema for `verification-metadata.xml` to be more concise.
Could be nice to get a little more information or an example of this. How is it more concise?

2023-10-05 14:16 UTC, ov7a approved these changes

2023-10-06 14:29 UTC, ljacomet requested changes
Looks good overall to me.

There is one piece missing IMO.

`BuildTreeDefinedKeys` should take into account the new configuration option and only load the relevant file if this is configured.
Otherwise, the current default should remain: `gpg` over `keys`

2023-10-17 11:57 UTC, ljacomet approved these changes

2023-10-17 23:06 UTC, ov7a commented
@bot-gradle test and merge

2023-10-18 02:01 UTC, merged