Migrate testing projects to JVM, software platforms
gradle/gradle pull request #26421
Opened 2023-09-18 20:55 UTC by tresat

2023-09-18 20:55 UTC, tresat commented
@bot-gradle test this

2023-09-18 21:58 UTC, big-guy requested changes
One comment about owners. Moves LGTM.

2023-09-18 21:58 UTC, big-guy commented on .github/CODEOWNERS
> -subprojects/testing-jvm-infrastructure/     @gradle/bt-jvm @gradle/ge-testing
We need to preserve these owners for GE

2023-09-19 11:50 UTC, tresat commented
@bot-gradle test and merge

2023-09-19 12:35 UTC, merged