Add documentation for removing auto-provisioned toolchains
gradle/gradle pull request #26519
Opened 2023-09-25 22:50 UTC by anazworth

Added instructions to properly remove an auto-provisioned toolchain and a note about stopping the Gradle Daemon to clear the cache

Documentation change only.

Fixes #24581 

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

2023-09-26 18:14 UTC, lkasso commented on subprojects/docs/src/docs/userguide/jvm/toolchains.adoc
> +To properly remove an auto-provisioned toolchain, you can remove or modify any reference to the toolchain from `settings.gradle.kts` or `settings.gradle`
```suggestion
To properly remove an auto-provisioned toolchain, you can remove or modify any reference to the toolchain from `settings.gradle.kts` or `settings.gradle`.
```

2023-09-26 18:14 UTC, lkasso approved these changes

2023-10-09 09:45 UTC, ov7a commented
@anazworth Thank you for your interest in Gradle!

Please note that the original issue was about files on the disc, not the build script.

2023-10-09 09:46 UTC, ov7a requested changes
@anazworth Thank you for your interest in Gradle!

Please note that the original issue was about files on the disc, not the build script.

2023-10-10 06:43 UTC, ov7a requested changes

2023-10-11 16:45 UTC, lkasso submitted a review, later dismissed
Minor english cleanup.

2023-10-11 16:45 UTC, lkasso commented on subprojects/docs/src/docs/userguide/jvm/toolchains.adoc
> +In a situation where it's necessary to remove an auto-provisioned toolchain, remove the relevant toolchain located in the `/jdks` directory within the <<directory_layout.adoc#dir:gradle_user_home,Gra
```suggestion
When removing an auto-provisioned toolchain is necessary, remove the relevant toolchain located in the `/jdks` directory within the <<directory_layout.adoc#dir:gradle_user_home,Gradle User Home>>.
```

2023-11-14 13:55 UTC, ljacomet requested changes
See the comment below.

The documentation describing what to delete and the associated note are good to go after that.

2023-11-14 13:55 UTC, ljacomet commented on subprojects/docs/src/docs/userguide/jvm/toolchains.adoc
> +In some cases, a user might want explicit control over the toolchain configuration for their project.
This line and the next one do not provide any new information.
The section is in the toolchains chapter so there is no need to re-iterate what toolchains provide.

Please remove this line and the next one.

2024-03-11 05:02 UTC, lkasso commented
Reopening to clean up docs

2024-04-26 02:12 UTC, lkasso commented
@anazworth, I merged your changes in https://github.com/gradle/gradle/pull/28972.
Thank you for your contribution!

2024-04-26 02:12 UTC, closed without merging