feat(#26598): add --java-version so init don't enter into unwanted interactive mode
gradle/gradle pull request #26670
Opened 2023-10-07 23:40 UTC by sombriks

Fixes #26598 

### Context

### Contributor Checklist
- [X] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [X] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [X] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [X] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2023-10-09 13:12 UTC, tresat requested changes
Thank you for the submission and your interest in contributing to Gradle!  

Unfortunately we can't accept this as-is.  We do appreciate the effort that went into this work, and I think with a few further revisions this change could be added.

I've left some feedback and suggestions.  Due to the nature of the change, other Gradle maintainers will likely also take a look before this is merged.

2023-10-09 13:35 UTC, tresat commented
❌ Also be sure to run `gradlew sanityCheck` and fix any reported issues there.  New public API properties must be marked `@Incubating`.

2023-10-09 14:39 UTC, lkasso approved these changes
Some minor docs to cleanup.

2023-10-09 14:39 UTC, lkasso commented on subprojects/docs/src/docs/userguide/core-plugins/build_init_plugin.adoc
> +You can see available options from the task help:
```suggestion
You can see available options using the `help` task:
```

2023-10-09 14:39 UTC, lkasso commented on subprojects/docs/src/docs/userguide/core-plugins/build_init_plugin.adoc
> +The build type can be specified by using the `--type` command-line option. For example, to create a Java library project run:
```suggestion
The build type can be specified by using the `--type` command-line option. 
For example, to create a Java library project run:
```

2023-10-09 21:10 UTC, sombriks commented
Hi @tresat , @lkasso , thanks for the review!
I'll address the comments carefully and then ask for another round!

2023-10-12 12:29 UTC, tresat approved these changes

2023-10-12 12:29 UTC, tresat commented on platforms/software/build-init/src/main/java/org/gradle/buildinit/tasks/InitBuild.java
> +     * @return the java version number supplies by the user
```suggestion
     * @return the java version number supplied by the user
```

2023-10-12 12:29 UTC, tresat commented on platforms/software/build-init/src/testFixtures/groovy/org/gradle/buildinit/plugins/fixtures/ScriptDslFixture.groovy
> +    void assertGradleFilesGenerated(TestFile parentFolder = rootDir, String ...pathForBuild) {
```suggestion
    void assertGradleFilesGenerated(TestFile parentFolder = rootDir, String... pathForBuild) {
```

2023-10-12 12:30 UTC, tresat commented
@bot-gradle test and merge

2023-10-12 20:13 UTC, merged