Add codec for Unit type
gradle/gradle pull request #26761
Opened 2023-10-18 09:20 UTC by ILikeYourHat

Fixes #25560

### Context
Added code for Unit type. It ain’t much, but it’s honest work 😉 

No integration tests for this change, because existing tests are using GroovyDSL, so referencing Kotlin classes would not be trivial nor readable.

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md)
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2023-10-18 14:28 UTC, bgalek approved these changes

2023-10-31 09:30 UTC, ILikeYourHat commented
Any update on this PR? Do you need anything more from me?

2023-11-03 23:01 UTC, mlopatkin requested changes
> Any update on this PR? Do you need anything more from me?

Sorry for a delay and thank you for working on this! 

I think this is mostly good, except for the test. I'd prefer the assertion to be hardened. I'll kick off the rest of the tests, though I don't expect many failures.

2023-11-03 23:01 UTC, mlopatkin commented
@bot-gradle test this

2023-11-04 12:32 UTC, ILikeYourHat commented on platforms/core-configuration/configuration-cache/src/test/kotlin/org/gradle/configurationcache/serialization/codecs/UnitCodecTest.kt
> +    fun `can handle Unit instance`() {
changed to `same Unit instance is used upon restore`, I prefer to avoid negations in test names

2023-11-04 12:34 UTC, ILikeYourHat commented on platforms/core-configuration/configuration-cache/src/test/kotlin/org/gradle/configurationcache/serialization/codecs/UnitCodecTest.kt
> +            assertThat(this, `is`(Unit))
My mistake, I thought that `is` function does exactly that 🙈 Fixd

2023-11-06 12:56 UTC, abstratt approved these changes
👍

2023-11-06 13:02 UTC, mlopatkin approved these changes

2023-11-06 13:02 UTC, mlopatkin commented
@bot-gradle test and merge

2023-11-06 13:15 UTC, bamboo approved these changes

2023-11-06 17:45 UTC, merged

2023-11-06 18:23 UTC, mlopatkin commented
@ILikeYourHat thank you for fixing this!