Fix FilteringProvider to accept Spec instead of Predicate
gradle/gradle pull request #26770
Opened 2023-10-19 08:48 UTC by ov7a

### Context
It was missed during the [original PR](https://github.com/gradle/gradle/pull/26067) for
* https://github.com/gradle/gradle/issues/19981

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2023-10-19 09:11 UTC, ljacomet requested changes
Code changes LGTM

But since we are changing an API, even incubating, I think we should have a mention of the impact in the upgrade guide under potential breaking changes.

2023-10-19 09:32 UTC, ov7a commented
@bot-gradle test this

2023-10-19 14:05 UTC, ljacomet approved these changes

2023-10-19 17:10 UTC, lkasso approved these changes
Docs are approved with a few notes.

2023-10-19 17:10 UTC, lkasso commented on subprojects/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc
> +This change should not affect anyone using `Provider.filter` with a lambda expression.
```suggestion
This change does not affect anyone using `Provider.filter` with a lambda expression.
```

2023-10-19 17:10 UTC, lkasso commented on subprojects/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc
> +The type of the argument passed to `Provider.filter` is changed from `Predicate` to `Spec` to have a more consistent API.
```suggestion
The type of the argument passed to `Provider.filter` is changed from `Predicate` to `Spec` for a more consistent API.
```

2023-10-19 17:10 UTC, lkasso commented on subprojects/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc
> +However, this might have consequences for plugin authors.
Can we detail the consequences? What should they do?

2023-10-26 06:53 UTC, ov7a commented
@bot-gradle test and merge

2023-10-26 08:10 UTC, merged