Clean admonitions in Gradle User Manual
gradle/gradle pull request #27082
Opened 2023-11-19 00:04 UTC by lkasso

### Details
This is a Documentation change ONLY.

### Context
Cleans admonitions to use preferred ASCII doc syntax.
Remove long admonitions.

### Reviewers: 
Please make sure nothing was erroneously deleted.

2023-11-19 01:50 UTC, lkasso commented
@bot-gradle test BD

2023-11-19 02:15 UTC, lkasso commented
@bot-gradle test BD

2023-11-21 09:52 UTC, alllex reviewed
I skimmed it quickly and a couple of questions popped up

2023-11-22 14:10 UTC, tresat commented on subprojects/docs/src/docs/userguide/api/kotlin_dsl.adoc
> -.Avoid using internal Kotlin DSL APIs
+1 for leaving the titles.  Declaring the title ahead of the `NOTE:` in the md seems fine to me.  

Unrelated, I think the title being formatted with just italics doesn't draw enough attention to it.  Perhaps the style could be made a little more emphatic in a future change.

2023-11-22 14:35 UTC, tresat requested changes
I stopped reviewing after about a third of the way.

I completely agree there are way too many admonitions, and that many of the longer ones should be removed and incorporated into the normal text flow, or at least shortened.  

However, removing all but the first sentence of some of these notes from the admonitions itself seems to be often leading to the following pattern:


```markdown
Text about some topic X...

NOTE: By the way, also Y...

// Note ends

Therefore, Y means that...  // <-- This is more about Y and doesn't make sense outside of the admonition

Moving on to topic Z...
```

I think a rule of thumb should be the admonitions are self-contained to a large extent.  So if you remove them, does the text still make sense and continue to flow naturally?  If the answer is no, I think some of the _after_ text should be rewritten or moved into the admonition itself.

2023-11-22 14:35 UTC, tresat commented on subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/dependency_verification.adoc
> +Try to limit it to the appropriate groups or artifacts:
❗ It looks like this line at least should be in the admonition.

2023-11-22 14:35 UTC, tresat commented on subprojects/docs/src/docs/userguide/dep-man/02-declaring-dependency-versions/dependency_locking.adoc
>  This prevents persisting possibly invalid state.
❗ This text belongs in the admonition.

2023-11-22 14:35 UTC, tresat commented on subprojects/docs/src/docs/userguide/dep-man/02-declaring-dependency-versions/dynamic_versions.adoc
> +NOTE: Using dynamic versions and changing modules can lead to unreproducible builds. As new versions of a particular module are published, its API may become incompatible with your source code. Use t
🤔 As this note literally ends with caution, perhaps we should switch it to a `CAUTION` admonition?

2023-11-22 14:35 UTC, tresat commented on subprojects/docs/src/docs/userguide/dep-man/02-declaring-dependency-versions/dynamic_versions.adoc
> +NOTE: Using dynamic versions in a build bears the risk of potentially breaking it. As soon as a new version of the dependency is released that contains an incompatible API change your source code mig
🤔 Another caution?

2023-11-22 14:35 UTC, tresat commented on subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/dependency_downgrade_and_exclude.adoc
> +WARNING: Similar as forcing a version of a dependency, excluding a dependency completely requires a conscious decision.
```suggestion
WARNING: Similar to forcing a version of a dependency, excluding a dependency completely requires a conscious decision.
```

2023-11-22 14:35 UTC, tresat commented on subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/platforms.adoc
>  As such it makes sense to reduce the chance of collisions by picking a name that reduces the potential conflicts.
❗ This text continues the text in the admonition.

2023-11-28 04:24 UTC, lkasso commented on subprojects/docs/src/docs/userguide/api/kotlin_dsl.adoc
> -.Avoid using internal Kotlin DSL APIs
Admonitions should to be short and sweet. They should not have a title. 
Block should have a title.
I'll make sure to update this PR accordingly.

2023-11-28 04:25 UTC, lkasso commented on subprojects/docs/src/docs/userguide/api/groovy_build_script_primer.adoc
> +CAUTION: Avoid using https://groovy-lang.org/metaprogramming.html#_metaclasses[Groovy MetaClass] programming techniques in your build scripts. Gradle provides its own API for adding <<writing_build_s
+ is a forced new line in ascii docs.

2023-11-28 04:25 UTC, lkasso commented on subprojects/docs/src/docs/userguide/authoring-builds/writing_build_scripts.adoc
> +IMPORTANT: Build scripts_ define `Project` objects. +
Thank you

2023-11-29 06:31 UTC, lkasso commented on subprojects/docs/src/docs/userguide/dep-man/03-controlling-transitive-dependencies/resolution_rules.adoc
> +WARNING: This section covers mechanisms Gradle offers to directly influence the behavior of the dependency resolution engine.
Great question.

2023-11-29 07:04 UTC, lkasso commented
@bot-gradle test BD

2023-12-04 16:42 UTC, lkasso commented
@bot-gradle test BD

2023-12-07 01:49 UTC, lkasso commented
@bot-gradle test and merge

2023-12-07 03:34 UTC, merged