Don't fail the build on invalid Problems API invocation
gradle/gradle pull request #27383
Opened 2023-12-12 14:39 UTC by donat

Fixes #27353

2023-12-12 14:40 UTC, donat commented
@bot-gradle test QFL

2023-12-12 17:35 UTC, donat commented
@bot-gradle test RFM

2023-12-12 17:46 UTC, donat commented
@bot-gradle test RFM

2023-12-12 17:54 UTC, donat commented
@bot-gradle test RFM

2023-12-13 06:58 UTC, reinsch82 requested changes
A few small things.
note: I didn't mark all the missing whitespaces for `withReportProblemTask`

2023-12-13 06:58 UTC, reinsch82 commented on platforms/ide/problems-api/src/integTest/groovy/org/gradle/api/problems/ProblemsServiceIntegrationTest.groovy
> +        withReportProblemTask"""
💅 
```suggestion
        withReportProblemTask """
```

2023-12-13 06:58 UTC, reinsch82 commented on platforms/ide/problems-api/src/integTest/groovy/org/gradle/api/problems/ProblemsServiceIntegrationTest.groovy
> +        withReportProblemTask"""
💅 
```suggestion
        withReportProblemTask """
```

2023-12-13 06:58 UTC, reinsch82 commented on platforms/ide/problems-api/src/integTest/groovy/org/gradle/api/problems/ProblemsServiceIntegrationTest.groovy
> +        withReportProblemTask"""
💅 
```suggestion
        withReportProblemTask """
```

2023-12-13 06:58 UTC, reinsch82 commented on platforms/ide/problems-api/src/integTest/groovy/org/gradle/api/problems/ProblemsServiceIntegrationTest.groovy
> +                def exception = new RuntimeException("test")
💅 I think we should inline `exception`

2023-12-13 06:58 UTC, reinsch82 commented on platforms/ide/problems-api/src/integTest/groovy/org/gradle/api/problems/ProblemsServiceIntegrationTest.groovy
> +            def exception = new RuntimeException("test")
💅 I think we should inline `exception`

2023-12-13 08:15 UTC, donat commented
@bot-gradle test RFM

2023-12-13 08:20 UTC, donat commented on platforms/ide/problems-api/src/integTest/groovy/org/gradle/api/problems/ProblemsServiceIntegrationTest.groovy
> +        withReportProblemTask"""
Fixed by reformatting the code.

2023-12-13 08:23 UTC, reinsch82 approved these changes
LGTM

2023-12-13 09:22 UTC, donat commented
@bot-gradle merge

2023-12-13 10:46 UTC, merged