Make `KotlinDslScriptsModelSpec` a crossVersionTest
gradle/gradle pull request #27628
Opened 2024-01-09 14:19 UTC by reinsch82

Addresses 
- #27198

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2024-01-09 14:32 UTC, reinsch82 commented
@bot-gradle test ACT

2024-01-10 08:25 UTC, donat requested changes
I have concerns with the newly introduced dependencies, otherwise the PR is good to go.

2024-01-10 08:25 UTC, donat commented on platforms/core-configuration/kotlin-dsl-tooling-builders/build.gradle.kts
> +    implementation(project(":kotlin-dsl-tooling-models"))
❌  Why do you need to introduce dependencies for the main source set when your change only affects tests?

2024-01-10 08:31 UTC, donat approved these changes

2024-01-10 08:31 UTC, reinsch82 commented
@bot-gradle merge

2024-01-10 10:14 UTC, merged