Apache commons compress upgrade to 1.25
gradle/gradle pull request #27666
Opened 2024-01-12 08:03 UTC by ov7a

Fixes #27604

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2024-01-12 13:37 UTC, cobexer requested changes
This may need release notes /upgrade guide because some of the changes in commons-compress may change the produced files:

https://issues.apache.org/jira/browse/COMPRESS-612
* https://github.com/apache/commons-compress/pull/254

https://issues.apache.org/jira/browse/COMPRESS-613
* https://github.com/apache/commons-compress/pull/345

https://issues.apache.org/jira/browse/COMPRESS-638
* https://github.com/apache/commons-compress/commit/770ea82a132282fb0edb186fe6db646a1a0b7a35

possibly more

2024-01-12 13:39 UTC, ov7a commented
@cobexer Yep. already working on that, sorry for miscommunication

2024-01-13 00:15 UTC, lkasso approved these changes
Docs LGTM

2024-01-15 07:58 UTC, cobexer commented on platforms/documentation/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc
> +Apache Commons Compress has been updated from 1.21 to https://commons.apache.org/proper/commons-compress/changes-report.html#a1.25.0[1.25.0].
💅 might include that the previous version used to be 1.21

2024-01-15 08:15 UTC, cobexer commented on platforms/documentation/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc
> +Apache Commons Compress has been updated from 1.21 to https://commons.apache.org/proper/commons-compress/changes-report.html#a1.25.0[1.25.0].
I... go get myself a coffee...

2024-01-15 09:11 UTC, cobexer approved these changes

2024-01-19 06:43 UTC, ov7a commented
@bot-gradle merge

2024-01-31 12:40 UTC, ov7a commented
@bot-gradle APT

2024-01-31 12:40 UTC, ov7a commented
@bot-gradle test APT

2024-02-02 07:32 UTC, ov7a commented
@bot-gradle merge

2024-02-02 09:02 UTC, merged