Rework schema customisation setup for the Declarative DSL interpreter
gradle/gradle pull request #28157
Opened 2024-02-21 12:41 UTC by h0tk3y

2024-02-22 10:34 UTC, eskatos requested changes
This is looking good overall.

Please add integration tests for the use cases fixed by this PR: support for Gradle properties in the settings DSL.

2024-02-23 12:36 UTC, h0tk3y commented
@bot-gradle test and merge

2024-02-23 12:38 UTC, eskatos approved these changes

2024-02-23 15:59 UTC, h0tk3y commented
@bot-gradle merge

2024-02-23 17:08 UTC, merged