Let declarative DSL performance tests declare minimum base Gradle version
gradle/gradle pull request #28179
Opened 2024-02-22 05:51 UTC by blindpirate

A performance test for Declarative DSL was introduced in https://github.com/gradle/gradle/pull/28098, and it broke performance test because the baseline version doesn't support Declarative DSL. Reset the baseline to commit 03c5536d04b927da43318918ab0824a6b457206f

2024-02-22 10:33 UTC, jbartok approved these changes

2024-02-22 10:39 UTC, eskatos requested changes
I don't think we should do this.

We should set `runner.minimumBaseVersion` to 8.8 in the performance tests instead.

2024-02-23 12:45 UTC, jbartok commented
@eskatos I think it's ok now, please take a look and lift the change request if you agree.

2024-02-23 12:58 UTC, eskatos approved these changes
👍

2024-02-27 08:25 UTC, eskatos commented on subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/BaselineVersionResolver.groovy
> +        Assume.assumeFalse("Ignore the test if all baseline versions are filtered out", resolvedVersions.isEmpty())
Hey Bo,
These failures are an overhead when doing performance regression tracking. We should not consider this normal.
Could you clarify what is the issue with the change?

2024-02-27 11:24 UTC, eskatos commented on subprojects/internal-performance-testing/src/main/groovy/org/gradle/performance/fixture/BaselineVersionResolver.groovy
> +        Assume.assumeFalse("Ignore the test if all baseline versions are filtered out", resolvedVersions.isEmpty())
Got it. Thank you for the explanation Bo!

2024-02-28 09:12 UTC, merged

2024-02-28 11:50 UTC, jbartok commented
Thank you, @blindpirate, and sorry for the slow reaction and making you do my work instead.