clean up and break up integ test
gradle/gradle pull request #28256
Opened 2024-02-27 07:02 UTC by reinsch82

Fixes 
 - #28244 

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2024-02-27 07:49 UTC, reinsch82 commented
@bot-gradle test RFN

2024-02-27 08:09 UTC, donat requested changes

2024-02-27 08:23 UTC, reinsch82 commented on subprojects/core/src/integTest/groovy/org/gradle/execution/commandline/CommandLineIntegrationTest.groovy
> +        then:
good point, I wasn't aware of `cleanup`

2024-02-27 13:49 UTC, donat approved these changes

2024-02-27 14:03 UTC, reinsch82 commented
@bot-gradle merge

2024-02-29 13:30 UTC, donat commented
@bot-gradle merge

2024-03-05 11:49 UTC, reinsch82 commented
@bot-gradle test this

2024-03-05 13:53 UTC, reinsch82 commented
@bot-gradle test RFN

2024-03-07 10:33 UTC, reinsch82 commented
@bot-gradle test RFN

2024-03-07 15:15 UTC, reinsch82 commented
@bot-gradle test RFN

2024-03-15 10:03 UTC, reinsch82 commented
@bot-gradle test this

2024-03-15 12:46 UTC, reinsch82 commented
@bot-gradle test this

2024-03-15 16:08 UTC, merged

2024-03-18 07:50 UTC, donat commented
🎉 🎉 🎉