Improve problem aggregation
gradle/gradle pull request #28396
Opened 2024-03-08 11:57 UTC by reinsch82

Fixes 
 - #28215 

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2024-03-08 12:56 UTC, reinsch82 commented
@bot-gradle test ACT

2024-03-11 14:03 UTC, reinsch82 commented
@bot-gradle test ACT

2024-03-11 15:03 UTC, reinsch82 commented
@bot-gradle test ACT

2024-03-12 13:55 UTC, reinsch82 commented
@bot-gradle test ACT

2024-03-12 15:57 UTC, reinsch82 commented
@bot-gradle test ACT

2024-03-13 15:38 UTC, reinsch82 commented
@bot-gradle test ACT

2024-03-14 07:15 UTC, reinsch82 commented
@bot-gradle test ACT

2024-03-14 14:24 UTC, reinsch82 commented
@bot-gradle test ACT

2024-03-18 06:54 UTC, reinsch82 commented
@bot-gradle test this

2024-03-18 10:32 UTC, donat requested changes
Looks good, I mainly have review items about naming and documentation.

2024-03-18 10:32 UTC, donat commented on platforms/ide/tooling-api/src/main/java/org/gradle/tooling/internal/protocol/InternalProblemAggregationV2.java
> +public interface InternalProblemAggregationV2 extends InternalProblemAggregation {
❌ To follow the pattern in the `protocol` package, this interface should be called `InternalProblemAggregationVersion2`.

2024-03-18 10:32 UTC, donat commented on platforms/ide/tooling-api/src/main/java/org/gradle/tooling/events/problems/ProblemContextDetails.java
> +public interface ProblemContextDetails {
Can we call it `ProblemContext`?

2024-03-18 10:32 UTC, donat commented on platforms/ide/tooling-api/src/main/java/org/gradle/tooling/events/problems/ProblemAggregation.java
> +    List<ProblemContextDetails> getProblemContextDetails();
getContexts()
getProblemContexts()?

2024-03-18 10:32 UTC, donat commented on platforms/ide/tooling-api/src/main/java/org/gradle/tooling/events/problems/ProblemAggregationEvent.java
> +     * Returns the problem category that is common for all aggregated problems.
❌ This doesn't seem accurate.

2024-03-18 14:57 UTC, donat approved these changes

2024-03-18 16:32 UTC, merged