More newbie-friendly documentation for the CodeNarc plugin regarding Groovy 3
gradle/gradle pull request #28641
Opened 2024-03-31 16:43 UTC by JayWei1215

More newbie-friendly documentation for the CodeNarc plugin regarding Groovy 3
Signed-off-by: Jay Wei <jaywei011215@gmail.com>

### Context

Provide documentation on specifying the Groovy version for the CodeNarc plugin dependency. 

Documentation change only.

Fixes https://github.com/gradle/gradle/issues/14853

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2024-04-01 11:01 UTC, tresat requested changes

2024-04-01 11:01 UTC, tresat commented on platforms/documentation/docs/src/docs/userguide/core-plugins/codenarc_plugin.adoc
> +When there is a significant difference between the Groovy version used for compiling the code and the version that CodeNarc depends on, it's necessary to specify a specific Groovy version.
```suggestion
If CodeNarc requires a different Groovy version than that used to compile Groovy source,  you can supply one using the `codenarc` configuration.
```

2024-04-01 15:08 UTC, lkasso commented
@bot-gradle test BD

2024-04-05 12:12 UTC, JayWei1215 commented
I have updated the PR @tresat

2024-04-05 17:02 UTC, lkasso approved these changes

2024-04-07 13:41 UTC, JayWei1215 commented
It still prompts '1 change requested' here, and I'm not sure if this is the reason for the merge branch failure. @lkasso @tresat

2024-04-08 21:45 UTC, lkasso commented
@bot-gradle test BD

2024-04-09 15:02 UTC, JayWei1215 commented
I have fixed the error. @lkasso @blindpirate

2024-04-16 05:38 UTC, merged