config cache problems in problem api
gradle/gradle pull request #28739
Opened 2024-04-09 07:01 UTC by reinsch82

Initial version

some tests need fixing

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2024-04-09 07:22 UTC, reinsch82 commented
@bot-gradle test this

2024-06-03 11:23 UTC, reinsch82 commented
@bot-gradle test this

2024-06-05 12:14 UTC, reinsch82 commented
@bot-gradle test this

2024-06-05 13:42 UTC, reinsch82 commented
@bot-gradle test APT

2024-06-10 10:10 UTC, donat requested changes
Looks good to me, only the TODOs in the PR should be addressed.

2024-06-10 10:10 UTC, donat commented on platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheProblems.kt
> +            ) // TODO (reinhold) display name might be too elaborate
Please double-check that. The id should be just a few words. We have the `contextualLabel` and the `details` fields to add longer descriptions.

2024-06-10 10:10 UTC, donat commented on testing/internal-integ-testing/src/main/groovy/org/gradle/integtests/fixtures/problems/KnownProblemIds.groovy
> +        'validation:configuration-cache-cannot-serialize-object-of-type-org-gradle-api-defaulttask-a-subtype-of-org-gradle-api-task-as-these-are-not-supported-with-the-configuration-cache' : 'cannot
Although the id definitions look a bit suspicious, they might be correct as-is. These IDs are indeed context-insensitive and indeed uniquely define a particular configuration cache problem.

2024-06-11 08:25 UTC, donat approved these changes

2024-06-11 08:25 UTC, donat commented on platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/configurationcache/problems/ConfigurationCacheProblems.kt
> +            documentedAt(Documentation.userManual("configuration_cache", it.anchor).toString()) // TODO (reinhold) not sure?
❌ I assume it's a leftover TODO.

2024-06-11 17:53 UTC, merged