Fix cross version tests related to r86/ProblemProgressEventCrossVersi…
gradle/gradle pull request #28910
Opened 2024-04-22 14:08 UTC by reinsch82

Fixes 
 - gradle/gradle-private#4182

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2024-04-22 15:07 UTC, reinsch82 commented
@bot-gradle test ACT

2024-04-23 07:15 UTC, donat requested changes

2024-04-23 07:15 UTC, donat commented on platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r86/ProblemProgressEventCrossVersionTest.groovy
> +    static void assertProblemDetailsForTAPIProblemEventWithoutSolution(List<?> problems) {
Does it bring any value to keep this method? If it's trivial, I'd just inline the `problems.size() == 1` assertion.

2024-04-23 08:31 UTC, reinsch82 commented
@bot-gradle test ACT

2024-04-23 08:39 UTC, reinsch82 commented
@bot-gradle test ACT

2024-04-23 08:57 UTC, donat approved these changes

2024-04-23 13:23 UTC, merged