Add notes about testing Gradle 8.8 builds with TestKit using older Gradle versions
gradle/gradle pull request #29184
Opened 2024-05-16 13:26 UTC by asodja

2024-05-16 14:12 UTC, cobexer approved these changes

2024-05-16 14:59 UTC, ljacomet requested changes
Am I correct in thinking this is the answer to #29000?

If yes, could you please make it explicit.

2024-05-16 14:59 UTC, ljacomet commented on platforms/documentation/docs/src/docs/release/notes.md
> +#### Testing Gradle 8.8 builds with TestKit using older Gradle version
❌ We should not mention this in release notes since that's a potential breaking change. It belongs to the upgrade guide.

2024-05-16 14:59 UTC, ljacomet commented on platforms/documentation/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc
> +To fix this issue, you should use Gradle 8.8 to run the tests.
❓ Is that really the only option? In #29000 you list more options. IMO we should document them all here.

2024-05-17 23:25 UTC, lkasso commented on platforms/documentation/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc
> +While previous versions ignored that flag, Gradle 8.8 correctly reads `org.gradle.native` flag, and thus disables native services.
```suggestion
While previous versions ignored that flag, Gradle 8.8 correctly reads the `org.gradle.native` flag, and thus disables native services.
```

2024-05-21 08:11 UTC, closed without merging