Documentation cleanup for June - part 1
gradle/gradle pull request #29430
Opened 2024-06-05 22:36 UTC by lkasso

### Details
This is a Documentation change ONLY.

### Context
This is an update for:
1.  Fix https://github.com/gradle/gradle/issues/29394

2024-06-11 17:58 UTC, lkasso commented
@bot-gradle test BD

2024-06-12 08:33 UTC, oleg-nenashev requested changes
One of the biggest changes in this PR is removal of https://docs.gradle.org/current/userguide/third_party_integration.html , with no links to the replacement content, and with no merge into existing pages. This removal is not listed in the scope of the PR, so I am not sure what is the reasoning for removing content from this page without equal replacement.

I would suggest the following:

- Move the IDE integrations content as a new section in the cookbook
- Extract Tooling API somewhere, AFAICT it is still a part of the user guide (or maybe a developer guide)
- Nice2Have: Fix redirects to the links so they point to the pages

2024-06-12 08:33 UTC, oleg-nenashev commented on platforms/documentation/docs/src/docs/userguide/redirects/github-actions.adoc
> +<meta http-equiv="refresh" content="0;URL=https://community.gradle.org/">
IIUC it is not a redirect to the page but to the root, right?

2024-06-12 08:33 UTC, oleg-nenashev commented on platforms/documentation/docs/src/docs/userguide/reference/third_party_integration.adoc
> -== IDEs
Are you moving it to the Cookbook? AFAICT we do not have a replacement content
As of now, I suggest incorporating the difference to https://docs.gradle.org/current/userguide/gradle_ides.html or moving the pages to the Cookbook and putting references

2024-06-12 08:33 UTC, oleg-nenashev commented on platforms/documentation/docs/src/docs/userguide/reference/third_party_integration.adoc
> -== Embedding Gradle using the Tooling API
Is there a replacement page for Tooling API information somewhere? AFAICT it is still fully supported https://docs.gradle.org/current/javadoc/org/gradle/tooling/GradleConnector.html

2024-06-12 08:33 UTC, oleg-nenashev commented on platforms/documentation/docs/src/docs/userguide/reference/third_party_integration.adoc
> -=== Compatibility of Java and Gradle versions
Should the content be merged into https://docs.gradle.org/current/userguide/compatibility.html#java

2024-06-12 08:33 UTC, oleg-nenashev commented on platforms/documentation/docs/src/docs/userguide/reference/third_party_integration.adoc
> +This page has been removed.
Should it actually reference some page?

2024-06-12 08:33 UTC, oleg-nenashev commented on platforms/documentation/docs/src/main/resources/header.html
> -            <h3 id="gradle-on-ci">Gradle on CI</h3>
Should we create a link to Gradle Cookbook in the User Guide navbar?

2024-06-12 18:07 UTC, lkasso commented
@bot-gradle test BD

2024-06-12 20:52 UTC, lkasso commented
@bot-gradle test BD

2024-06-12 20:53 UTC, lkasso commented
@bot-gradle clean

2024-06-12 21:12 UTC, lkasso commented
@bot-gradle test BD

2024-06-13 00:02 UTC, lkasso commented
@bot-gradle clean

2024-06-13 04:37 UTC, oleg-nenashev approved these changes
I would suggest starting the Cookbook section as in https://github.com/gradle/gradle/pull/29430#discussion_r1636059376 , but it can be done later once we have more content there

2024-06-13 05:23 UTC, lkasso commented
> I would suggest starting the Cookbook section as in [#29430 (comment)](https://github.com/gradle/gradle/pull/29430#discussion_r1636059376) , but it can be done later once we have more content there

I'm not ready for that yet. I prefer to do it in Version 2.0 of the manual.

2024-06-13 08:13 UTC, merged