Update release notes to include preview feature section
gradle/gradle pull request #29683
Opened 2024-06-25 14:46 UTC by lkasso

### Details
This is a Documentation change ONLY.

### Context
Release Notes now have a "Preview Features" section for Gradle features in alpha/beta/testing mode.

2024-06-25 22:07 UTC, big-guy requested changes
I think I'm -1 to this.  I'm not really sure we want to split the release notes into stable/unstable update sections.

2024-06-25 22:07 UTC, big-guy commented on platforms/documentation/docs/src/docs/release/notes-template.md
> +## Preview features
I think preview features is maybe the wrong phrase here. We already have something called "feature previews". Feature previews are a way we introduce breaking behavior and allow builds to opt into the new behavior early.

e.g., type-safe project accessors are both an incubating feature and enabled with a feature preview.  Not every incubating feature will have a feature preview and not every feature preview will align with an incubating feature. 

A preview feature isn't a part of our feature lifecycle (internal -> incubating -> public -> deprecated).  We have the "promoted features" section above which is supposed to signal something going from incubating -> public/stable.  This usually happens after a long period of no other changes, so there's nothing significant to report. 

I'm not sure if we really want/need an entirely separate section dedicated to incubating (or preview features). That would imply the other section can only be updates to existing stable features.  Maybe we just need to be clear when an update is about an incubating feature/API or use some kind of special header decoration, like we do in the DSL reference.

2024-07-01 10:19 UTC, oleg-nenashev reviewed
Looks good overall, just clarufying some bits

2024-07-01 10:19 UTC, oleg-nenashev commented on platforms/documentation/docs/src/docs/userguide/releases/feature_lifecycle.adoc
> +The feature might significantly change or be removed at any time.
```suggestion
The experimental feature might significantly change or be removed at any time, without prior notice.
```

2024-07-01 10:19 UTC, oleg-nenashev commented on platforms/documentation/docs/src/docs/userguide/releases/feature_lifecycle.adoc
> +We do not guarantee the use of these features against defects that may produce unexpected or undesired results.
```suggestion
We do not guarantee the use of these features against defects that may produce unexpected or undesired results,
including but not limited to potential security risks.
```

2024-07-01 10:19 UTC, oleg-nenashev commented on platforms/documentation/docs/src/docs/userguide/releases/feature_lifecycle.adoc
> +Eventually _experimental_ features either graduate to _incubating_ or are removed from Gradle.
"Graduate" seems to be a stronger word

```suggestion
Eventually _experimental_ features either get promoted to _incubating_ or are removed from Gradle.
```

2024-07-01 10:19 UTC, oleg-nenashev commented on platforms/documentation/docs/src/docs/userguide/releases/feature_lifecycle.adoc
>  Features are introduced in the _incubating_ state to allow real-world feedback to be incorporated into the feature before making it public.
```suggestion
The _incubating_ state for new features is designed to allow real-world feedback to be incorporated into the feature before making it public.
```

2024-07-01 10:19 UTC, oleg-nenashev commented on platforms/documentation/docs/src/docs/userguide/releases/feature_lifecycle.adoc
> +_Experimental_ features are not enabled by default.
```suggestion
_Experimental_ features are not enabled by default, and enabling them might require multiple steps and a special environment.
Follow the feature documentation.
```

2024-07-03 18:13 UTC, lkasso commented
Adding an "Experiment" feature lifecycle is no longer needed to improve and produce guidelines for release notes.

2024-07-03 18:13 UTC, closed without merging

2024-07-07 17:19 UTC, oleg-nenashev commented
Would be nice to summarize the decision for the community members