Fix problem report url for cc
gradle/gradle pull request #29743
Opened 2024-06-28 12:32 UTC by reinsch82

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2024-07-05 08:49 UTC, reinsch82 commented
@bot-gradle test this

2024-07-05 12:15 UTC, hegyibalint commented on platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/ConfigurationCacheProblemsServiceIntegTest.groovy
> +            locations.size() == 2
:x:  We should stop doing this, as implicit locations (e.g., task location, which I'm trying to introduce) break this.

2024-07-05 12:17 UTC, hegyibalint requested changes
Implementation is OK, left some remarks about location counting

2024-07-05 12:17 UTC, hegyibalint commented on platforms/core-configuration/configuration-cache/src/crossVersionTest/groovy/org/gradle/internal/cc/impl/ConfigurationCacheProblemsCrossVersionTest.groovy
> +    def "Failing executions produce problems"() {
🤔 Most of our tests are starting with lowercase, are TAPI tests different?

```suggestion
    def "failing executions produce problems"() {
```

2024-07-05 12:17 UTC, hegyibalint commented on platforms/core-configuration/configuration-cache/src/crossVersionTest/groovy/org/gradle/internal/cc/impl/ConfigurationCacheProblemsCrossVersionTest.groovy
> +            locations.size() == 2
❌ We should stop doing this, as implicit locations (e.g., task location, which I'm trying to introduce) break this.

2024-07-08 08:30 UTC, hegyibalint approved these changes

2024-07-08 11:22 UTC, merged