Update Dokka & Dokkatoo versions
gradle/gradle pull request #29953
Opened 2024-07-18 08:57 UTC by jbartok

### Context

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2024-07-18 09:56 UTC, cobexer requested changes
Changes to the verification-metadata must be verified

2024-07-18 09:56 UTC, cobexer commented on gradle/verification-metadata.xml
> +            <sha256 value="726484477260a552dc7c19b09d4656c48ae3b10db2725000e182d6159529b46e" origin="Generated by Gradle" reason="A key couldn't be downloaded"/>
❌ this must be resolved
> Also, there should not be any "Generated by Gradle" origins left.

2024-07-19 07:48 UTC, aSemy commented
Hey @jbartok, I recommend you remove the Dokka version override here:

https://github.com/gradle/gradle/blob/4ed68e856d43f6b66e400e698e46265c43777937/platforms/documentation/docs/build.gradle#L101-L103

[Dokkatoo 2.3.1 uses Dokka 1.9.20 by default](https://github.com/adamko-dev/dokkatoo/blob/v2.3.1/gradle/libs.versions.toml#L4).

2024-07-19 08:14 UTC, jbartok commented
> Hey @jbartok, I recommend you remove the Dokka version override ...

Very good point, thanks a lot!

2024-07-23 07:06 UTC, jbartok commented
@cobexer good to go?

2024-07-24 13:25 UTC, merged