Deprecate selecting variant by configuration name for non-ivy external components
gradle/gradle pull request #30287
Opened 2024-08-23 05:06 UTC by jvandort

This effectively deprecates selecting variants by configuration name for maven components. Previously, users were able to select maven "configurations" such as runtime, compile, or test, using the configuration: notation when declaring the dependency.

Maven does not have the concept of configurations. Variant derivation works well for maven and we are sticking to it.

This leaves only ivy components and local components as the only components that support variant selection via configuration name. Eventually, local components will also get this same restriction. Only ivy components should allow variant-by-name selection, as that is a core aspect of its resolution model.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2024-08-23 11:48 UTC, jvandort commented
@bot-gradle test this

2024-08-29 21:56 UTC, big-guy requested changes

2024-08-29 21:56 UTC, big-guy commented on platforms/documentation/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc
> +
Can we link to a section of the user manual about variant aware dependency resolution? 

```suggestion
Starting in Gradle 9.0, selecting variants by name from non-Ivy external components will be forbidden.

Selecting variants by name from local components will still be permitted; however, this pattern is discouraged.
For local components, variant aware dependency resolution should be preferred over selecting variants by name.

The following dependencies will fail to resolve when targeting a non-Ivy external component:

```

2024-08-29 21:56 UTC, big-guy commented on platforms/software/dependency-management/src/main/java/org/gradle/internal/component/model/DefaultExternalComponentGraphResolveState.java
> +                .nagUser();
```suggestion
            DeprecationLogger.deprecateBehaviour("Selecting a variant by configuration name from a non-Ivy external component.")
                .willBecomeAnErrorInGradle9()
                .withUpgradeGuideSection(8, "selecting_variant_by_configuration_name")
                .nagUser();
```

2024-08-29 21:56 UTC, big-guy commented on platforms/documentation/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc
> +    implementation(group: "com.example", name: "example", version: "1.0", configuration: "conf")
Can we add something to DependencyHandler docs to discourage this?

2024-08-29 21:56 UTC, big-guy commented on platforms/documentation/docs/src/docs/userguide/releases/upgrading/upgrading_version_8.adoc
> +        targetConfiguration = "conf"
Can we add something to ModuleDependency Javadoc to discourage this for Maven?

2024-09-04 01:19 UTC, jvandort commented
@bot-gradle test this

2024-09-04 05:24 UTC, merged