Update Develocity Gradle Plugin to 3.18.1
gradle/gradle pull request #30478
Opened 2024-09-10 15:39 UTC by welandaz

This PR updates Develocity Gradle Plugin to the latest `3.18.1` version

2024-09-10 15:39 UTC, welandaz commented
@bot-gradle test this

2024-09-10 16:33 UTC, ljacomet requested changes
❌ `release` is not an active branch for the moment.
This should be merged to `master` instead.

2024-09-10 16:34 UTC, wolfs requested changes

2024-09-10 16:34 UTC, wolfs commented on build-logic-commons/build-platform/build.gradle.kts
> +        api("com.gradle:develocity-gradle-plugin:3.18.1") // Run `build-logic-settings/update-develocity-plugin-version.sh <new-version>` to update
🤔 The 8.10.1 patch release just went out, I think we shouldn't change the bundled version for 8.10 anymore. Let's do the PR on `master`.

2024-09-10 16:34 UTC, wolfs commented on build-logic-commons/gradle-plugin/build.gradle.kts
> +    compileOnly("com.gradle:develocity-gradle-plugin:3.18.1")
❌ This version should be removed, as on `master`.

2024-09-10 17:15 UTC, welandaz commented
> ❌ `release` is not an active branch for the moment. This should be merged to `master` instead.
> 
> Even if we planned a 8.10.2, I am not sure we would take this change in it.

You mean release will be recreated from `master`? (e.g. there is going to be no merge to `master` if this PR ends in `release`)

2024-09-11 10:18 UTC, welandaz commented
Closed in favor of https://github.com/gradle/gradle/pull/30491 as discussed in comments

2024-09-11 10:18 UTC, closed without merging