Move classes used for generating Groovy interceptors from :core to :internal-instrumentation-api
gradle/gradle pull request #30572
Opened 2024-09-16 13:59 UTC by asodja

So we can upgrade classes in core-api.

Fixes https://github.com/gradle/gradle/issues/29239

2024-09-16 14:00 UTC, asodja commented
@bot-gradle test this

2024-09-16 14:23 UTC, asodja commented
@bot-gradle test this

2024-09-16 14:33 UTC, asodja commented
@bot-gradle clean

2024-09-16 14:51 UTC, asodja commented
@bot-gradle test this

2024-09-16 14:52 UTC, asodja commented
@bot-gradle clean

2024-09-17 06:49 UTC, mlopatkin requested changes
Looks good! 

For the remaining interceptor implementation classes, I think they should be moved too, the current split now feels a bit arbitrary.

2024-09-17 06:49 UTC, mlopatkin commented on subprojects/core/src/test/groovy/org/gradle/internal/classpath/intercept/InterceptScopeTest.groovy
💅  I think this test should be moved too, alongside the class its tests.

2024-09-17 06:49 UTC, mlopatkin commented on subprojects/core/src/main/java/org/gradle/internal/classpath/intercept/CallInterceptorResolver.java
❓ Why is the reset of the package still in `:core`?

2024-09-17 06:49 UTC, mlopatkin commented on platforms/core-runtime/internal-instrumentation-processor/src/main/java/org/gradle/internal/instrumentation/processor/codegen/groovy/InterceptGroovyCallsGenerator.java
> +    static final ClassName FILTERABLE_CALL_INTERCEPTOR = ClassName.get(FilterableCallInterceptor.class);
👍

2024-09-17 07:35 UTC, asodja commented on subprojects/core/src/test/groovy/org/gradle/internal/classpath/intercept/InterceptScopeTest.groovy
Good catch

2024-09-17 07:36 UTC, asodja commented on subprojects/core/src/main/java/org/gradle/internal/classpath/intercept/CallInterceptorResolver.java
I moved only as little as is needed. I can try to move other classes too if they don't have any dependencies

2024-09-18 12:18 UTC, asodja commented
@bot-gradle test this

2024-09-18 12:18 UTC, asodja commented on subprojects/core/src/test/groovy/org/gradle/internal/classpath/intercept/InterceptScopeTest.groovy
Fixed

2024-09-18 12:20 UTC, asodja commented on subprojects/core/src/main/java/org/gradle/internal/classpath/intercept/CallInterceptorResolver.java
The rest of the package is not actually used in generated classes but only at runtime. I left only classes that are responsible to discovering interceptors in `:core` for now.

I guess we could at one point add `instrumentation-runtime` project (or just move them to `instrumentation-api`). But it looks like it needs some more untangling. So I left them there for now.

2024-09-18 12:22 UTC, asodja commented
> For the remaining interceptor implementation classes, I think they should be moved too, the current split now feels a bit arbitrary.

Moved `ClassBoundCallInterceptor`, `CompositeCallInterceptor` and `FilterableCallInterceptor` as well. Others are concrete implementation which in `Instrumented.java` which I think doesn't belong in `instrumentation-api` project.

2024-09-18 12:29 UTC, asodja commented
@bot-gradle clean

2024-09-18 12:53 UTC, mlopatkin approved these changes

2024-09-18 14:39 UTC, merged