Use a non-caching non-reporting JVM metadata detector when provisioning
gradle/gradle pull request #30774
Opened 2024-10-03 05:51 UTC by octylFractal

Fixes #30409

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2024-10-23 12:08 UTC, tresat approved these changes

2024-10-28 20:25 UTC, big-guy requested changes
IIUC, this will cause us to reprobe all the time.

We don't want to do this. We already have problems where we're caching the wrong thing for too long, so it's better to fix this in a cross-cutting way.

2024-10-28 21:55 UTC, octylFractal commented
No, this would only be when we are provisioning a new JDK (it's for checking the downloaded one, which is always going to be fresh anyways).

2024-10-29 02:33 UTC, octylFractal commented
@bot-gradle test this

2024-10-29 06:18 UTC, merged