Add a check to verify that relative markdown links are not broken
gradle/gradle pull request #30882
Opened 2024-10-11 15:50 UTC by ov7a

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2024-10-11 15:51 UTC, ov7a commented
Failing build:
* https://github.com/gradle/gradle/actions/runs/11295403820/job/31418031305?pr=30882

2024-10-14 07:44 UTC, cobexer requested changes

2024-10-14 07:44 UTC, cobexer commented on .github/workflows/check-markdown-links.yml
> +jobs:
❌ please set permission on the job level and clear permission on the top level

examples:
https://github.com/gradle/gradle/blob/13697e813e5e18e79735557a84a5b8ad261e66fc/.github/workflows/contributor-pr.yml#L23

https://github.com/gradle/gradle/blob/13697e813e5e18e79735557a84a5b8ad261e66fc/.github/workflows/contributor-pr.yml#L28

2024-10-14 07:59 UTC, cobexer approved these changes

2024-10-14 08:45 UTC, merged