Make PatternMatchers globally shared
gradle/gradle pull request #31003
Opened 2024-10-23 19:31 UTC by abstratt

`PatternMatcher` subclasses lead to a lot of state duplication with parallel CC. Stats for perf-android-large-build:

<img width="1726" alt="Screenshot 2024-10-23 at 16 20 36" src="https://github.com/user-attachments/assets/d3c0f686-c3c7-4527-a78d-f99db9def1e6">

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2024-10-23 19:31 UTC, abstratt commented
@bot-gradle test ACC

2024-10-23 20:20 UTC, mlopatkin requested changes
Good to have more deduplication! A suggestion below.

2024-10-23 20:20 UTC, mlopatkin commented on platforms/core-configuration/core-serialization-codecs/src/main/kotlin/org/gradle/internal/serialize/codecs/core/PatternMatcherCodec.kt
> +object PatternMatcherCodec: Codec<PatternMatcher> {
❓  Looks like all these classes are going to have the same implementation. Can we have a single generic class and just add parameters, kind of like the codec for unsupported types does?

2024-10-24 10:55 UTC, abstratt commented
@bot-gradle test APT

2024-11-20 10:14 UTC, alllex approved these changes
I support the refactoring suggested by Mike. It would also be nice to have a test that demonstrates the effects of the change, but I don't know if we have the infrastructure for it, and if it's worth the effort.

Otherwise, looks good

2024-11-20 10:14 UTC, alllex commented on platforms/core-configuration/core-serialization-codecs/src/main/kotlin/org/gradle/internal/serialize/codecs/core/PatternMatcherCodec.kt
> +        writeSharedObject(value) {
❓  Can we write a test that validates the sharing actually happens?

2024-11-27 14:17 UTC, abstratt commented
Thanks for the feedback. Unfortunately, we didn't get speed improvements from this change set alone, even if there was some gain in cache size reduction. Closing this PR.

2024-11-27 14:17 UTC, closed without merging