Include instance ids in CC trace
gradle/gradle pull request #31262
Opened 2024-11-12 20:37 UTC by abstratt

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2024-11-12 22:39 UTC, bamboo requested changes

2024-11-12 22:39 UTC, bamboo commented on platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/ConfigurationCacheDebugLogIntegrationTest.groovy
> +            def someObject = scriptObject
💅 I'd inline `scriptObject` here

2024-11-12 22:39 UTC, bamboo commented on platforms/core-configuration/configuration-cache/src/integTest/groovy/org/gradle/internal/cc/impl/ConfigurationCacheDebugLogIntegrationTest.groovy
> +        def scriptObject = [foo: "bar"]
💅 Indent script one level further than the enclosing `buildFile` call

2024-11-12 22:39 UTC, bamboo commented on platforms/core-configuration/graph-serialization/src/main/kotlin/org/gradle/internal/serialize/graph/Codec.kt
> +    fun open(frame: String, instance: Any? = null)
💅 The default argument values are unnecessary

2024-11-13 16:39 UTC, bamboo approved these changes

2024-11-13 19:20 UTC, abstratt commented on platforms/core-configuration/graph-serialization/src/main/kotlin/org/gradle/internal/serialize/graph/LoggingTracer.kt
> +            ?.let { System.identityHashCode(it).toString(16) to it.hashCode().toString(16) }
I wonder what they are waiting for...

2024-11-13 19:21 UTC, abstratt commented
Thanks for the reviews!

2024-11-14 20:52 UTC, merged