Donat/problems/unignore summarization test
gradle/gradle pull request #31532
Opened 2024-12-05 12:52 UTC by donat

### Context

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2024-12-05 12:55 UTC, donat commented
@bot-gradle test ACT

2024-12-06 13:16 UTC, donat commented
@bot-gradle test ACT

2024-12-09 09:08 UTC, reinsch82 requested changes
Basically one question.

2024-12-09 09:08 UTC, reinsch82 commented on platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r812/ProblemThresholdCrossVersionTest.groovy
> +        buildFile getBuildScriptSampleContent(false, false, targetVersion, 15 + exceedingCount)
❓ Use `threshold` here too?

2024-12-09 09:08 UTC, reinsch82 commented on platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r812/ProblemThresholdCrossVersionTest.groovy
> +        def totalSentEventsCount = 15 + exceedingCount
❓ Use `threshold` here too?

2024-12-09 09:08 UTC, reinsch82 commented on platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r812/ProblemThresholdCrossVersionTest.groovy
> +        validateProblemsRange(0..(15 - 1), problems)
❓ Use `threshold` here too?

2024-12-09 09:08 UTC, reinsch82 commented on platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r812/ProblemThresholdCrossVersionTest.groovy
> +        buildFile getProblemReportingScript("${getProblemReportingBody(15 + exceedingCount)}")
❓ Use `threshold` here too?

2024-12-09 09:14 UTC, donat commented on platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r812/ProblemThresholdCrossVersionTest.groovy
> +        buildFile getBuildScriptSampleContent(false, false, targetVersion, 15 + exceedingCount)
makes sense; will fix it

2024-12-09 09:14 UTC, donat commented on platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r812/ProblemThresholdCrossVersionTest.groovy
> +        validateProblemsRange(0..(15 - 1), problems)
makes sense; will fix it

2024-12-09 13:04 UTC, donat commented
@bot-gradle test this

2024-12-09 13:10 UTC, reinsch82 approved these changes
LGTM

2024-12-09 15:26 UTC, donat commented
@bot-gradle merge

2024-12-09 17:54 UTC, merged

2025-01-15 10:25 UTC, ljacomet commented
@donat You may want to look at [the feedback](https://github.com/gradle/gradle/pull/31988#pullrequestreview-2552133383) from cherry picking this to release