Map and collection property unification
gradle/gradle pull request #31635
Opened 2024-12-09 15:27 UTC by 6hundreds

This PR extracts common parent class for `DefaultMapProperty$CollectingSupplier` and `AbstractCollectingProperty$CollectingSupplier`

2024-12-09 15:28 UTC, 6hundreds commented
@bot-gradle test this on linux

2024-12-11 12:16 UTC, 6hundreds commented
@bot-gradle test this

2024-12-11 15:03 UTC, 6hundreds commented on platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectionProperty.java
> +            super(SerializableLambdas.predicate(AbstractCollectionProperty::isAbsentIgnoring), collectors, size);
With getting rid of `ignoreAbsent` concept this will be redundant.

2024-12-11 16:17 UTC, mlopatkin commented on platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectingSupplier.java
> +    protected ValueProducer getProducer(Function<COLLECTOR, ValueProducer> getProducerForCollector) {
> @mlopatkin Previously(currently in the `release` branch), the implementation of `getProducer` is not consistent:
> ...
> Obviously, I can preserve current behaviour, but I'd like to understand why it's not consistent between `MapProperty` and `CollectionProperty`?

That's just an oversight, `getProducer` for Collection property no longer expects `getProducer` to fail. See
https://github.com/gradle/gradle/commit/570bd554fdfdea1d0f52cbfa991132cbb1a683dd

2024-12-11 17:27 UTC, mlopatkin requested changes
Cool stuff!
I only have concern about not being explicit about the ArrayList.

2024-12-11 17:27 UTC, mlopatkin commented on platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/DefaultMapProperty.java
>                  }).collect(toList()),
:x: this should collect into `ArrayList` too

2024-12-12 12:59 UTC, 6hundreds commented on platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectingSupplier.java
> +    protected ValueProducer getProducer(Function<COLLECTOR, ValueProducer> getProducerForCollector) {
> I think we should keep the behavior of getPrdoucer not failing for now.

Then we should adjust MapProperty tests

2024-12-12 16:38 UTC, 6hundreds commented on platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectingSupplier.java
> +    protected ValueProducer getProducer(Function<COLLECTOR, ValueProducer> getProducerForCollector) {
@mlopatkin Thanks for the review, I've applied your comments. Would you mind to point out how to treat `GET_PRODUCER` as a safe consumer for `MapProperty` [here](https://github.com/gradle/gradle/blob/fe6592abf8f79faaeeccd6c50212bede673da7f0/platforms/core-configuration/model-core/src/test/groovy/org/gradle/api/internal/provider/MapPropertySpec.groovy#L1901)? It's kinda tricky to understand what's happening there

2024-12-13 18:02 UTC, 6hundreds commented on platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectingSupplier.java
> +    protected ValueProducer getProducer(Function<COLLECTOR, ValueProducer> getProducerForCollector) {
@mlopatkin Made `getProducer` as a safe consumer. PTAL!

2024-12-13 18:03 UTC, 6hundreds commented
@bot-gradle test this

2024-12-13 18:15 UTC, mlopatkin approved these changes

2024-12-13 18:15 UTC, mlopatkin commented on platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/AbstractCollectingSupplier.java
> +    protected ValueProducer getProducer(Function<COLLECTOR, ValueProducer> getProducerForCollector) {
> @mlopatkin Made `getProducer` as a safe consumer. PTAL!

Sorry, missed that. Glad you've figured that out!

2024-12-14 08:31 UTC, merged