Do not realize all configurations in a project by default
gradle/gradle pull request #31682
Opened 2024-12-11 23:02 UTC by jvandort

Fixes #28192

Previously, unlike tasks, Configurations of a project are automatically realized, even if they are 'register'ed or even if the new role-based factory methods are used, which are intended to be lazy.

This happens for two reasons
1. The base plugin had a configurations.all call in it in order to implement behavior related to the assemble task
2. When resolving a dependency against a target project, we would previously realize all configurations in the target project, even if they were non consumable.

This commit makes two significant changes
1. We no longer call configurations.all in the base plugin, but rather lazily add the artifacts of all visible configurations to the assemble task. This prevents all configurations from being realized instantly if the base plugin is applied.

2. We no longer realize all configurations of a target project when resolving a dependency against it. We now only realize the configurations known to be consumable or with an unknown/mutable role.

We add a new test to WellBehavedPluginTest to ensure it does not add configurations.all calls or other calls to instantly realize configurations We also add a new test suite to verify dependency resolution only realizes consumable configurations or configurations with unknown an unknown role, but does not realize configurations with a known non-consumable type.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2024-12-11 23:08 UTC, jvandort commented
@bot-gradle test this

2024-12-11 23:16 UTC, jvandort commented
@bot-gradle test apt

2024-12-12 17:49 UTC, jvandort commented
@bot-gradle test prf apt

2024-12-12 18:25 UTC, jvandort commented
@bot-gradle test prf apt

2024-12-13 17:29 UTC, jvandort commented
@bot-gradle test this

2024-12-16 04:26 UTC, lkasso commented on platforms/documentation/docs/src/docs/release/notes.md
> +Configurations should be declared using the `register` method instead of the `create` method to take advantage of the lazy initialization.
Can we add a code snippet here? It will be more impactful for people that are glancing at the release notes.

2024-12-16 04:29 UTC, lkasso commented on platforms/documentation/docs/src/docs/release/notes.md
> +Similar to Tasks, Configurations are now initialized lazily, only when necessary.
```suggestion
Similar to [Tasks](userguide/lazy_configuration.html), Configurations are now initialized lazily when necessary.
```

2024-12-16 04:32 UTC, lkasso commented on platforms/documentation/docs/src/docs/release/notes.md
> +Now, when applying the `Base` plugin or any plugins derived from it such as the JVM plugins, configurations that are lazily declared using `register` or through the incubating role-based factory meth
```suggestion
Starting with this release, applying the `Base` plugin or any of its derived plugins (e.g., JVM plugins) ensures that configurations declared using `register` or the incubating role-based factory methods are no longer eagerly realized unless required.
```

2025-01-17 03:43 UTC, jvandort commented on platforms/software/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/LazyConfigurationResolveIntegrationTest.groovy
> +                // TODO: A lazy extendsFrom mechanism would allow us to avoid realizing otherDependencies
Or getting rid of Configurations completely? 😤

2025-01-22 18:52 UTC, jvandort commented on platforms/software/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/LazyConfigurationResolveIntegrationTest.groovy
> +    def "realizes non-role-locked configurations in target project"() {
The first one verifies that role-locked configurations are not realized when consuming variants from a given project. 

This test verifies that non-role-locked (unlocked) configurations _are_ realized when consuming variants from a given project.

2025-01-22 18:54 UTC, jvandort commented on platforms/software/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/LazyConfigurationResolveIntegrationTest.groovy
> +        outputDoesNotContain("Realizing configuration")
Updated the test to print `Realizing configuration` as the other tests do, and properly verify the output

2025-01-22 19:03 UTC, jvandort commented on subprojects/core-api/src/main/java/org/gradle/api/artifacts/UnlockedConfiguration.java
> +public interface UnlockedConfiguration extends Configuration {
You are suggesting just a rename here?

I'm not against a rename here, but would like to throw my 2 cents in for the new name.

1. I would say all configurations are role based. ConsumableConfiguration has a role with the consumable usage, ResolvableConfiguration has a role with the resolvable usage, and DependencyScopeConfiguration has a role with the dependency scope usage. However, all of these configurations may not have their role changed.

2. This configuration, like the others, has a concept of a role. However, most importantly, these configurations may have multiple roles, and _the roles it has might change_. 

For that reason, I would vote against `RoleBasedConfiguration`, as I think all of the above mentioned configuration types are role based. I think the important thing to focus on here for the name is 

1. The role is mutable
2. The role may have more than one usage

Thoughts?

2025-01-22 19:10 UTC, jvandort commented on platforms/software/platform-base/src/main/java/org/gradle/api/internal/plugins/DefaultArtifactPublicationSet.java
> +    public DefaultArtifactPublicationSet(ConfigurationContainer configurations, String aggregateArtifactsConfName) {
Yeah I don't think this should accept a Configuration as parameter, as the purpose of this class is to aggregate artifacts from all configurations that are _not_ the aggregate configuration, and add those artifacts to the aggregate configuration.


I agree this needs some documentation and I will add that in this PR. 


Just to clarify some things here, this class encapsulates legacy behavior causes all artifacts of all `isVisible()` configurations to be built when the `assemble` task is executed. This is done in a convoluted way (and remains so due to backwards compatibility). We first add all non-visible artifacts to the `archives` configuration. Then, in the `base` plugin, we make sure the `assemble` task depends on all artifacts from the `archives` configurations.

In terms of all the changing state, yeah thats some ugly stuff too but ATM remains for backwards compatibility. It is some legacy code that tries to "intelligently" determine if some artifacts should be added to the archives configuration or not (and and as a result, if they should be built by `assemble` or not). It ends up causing more problems than not.


Ideally, all of this would be deprecated and I think we are getting close to being able to do so. ATM Kotlin depends on this internal API, which I have filed [an issue](https://youtrack.jetbrains.com/issue/KT-74476/KGP-uses-internal-Gradle-API-DefaultArtifactPublicationSet) for and they plan to resolve by 9.0. However, for now this code and its complexities must remain here

2025-01-22 19:17 UTC, jvandort commented on platforms/documentation/docs/src/docs/release/notes.md
> +Configurations should be declared using the `register` method instead of the `create` method to take advantage of the lazy initialization.
Added

2025-01-22 19:17 UTC, jvandort commented on platforms/documentation/docs/src/docs/release/notes.md
> +Similar to Tasks, Configurations are now initialized lazily, only when necessary.
Reworded

2025-01-22 19:18 UTC, jvandort commented on platforms/documentation/docs/src/docs/release/notes.md
> +Now, when applying the `Base` plugin or any plugins derived from it such as the JVM plugins, configurations that are lazily declared using `register` or through the incubating role-based factory meth
Reworded

2025-01-22 19:18 UTC, jvandort commented on platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ConfigurationsProvider.java
> +     * Visit all consumable configurations provided by this configurations provider.
Reworded

2025-01-22 19:18 UTC, jvandort commented on platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/ConfigurationsProvider.java
> +     * Lazy configurations which are known to be non-consumable are not realized.
Reworded

2025-01-22 19:53 UTC, jvandort commented on platforms/software/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/api/LazyConfigurationResolveIntegrationTest.groovy
> +class LazyConfigurationResolveIntegrationTest extends AbstractIntegrationSpec {
Made some small improvements to the tests

2025-01-22 19:53 UTC, jvandort commented
@bot-gradle test this

2025-01-23 23:16 UTC, big-guy requested changes
I left some comments on the release notes, but I didn't dig into the full implementation.

2025-01-23 23:16 UTC, big-guy commented on platforms/documentation/docs/src/docs/release/notes.md
> +Similar to [Tasks](userguide/lazy_configuration.html), Configurations are now initialized lazily when necessary.
```suggestion
Similar to [tasks](userguide/lazy_configuration.html), Configurations are only realized when necessary. 
```

2025-01-23 23:16 UTC, big-guy commented on platforms/documentation/docs/src/docs/release/notes.md
> +Starting with this release, applying the `Base` plugin or any of its derived plugins (e.g., JVM plugins) will not cause configurations declared using `register` or using the incubating role-based fac
This should be `base` and possibly link to base_plugin user manual chapter. 

```suggestion
Starting with this release, applying the `base` plugin or any plugin that applies the `base` plugin (e.g., JVM plugins) will no longer realize all configurations declared using `register` or the incubating role-based factory methods. 

In some builds, this will reduce configuration time and memory usage. 
```

2025-01-23 23:16 UTC, big-guy commented on platforms/documentation/docs/src/docs/release/notes.md
> +Configurations should be declared using the `register` method instead of the `create` method to take advantage of the lazy initialization.
```suggestion
Configurations should be declared using the `register` method instead of the `create` methods to have the largest impact.
```

2025-01-23 23:16 UTC, big-guy commented on platforms/documentation/docs/src/docs/release/notes.md
> +    // Use `register` to lazily initialize the configuration
```suggestion
    // Use `register` to avoid realizing the configuration
```

2025-01-23 23:16 UTC, big-guy commented on platforms/documentation/docs/src/docs/release/notes.md
> +Starting with this release, applying the `Base` plugin or any of its derived plugins (e.g., JVM plugins) will not cause configurations declared using `register` or using the incubating role-based fac
Do we have any way of quantifying the impact?

2025-01-23 23:17 UTC, jvandort commented on platforms/documentation/docs/src/docs/release/notes.md
> +Starting with this release, applying the `Base` plugin or any of its derived plugins (e.g., JVM plugins) will not cause configurations declared using `register` or using the incubating role-based fac
I don't expect much atm. But, I would expect more when the JVM plugins switch over to registering role-locked configurations 9.0 (vs eagerly creating unlocked configurations)

2025-01-24 16:42 UTC, big-guy commented on subprojects/core-api/src/main/java/org/gradle/api/artifacts/UnlockedConfiguration.java
> +public interface UnlockedConfiguration extends Configuration {
What about `LegacyConfiguration`? This is what we've referred to it in other contexts.

2025-01-27 19:31 UTC, jvandort commented
@bot-gradle test this

2025-01-27 20:01 UTC, tresat commented on subprojects/core-api/src/main/java/org/gradle/api/artifacts/UnlockedConfiguration.java
> +public interface UnlockedConfiguration extends Configuration {
I like `LegacyConfiguration`.

2025-01-27 21:36 UTC, lkasso commented on platforms/documentation/docs/src/docs/release/notes.md
> +Similar to [tasks](userguide/lazy_configuration.html), Configurations are now only realized when necessary.
```suggestion
Similar to [tasks](userguide/lazy_configuration.html), [configurations](userguide/declaring_configurations.html) are now realized only when necessary.
```

2025-01-27 21:36 UTC, lkasso commented on platforms/documentation/docs/src/docs/release/notes.md
> +Starting with this release, applying the `base` plugin or any plugin that applies the `base` plugin (e.g., JVM plugins) will no longer realize all configurations declared using `register` or the incu
```suggestion
Starting with this release, applying the `base` plugin (or any plugin that applies it, such as JVM plugins) no longer realizes all configurations declared using `register` or the incubating role-based factory methods.
```

2025-01-27 21:36 UTC, lkasso commented on platforms/documentation/docs/src/docs/release/notes.md
> +In some builds, this will reduce configuration time and memory usage.
```suggestion
This change can reduce configuration time and memory usage in some builds.
```

2025-01-27 21:36 UTC, lkasso commented on platforms/documentation/docs/src/docs/release/notes.md
> +Configurations should be declared using the `register` method instead of the `create` methods to have the largest impact.
```suggestion
To leverage these improvements, declare configurations using the `register` method instead of the `create` method:
```

2025-01-27 23:29 UTC, jvandort commented on subprojects/core-api/src/main/java/org/gradle/api/artifacts/UnlockedConfiguration.java
> +public interface UnlockedConfiguration extends Configuration {
Renamed to `LegacyConfiguration`

2025-01-27 23:30 UTC, jvandort commented
@bot-gradle test this

2025-02-03 16:45 UTC, ghale approved these changes
There are so many things wrong with `DefaultArtifactPublicationSet` I don't don't even know where to get started (not things you've done in this PR, just the existence of this class).  The sooner we kill it with fire, the better.

These changes seem fine to me, assuming we actually _do_ get rid of this class soon.

2025-02-04 17:21 UTC, merged