Donat/problems/stabilization step5
gradle/gradle pull request #31854
Opened 2024-12-20 11:40 UTC by donat

### Context

### Contributor Checklist
- [ ] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md).
- [ ] Make sure that all commits are [signed off](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) to indicate that you agree to the terms of [Developer Certificate of Origin](https://developercertificate.org/).
- [ ] Make sure all contributed code can be distributed under the terms of the [Apache License 2.0](https://github.com/gradle/gradle/blob/master/LICENSE), e.g. the code was written by yourself or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team.
- [ ] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective.
- [ ] Provide unit tests (under `<subproject>/src/test`) to verify logic.
- [ ] Update User Guide, DSL Reference, and Javadoc for public-facing changes.
- [ ] Ensure that tests pass sanity check: `./gradlew sanityCheck`.
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:quickTest`.

### Reviewing cheatsheet

Before merging the PR, comments starting with 
- ❌ ❓**must** be fixed
- 🤔 💅 **should** be fixed
- 💭 **may** be fixed
- 🎉 celebrate happy things

2024-12-20 11:40 UTC, donat commented
@bot-gradle test this

2024-12-20 12:02 UTC, donat commented
[WIP] Add mandatory problem ID to ProblemReporter function args

2024-12-20 12:03 UTC, donat commented
@bot-gradle test this

2024-12-20 15:07 UTC, donat commented
@bot-gradle test ReadyForNightly

2024-12-27 09:18 UTC, hegyibalint requested changes

2025-01-02 08:38 UTC, donat commented on platforms/jvm/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/daemon/DaemonGroovyCompiler.java
> +                ProblemId problemId = ProblemId.create("groovy-daemon-compiler", "Missing tools.jar", GradleCoreProblemGroup.compilation().groovy());
I only reused what I found :) Right now, I'm leaning towards the `compilation:groovy:missing-tools-jar` id. We can consider converting this to Gradle-internal problem ID separately.

2025-01-02 10:03 UTC, donat commented
@bot-gradle test ACTR

2025-01-02 10:20 UTC, hegyibalint approved these changes
Replied to comments, PTAL.
No blockers from my side anymore: can be merged!

2025-01-02 10:20 UTC, hegyibalint commented on platforms/ide/tooling-api/src/crossVersionTest/groovy/org/gradle/integtests/tooling/r812/BuildFailureProblemsCrossVersionSpec.groovy
> +                     getProblems().getReporter().throwing(${targetVersion >= GradleVersion.version('8.13') ? 'new RuntimeException("Exception message", wrappedException), ' + ProblemsApiGroovyScriptU
💭 This is not exactly what I meant – if your change is based on my feedback. My idea is to create completely separate, even if repetitive, methods for reporting a problem. In this case, that would be from L140:144.

What you did is also fine; I'm just expressing that this wasn't my exact idea.

2025-01-02 10:20 UTC, hegyibalint commented on platforms/jvm/language-groovy/src/main/java/org/gradle/api/internal/tasks/compile/daemon/DaemonGroovyCompiler.java
> +                ProblemId problemId = ProblemId.create("groovy-daemon-compiler", "Missing tools.jar", GradleCoreProblemGroup.compilation().groovy());
As I said, I have no strong preferences over here. I still think this is a sort of _infrastructure problem_, and this doesn't communicate that well. OTOH the importance of this is really low.

It's more about thinking and establishing best practices, which we could document for the larger community.

2025-01-02 10:20 UTC, hegyibalint commented on platforms/core-execution/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorProblemsApiIntegrationTest.groovy
> +                     getProblems().getReporter().report(org.gradle.api.problems.ProblemId.create("type", "label", org.gradle.api.problems.ProblemGroup.create("generic", "Generic")), problem -> proble
You gave a 👍 but I don't see any change related to this. Can you confirm?

2025-01-02 12:27 UTC, donat commented on platforms/core-execution/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorProblemsApiIntegrationTest.groovy
> +                     getProblems().getReporter().report(org.gradle.api.problems.ProblemId.create("type", "label", org.gradle.api.problems.ProblemGroup.create("generic", "Generic")), problem -> proble
Something is off, I did change that. The latest state looks like this:
```
  // Create and report a problem
  // This needs to be Java 6 compatible, as we are in a worker
  ProblemId problemId = ProblemId.create("type", "label", ProblemGroup.create("generic", "Generic"));
  getProblems().getReporter().report(problemId, problem -> problem
      .stackLocation()
      .withException(new RuntimeException("Exception message", wrappedException))
  );
```

2025-01-02 12:31 UTC, donat commented
@bot-gradle merge

2025-01-02 15:22 UTC, donat commented
@bot-gradle merge

2025-01-02 15:45 UTC, donat commented
@bot-gradle merge

2025-01-02 16:27 UTC, donat commented
@bot-gradle test RFN

2025-01-02 22:40 UTC, MrG9090 commented on platforms/core-execution/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorProblemsApiIntegrationTest.groovy
platforms/core-execution/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorProblemsApiIntegrationTest.groovy

2025-01-03 08:34 UTC, donat commented
@bot-gradle merge

2025-01-03 10:30 UTC, merged